// lib/lexicon/hi-core.ts
//
// Function words, pronouns, postpositions, auxiliaries, question words, and the
// highest-frequency core vocabulary. This is the most valuable bank in the
// project: these are the tokens that collide with English (Section 3.2), and
// every one of them carries a language-ID prior.
//
// Transcription conventions, held constant across every bank:
//   - Hindi /h/ is the voiced glottal ɦ (Appendix E lists ɦ as Hindi-specific).
//   - Dental t̪ d̪ for Hindi t/d; retroflex ʈ ɖ ɽ only where genuinely retroflex.
//   - Vowel length is contrastive and always marked: ə vs aː, ɪ vs iː, ʊ vs uː.
//   - Nasalization is a tilde on the vowel, never a separate coda: maiṁ = mɛ̃ː.
//   - Word-final inherent schwa is never written: kamal = kəməl, not kəmələ.

import type { HiRow } from './hi-lexeme';

export const HI_CORE_ROWS: HiRow[] = [
  // ---- Pronouns -----------------------------------------------------------
  ['main', 'mai|maiN|mein|men', 'मैं', 'mɛ̃ː', 'I', 'pron', '', 12],
  ['mujhe', 'muje|mujhey', 'मुझे', 'mʊdʒʰeː', 'to me', 'pron', '', 48],
  ['mujhko', 'mujko', 'मुझको', 'mʊdʒʰkoː', 'to me', 'pron', '', 320],
  ['mera', 'meraa', 'मेरा', 'meːraː', 'my (m)', 'pron', '', 30],
  ['meri', 'merii|mery', 'मेरी', 'meːriː', 'my (f)', 'pron', '', 31],
  ['mere', 'merey', 'मेरे', 'meːreː', 'my (m pl/obl)', 'pron', '', 32],
  ['hum', 'ham', 'हम', 'ɦəm', 'we', 'pron', '', 22],
  ['humein', 'hamein|hume|humein', 'हमें', 'ɦəmẽː', 'to us', 'pron', '', 110],
  ['hamara', 'humara|hamaara', 'हमारा', 'ɦəmaːraː', 'our (m)', 'pron', '', 96],
  ['hamari', 'humari|hamaari', 'हमारी', 'ɦəmaːriː', 'our (f)', 'pron', '', 97],
  ['tu', 'too', 'तू', 't̪uː', 'you (intimate)', 'pron', '', 40],
  ['tum', 'tumm', 'तुम', 't̪ʊm', 'you (familiar)', 'pron', '', 26],
  ['tumhe', 'tumhein|tumhe', 'तुम्हें', 't̪ʊmɦẽː', 'to you', 'pron', '', 88],
  ['tera', 'teraa', 'तेरा', 't̪eːraː', 'your (m)', 'pron', '', 52],
  ['teri', 'terii', 'तेरी', 't̪eːriː', 'your (f)', 'pron', '', 53],
  ['tere', 'terey', 'तेरे', 't̪eːreː', 'your (m pl/obl)', 'pron', '', 54],
  ['tumhara', 'tumhaara', 'तुम्हारा', 't̪ʊmɦaːraː', 'your (m)', 'pron', '', 140],
  ['aap', 'ap|aap', 'आप', 'aːp', 'you (formal)', 'pron', '', 44],
  ['vo', 'wo|woh|voh', 'वो', 'ʋoː', 'he/she/that', 'pron', '', 18],
  ['ye', 'yeh|yeah', 'ये', 'jeː', 'this/these', 'pron', '', 20],
  ['is', 'iss', 'इस', 'ɪs', 'this (oblique)', 'pron', '', 66],
  ['us', 'uss', 'उस', 'ʊs', 'that (oblique)', 'pron', '', 68],
  ['isko', 'isko', 'इसको', 'ɪskoː', 'to this', 'pron', '', 190],
  ['usko', 'usko', 'उसको', 'ʊskoː', 'to that/him', 'pron', '', 150],
  ['uska', 'uskaa', 'उसका', 'ʊskaː', 'his/its', 'pron', '', 120],
  ['uski', 'uskii', 'उसकी', 'ʊskiː', 'her/its', 'pron', '', 121],
  ['unka', 'unkaa', 'उनका', 'ʊnkaː', 'their', 'pron', '', 175],
  ['inka', 'inkaa', 'इनका', 'ɪnkaː', 'their (prox)', 'pron', '', 260],
  ['khud', 'khudh', 'खुद', 'kʰʊd̪', 'oneself', 'pron', '', 210],
  ['apna', 'apnaa', 'अपना', 'əpnaː', 'own (m)', 'pron', '', 100],
  ['apni', 'apnii', 'अपनी', 'əpniː', 'own (f)', 'pron', '', 101],
  ['apne', 'apney', 'अपने', 'əpneː', 'own (pl/obl)', 'pron', '', 102],

  // ---- Postpositions ------------------------------------------------------
  ['ka', 'kaa', 'का', 'kaː', 'of (m)', 'postp', '', 4],
  ['ki', 'kii|ky', 'की', 'kiː', 'of (f)', 'postp', '', 5],
  ['ke', 'key', 'के', 'keː', 'of (pl/obl)', 'postp', '', 6],
  ['ko', 'koo', 'को', 'koː', 'to (dative)', 'postp', '', 7],
  ['se', 'sey', 'से', 'seː', 'from/with/by', 'postp', '', 8],
  // IPA uses combining tilde (U+0303), not the precomposed ẽ, so parseIpa and
  // the rest of the inventory share one representation. `main` is intentionally
  // absent from variants — that spelling belongs to the pronoun above; context
  // is what disambiguates the two when a writer types `mein`.
  ['mein', 'me|men|mein', 'में', 'mẽː', 'in', 'postp', '', 9],
  ['par', 'pe|pey|parr', 'पर', 'pər', 'on/at/but', 'postp', '', 14],
  ['ne', 'ney', 'ने', 'neː', 'ergative marker', 'postp', '', 16],
  ['tak', 'takk', 'तक', 't̪ək', 'until/up to', 'postp', '', 62],
  ['sath', 'saath|saathh', 'साथ', 'saːt̪ʰ', 'with/together', 'postp', '', 70],
  ['bina', 'binaa', 'बिना', 'bɪnaː', 'without', 'postp', '', 230],
  ['liye', 'liyay|liey', 'लिये', 'lɪjeː', 'for (purpose)', 'postp', '', 80],
  ['wala', 'vala|waala|vaala', 'वाला', 'ʋaːlaː', 'one who / -er (m)', 'postp', 'slang', 90],
  ['wali', 'vali|waali', 'वाली', 'ʋaːliː', 'one who / -er (f)', 'postp', 'slang', 91],
  ['wale', 'vale|waale', 'वाले', 'ʋaːleː', 'ones who (pl)', 'postp', 'slang', 92],
  ['upar', 'oopar|upper', 'ऊपर', 'uːpər', 'above/up', 'adv', '', 145],
  ['neeche', 'niche|nichey', 'नीचे', 'niːtʃeː', 'below/down', 'adv', '', 146],
  ['andar', 'undar', 'अंदर', 'ənd̪ər', 'inside', 'adv', '', 148],
  ['bahar', 'baahar|baher', 'बाहर', 'baːɦər', 'outside', 'adv', '', 149],
  ['peeche', 'piche|pichey', 'पीछे', 'piːtʃʰeː', 'behind/after', 'adv', '', 152],
  ['aage', 'aagey|age', 'आगे', 'aːgeː', 'ahead/forward', 'adv', '', 153],
  ['beech', 'bich|beach', 'बीच', 'biːtʃ', 'middle/between', 'noun', '', 240],
  ['paas', 'pas|pass', 'पास', 'paːs', 'near/with', 'postp', '', 108],

  // ---- Conjunctions and particles ----------------------------------------
  ['aur', 'or|our|awr', 'और', 'ɔːr', 'and/more', 'conj', '', 10],
  ['ya', 'yaa', 'या', 'jaː', 'or', 'conj', '', 60],
  ['to', 'toh|tho', 'तो', 't̪oː', 'so/then', 'conj', '', 11],
  ['bhi', 'bhee|bi', 'भी', 'bʰiː', 'also/even', 'adv', '', 13],
  ['hi', 'hee', 'ही', 'ɦiː', 'only/emphatic', 'adv', '', 24],
  ['phir', 'fir|phir|firr', 'फिर', 'pʰɪr', 'then/again', 'adv', '', 28],
  ['lekin', 'lekhin', 'लेकिन', 'leːkɪn', 'but', 'conj', '', 64],
  ['magar', 'mager', 'मगर', 'məgər', 'but', 'conj', '', 165],
  ['agar', 'ager', 'अगर', 'əgər', 'if', 'conj', '', 76],
  ['kyunki', 'kyonki|kyuki|kyunkey', 'क्योंकि', 'kjõːkɪ', 'because', 'conj', '', 130],
  ['warna', 'varna|warnaa', 'वरना', 'ʋərnaː', 'otherwise', 'conj', '', 250],
  ['jaise', 'jaisey|jese', 'जैसे', 'dʒɛːseː', 'like/as', 'conj', '', 105],
  ['waise', 'vaise|waisey', 'वैसे', 'ʋɛːseː', 'like that/anyway', 'conj', '', 155],
  ['matlab', 'matlub', 'मतलब', 'mət̪ləb', 'meaning/so', 'noun', 'slang', 115],
  ['yaar', 'yar|yaaar', 'यार', 'jaːr', 'friend/dude', 'noun', 'slang', 95],
  ['bas', 'bass', 'बस', 'bəs', 'enough/just', 'adv', '', 72],
  ['sirf', 'sirff', 'सिर्फ़', 'sɪrf', 'only', 'adv', '', 160],
  ['abhi', 'abhee', 'अभी', 'əbʰiː', 'right now', 'adv', '', 74],
  ['kabhi', 'kabhee', 'कभी', 'kəbʰiː', 'sometime/ever', 'adv', '', 112],
  ['zara', 'zaraa|jara', 'ज़रा', 'zəraː', 'a little/just', 'adv', 'slang', 220],

  // ---- Negation -----------------------------------------------------------
  ['nahi', 'nahin|nai|nahee|nhi', 'नहीं', 'nəɦĩː', 'no/not', 'adv', '', 15],
  ['na', 'naa', 'ना', 'naː', "not / isn't it", 'adv', '', 34],
  ['mat', 'matt', 'मत', 'mət̪', "don't (imperative)", 'adv', '', 170],
  ['bilkul', 'bilkool|bilqul', 'बिल्कुल', 'bɪlkʊl', 'absolutely', 'adv', '', 185],

  // ---- Question words -----------------------------------------------------
  ['kya', 'kyaa|kia|keya', 'क्या', 'kjaː', 'what', 'pron', '', 19],
  ['kaun', 'kon|koun', 'कौन', 'kɔːn', 'who', 'pron', '', 78],
  ['kab', 'kabb', 'कब', 'kəb', 'when', 'adv', '', 82],
  ['kahan', 'kaha|kahaan|kahai', 'कहाँ', 'kəɦãː', 'where', 'adv', '', 84],
  ['kaise', 'kese|kaisey', 'कैसे', 'kɛːseː', 'how', 'adv', '', 86],
  ['kaisa', 'kesa|kaisaa', 'कैसा', 'kɛːsaː', 'how/what kind (m)', 'adj', '', 128],
  ['kyun', 'kyon|kyu|kyoon', 'क्यों', 'kjõː', 'why', 'adv', '', 80],
  ['kitna', 'kitnaa', 'कितना', 'kɪt̪naː', 'how much (m)', 'adj', '', 118],
  ['kitni', 'kitnii', 'कितनी', 'kɪt̪niː', 'how much (f)', 'adj', '', 119],
  ['konsa', 'kaunsa|konsaa', 'कौनसा', 'kɔːnsaː', 'which (m)', 'adj', '', 265],

  // ---- Copula and auxiliaries --------------------------------------------
  ['hai', 'hay|he|hei', 'है', 'ɦɛː', 'is', 'verb', '', 2],
  ['hain', 'hai|hein|hn', 'हैं', 'ɦɛ̃ː', 'are', 'verb', '', 3],
  ['hun', 'hoon|hu|huun', 'हूँ', 'ɦũː', 'am', 'verb', '', 17],
  ['ho', 'hoo', 'हो', 'ɦoː', 'are/be', 'verb', '', 21],
  ['tha', 'thaa', 'था', 't̪ʰaː', 'was (m)', 'verb', '', 23],
  ['thi', 'thii', 'थी', 't̪ʰiː', 'was (f)', 'verb', '', 25],
  ['the', 'they|thay', 'थे', 't̪ʰeː', 'were', 'verb', '', 27],
  ['hoga', 'hogaa', 'होगा', 'ɦoːgaː', 'will be (m)', 'verb', '', 56],
  ['hogi', 'hogii', 'होगी', 'ɦoːgiː', 'will be (f)', 'verb', '', 57],
  ['honge', 'hongey', 'होंगे', 'ɦõːgeː', 'will be (pl)', 'verb', '', 58],
  ['hota', 'hotaa', 'होता', 'ɦoːt̪aː', 'happens (m)', 'verb', '', 106],
  ['hoti', 'hotii', 'होती', 'ɦoːt̪iː', 'happens (f)', 'verb', '', 107],
  ['hua', 'huaa|hwa', 'हुआ', 'ɦʊaː', 'happened (m)', 'verb', '', 98],
  ['hui', 'huii', 'हुई', 'ɦʊiː', 'happened (f)', 'verb', '', 99],
  ['rahe', 'rahey', 'रहे', 'rəɦeː', 'staying/-ing (pl)', 'verb', '', 103],
  ['raha', 'rahaa', 'रहा', 'rəɦaː', 'staying/-ing (m)', 'verb', '', 50],
  ['rahi', 'rahii', 'रही', 'rəɦiː', 'staying/-ing (f)', 'verb', '', 51],
  ['gaya', 'gayaa|gya', 'गया', 'gəjaː', 'went (m)', 'verb', '', 46],
  ['gayi', 'gai|gayee', 'गई', 'gəiː', 'went (f)', 'verb', '', 47],
  ['diya', 'diyaa|dia', 'दिया', 'd̪ɪjaː', 'gave', 'verb', '', 94],
  ['liya', 'liyaa|lia', 'लिया', 'lɪjaː', 'took', 'verb', '', 104],

  // ---- karna and the highest-frequency verbs -----------------------------
  ['karna', 'karnaa|krna', 'करना', 'kərnaː', 'to do', 'verb', '', 36],
  ['karta', 'kartaa|krta', 'करता', 'kərt̪aː', 'does (m)', 'verb', '', 37],
  ['karti', 'kartii', 'करती', 'kərt̪iː', 'does (f)', 'verb', '', 38],
  ['karte', 'kartey', 'करते', 'kərt̪eː', 'do (pl)', 'verb', '', 39],
  ['kar', 'kr|car', 'कर', 'kər', 'do (stem)', 'verb', '', 29],
  ['kiya', 'kiyaa|kia', 'किया', 'kɪjaː', 'did', 'verb', '', 42],
  ['karo', 'kro', 'करो', 'kəroː', 'do (imperative)', 'verb', '', 116],
  ['karun', 'karoon|karu', 'करूँ', 'kərũː', 'should I do', 'verb', '', 195],
  ['karunga', 'karoonga|krunga', 'करूँगा', 'kərũːgaː', 'will do (m)', 'verb', '', 196],
  ['jana', 'jaana', 'जाना', 'dʒaːnaː', 'to go', 'verb', '', 65],
  ['jata', 'jaata', 'जाता', 'dʒaːt̪aː', 'goes (m)', 'verb', '', 132],
  ['jaunga', 'jaoonga', 'जाऊँगा', 'dʒaːũːgaː', 'will go (m)', 'verb', '', 198],
  ['aana', 'ana', 'आना', 'aːnaː', 'to come', 'verb', '', 75],
  ['aaya', 'aya|aayaa', 'आया', 'aːjaː', 'came (m)', 'verb', '', 76],
  ['aayi', 'aai|ayi', 'आई', 'aːiː', 'came (f)', 'verb', '', 77],
  ['dena', 'denaa', 'देना', 'd̪eːnaː', 'to give', 'verb', '', 122],
  ['lena', 'lenaa', 'लेना', 'leːnaː', 'to take', 'verb', '', 124],
  ['dekhna', 'dekhnaa|dekna', 'देखना', 'd̪eːkʰnaː', 'to see', 'verb', '', 126],
  ['dekh', 'dekhh', 'देख', 'd̪eːkʰ', 'look (stem)', 'verb', '', 127],
  ['dekha', 'dekhaa', 'देखा', 'd̪eːkʰaː', 'saw (m)', 'verb', '', 129],
  ['bolna', 'bolnaa', 'बोलना', 'boːlnaː', 'to speak', 'verb', '', 134],
  ['bol', 'boll', 'बोल', 'boːl', 'speak (stem)', 'verb', '', 135],
  ['sunna', 'sunnaa', 'सुनना', 'sʊnnaː', 'to hear', 'verb', '', 136],
  ['sun', 'sunn', 'सुन', 'sʊn', 'listen (stem)', 'verb', '', 137],
  ['rehna', 'rahna|rehnaa', 'रहना', 'rəɦnaː', 'to stay/live', 'verb', '', 138],
  ['milna', 'milnaa', 'मिलना', 'mɪlnaː', 'to meet/get', 'verb', '', 142],
  ['mila', 'milaa', 'मिला', 'mɪlaː', 'got/met (m)', 'verb', '', 143],
  ['chalna', 'chalnaa', 'चलना', 'tʃəlnaː', 'to walk/move', 'verb', '', 144],
  ['chal', 'chall', 'चल', 'tʃəl', 'move (stem)', 'verb', 'slang', 147],
  ['samajh', 'samaj|samajhh', 'समझ', 'səmədʒʰ', 'understanding', 'noun', '', 156],
  ['samajhna', 'samajhnaa|samajna', 'समझना', 'səmədʒʰnaː', 'to understand', 'verb', '', 157],
  ['sochna', 'sochnaa', 'सोचना', 'soːtʃnaː', 'to think', 'verb', '', 158],
  ['soch', 'sochh', 'सोच', 'soːtʃ', 'thought', 'noun', '', 159],
  ['banana', 'banaana', 'बनाना', 'bənaːnaː', 'to make', 'verb', '', 162],
  ['likhna', 'likhnaa', 'लिखना', 'lɪkʰnaː', 'to write', 'verb', '', 164],
  ['padhna', 'padna|padhnaa', 'पढ़ना', 'pəɽʰnaː', 'to read/study', 'verb', '', 166],
  ['khana', 'khaana', 'खाना', 'kʰaːnaː', 'to eat / food', 'verb', '', 168],
  ['pina', 'peena', 'पीना', 'piːnaː', 'to drink', 'verb', '', 172],
  ['sona', 'sonaa', 'सोना', 'soːnaː', 'to sleep / gold', 'verb', '', 174],
  ['uthna', 'uthnaa', 'उठना', 'ʊʈʰnaː', 'to rise', 'verb', '', 176],
  ['girna', 'girnaa', 'गिरना', 'gɪrnaː', 'to fall', 'verb', '', 178],
  ['todna', 'todnaa|tornaa', 'तोड़ना', 't̪oːɽnaː', 'to break', 'verb', '', 180],
  ['chhodna', 'chodna|chhornaa', 'छोड़ना', 'tʃʰoːɽnaː', 'to leave', 'verb', '', 182],
  ['rakhna', 'rakhnaa', 'रखना', 'rəkʰnaː', 'to keep', 'verb', '', 184],
  ['lagna', 'lagnaa', 'लगना', 'ləgnaː', 'to seem/feel', 'verb', '', 186],
  ['lagta', 'lagtaa', 'लगता', 'ləgt̪aː', 'seems (m)', 'verb', '', 187],
  ['marna', 'marnaa', 'मरना', 'mərnaː', 'to die', 'verb', '', 188],
  ['jeena', 'jina|jeenaa', 'जीना', 'dʒiːnaː', 'to live', 'verb', '', 189],
  ['hasna', 'hansna|hasnaa', 'हँसना', 'ɦə̃snaː', 'to laugh', 'verb', '', 191],
  ['rona', 'ronaa', 'रोना', 'roːnaː', 'to cry', 'verb', '', 192],
  ['bhagna', 'bhaagna', 'भागना', 'bʰaːgnaː', 'to run', 'verb', '', 193],
  ['pucha', 'poocha|puchha', 'पूछा', 'puːtʃʰaː', 'asked', 'verb', '', 194],

  // ---- Time ---------------------------------------------------------------
  ['aaj', 'aj|aaaj', 'आज', 'aːdʒ', 'today', 'adv', '', 61],
  ['kal', 'kall', 'कल', 'kəl', 'yesterday / tomorrow', 'adv', '', 63,
    [{ ipa: 'kaːl', gloss: 'time / death / famine', devanagari: 'काल' }]],
  ['parso', 'parsoon', 'परसों', 'pərsõː', 'day before/after tomorrow', 'adv', '', 300],
  ['ab', 'abb', 'अब', 'əb', 'now', 'adv', '', 45],
  ['tab', 'tabb', 'तब', 't̪əb', 'then', 'adv', '', 111],
  ['jab', 'jabb', 'जब', 'dʒəb', 'when (rel)', 'conj', '', 67],
  ['raat', 'rat|raath', 'रात', 'raːt̪', 'night', 'noun', '', 93],
  ['din', 'dinn', 'दिन', 'd̪ɪn', 'day', 'noun', '', 79],
  ['subah', 'subha|suba', 'सुबह', 'sʊbəɦ', 'morning', 'noun', '', 133],
  ['shaam', 'sham|shaam', 'शाम', 'ʃaːm', 'evening', 'noun', '', 141],
  ['saal', 'sal|saall', 'साल', 'saːl', 'year', 'noun', '', 151],
  ['mahina', 'maheena', 'महीना', 'məɦiːnaː', 'month', 'noun', '', 235],
  ['hafta', 'haftaa', 'हफ़्ता', 'ɦəft̪aː', 'week', 'noun', '', 245],
  ['waqt', 'vaqt|wakt', 'वक़्त', 'ʋəqt̪', 'time', 'noun', 'filmi', 113],
  ['samay', 'samey', 'समय', 'səməj', 'time', 'noun', '', 205],
  ['der', 'derr', 'देर', 'd̪eːr', 'lateness/delay', 'noun', '', 215],
  ['jaldi', 'jaldee', 'जल्दी', 'dʒəld̪iː', 'quickly/early', 'adv', '', 200],
  ['hamesha', 'hamesha|humesha', 'हमेशा', 'ɦəmeːʃaː', 'always', 'adv', '', 225],
  ['roz', 'rozz|roj', 'रोज़', 'roːz', 'daily', 'adv', '', 232],

  // ---- Core nouns that carry the writing --------------------------------
  ['dil', 'dill', 'दिल', 'd̪ɪl', 'heart', 'noun', 'filmi', 84],
  ['jaan', 'jan|jaann', 'जान', 'dʒaːn', 'life/darling', 'noun', 'filmi', 154],
  ['baat', 'bat|baath|baaat', 'बात', 'baːt̪', 'matter/talk', 'noun', '', 43],
  ['kaam', 'kam|kaamm', 'काम', 'kaːm', 'work', 'noun', 'corporate', 55],
  ['ghar', 'gharr', 'घर', 'gʰər', 'home', 'noun', '', 59],
  ['log', 'logg', 'लोग', 'loːg', 'people', 'noun', '', 71],
  ['aadmi', 'admi|aadmee', 'आदमी', 'aːd̪miː', 'man', 'noun', '', 202],
  ['bacha', 'baccha|bachcha', 'बच्चा', 'bətʃtʃaː', 'child', 'noun', '', 204],
  ['naam', 'nam|naamm', 'नाम', 'naːm', 'name', 'noun', '', 73],
  ['haath', 'hath|haathh', 'हाथ', 'ɦaːt̪ʰ', 'hand', 'noun', '', 109],
  ['aankh', 'ankh|aankhh', 'आँख', 'ãːkʰ', 'eye', 'noun', 'filmi', 131],
  ['sar', 'sarr', 'सर', 'sər', 'head', 'noun', '', 206],
  ['pair', 'pairr|per', 'पैर', 'pɛːr', 'foot', 'noun', '', 208],
  ['saans', 'sans|saans', 'साँस', 'sãːs', 'breath', 'noun', 'filmi', 212],
  ['khoon', 'khun|khoonn', 'ख़ून', 'xuːn', 'blood', 'noun', '', 214],
  ['jism', 'jismm', 'जिस्म', 'dʒɪsm', 'body', 'noun', 'filmi', 216],
  ['zindagi', 'zindagee|jindagi', 'ज़िंदगी', 'zɪnd̪əgiː', 'life', 'noun', 'filmi', 89],
  ['duniya', 'duniyaa|dunia', 'दुनिया', 'd̪ʊnɪjaː', 'world', 'noun', 'filmi', 87],
  ['sapna', 'sapnaa', 'सपना', 'səpnaː', 'dream', 'noun', 'filmi', 218],
  ['pyaar', 'pyar|pyaarr', 'प्यार', 'pjaːr', 'love', 'noun', 'filmi', 85],
  ['ishq', 'ishk|ishqq', 'इश्क़', 'ɪʃq', 'love (Urdu)', 'noun', 'filmi', 222],
  ['dard', 'dardd', 'दर्द', 'd̪ərd̪', 'pain', 'noun', 'filmi', 224],
  ['gham', 'ghamm', 'ग़म', 'ɣəm', 'sorrow', 'noun', 'filmi', 226],
  ['khushi', 'khushee', 'ख़ुशी', 'kʰʊʃiː', 'happiness', 'noun', '', 228],
  ['dost', 'dostt', 'दोस्त', 'd̪oːst̪', 'friend', 'noun', '', 117],
  ['dushman', 'dushmann', 'दुश्मन', 'd̪ʊʃmən', 'enemy', 'noun', '', 234],
  ['paisa', 'paisaa|pesa', 'पैसा', 'pɛːsaː', 'money', 'noun', 'corporate', 114],
  ['izzat', 'izzatt|ijjat', 'इज़्ज़त', 'ɪzzət̪', 'respect/honour', 'noun', '', 236],
  ['sach', 'such|sachh', 'सच', 'sətʃ', 'truth', 'noun', '', 123],
  ['jhooth', 'jhoot|jhuth', 'झूठ', 'dʒʰuːʈʰ', 'lie', 'noun', '', 238],
  ['dar', 'darr', 'डर', 'ɖər', 'fear', 'noun', '', 242],
  ['gussa', 'gussaa', 'ग़ुस्सा', 'gʊssaː', 'anger', 'noun', '', 244],
  ['himmat', 'himmatt', 'हिम्मत', 'ɦɪmmət̪', 'courage', 'noun', '', 246],
  ['taqat', 'taaqat|takat', 'ताक़त', 't̪aːqət̪', 'strength', 'noun', '', 248],
  ['raasta', 'rasta|raastaa', 'रास्ता', 'raːst̪aː', 'road/way', 'noun', '', 125],
  ['sadak', 'sarak|sadakk', 'सड़क', 'səɽək', 'street', 'noun', 'ncr', 252],
  ['shehar', 'shahar|sheher|sheherr', 'शहर', 'ʃəɦər', 'city', 'noun', 'ncr', 139],
  ['gaon', 'gaaon|gaav', 'गाँव', 'gãːʋ', 'village', 'noun', '', 254],
  ['desh', 'deshh', 'देश', 'd̪eːʃ', 'country', 'noun', '', 256],
  ['pani', 'paani', 'पानी', 'paːniː', 'water', 'noun', '', 161],
  ['aag', 'aagg', 'आग', 'aːg', 'fire', 'noun', '', 258],
  ['hawa', 'hava|hawaa', 'हवा', 'ɦəʋaː', 'wind/air', 'noun', 'filmi', 163],
  ['dhoop', 'dhup|dhoopp', 'धूप', 'd̪ʰuːp', 'sunlight', 'noun', '', 262],
  ['baarish', 'barish|baarishh', 'बारिश', 'baːrɪʃ', 'rain', 'noun', 'ncr', 264],
  ['aasman', 'asman|aasmaan', 'आसमान', 'aːsmaːn', 'sky', 'noun', 'filmi', 167],
  ['zameen', 'zamin|jameen', 'ज़मीन', 'zəmiːn', 'ground/land', 'noun', '', 169],
  ['chand', 'chaand', 'चाँद', 'tʃãːd̪', 'moon', 'noun', 'filmi', 266],
  ['suraj', 'sooraj', 'सूरज', 'suːrədʒ', 'sun', 'noun', '', 268],
  ['raah', 'rah|raahh', 'राह', 'raːɦ', 'path', 'noun', 'filmi', 270],
  ['manzil', 'manjil|manzill', 'मंज़िल', 'mənzɪl', 'destination', 'noun', 'filmi', 272],
  ['safar', 'safarr', 'सफ़र', 'səfər', 'journey', 'noun', 'filmi', 274],
  ['kismat', 'kismatt|qismat', 'क़िस्मत', 'qɪsmət̪', 'fate', 'noun', 'filmi', 276],
  ['nazar', 'nazarr|najar', 'नज़र', 'nəzər', 'gaze/sight', 'noun', 'filmi', 278],
  ['awaaz', 'awaz|aawaaz', 'आवाज़', 'aːʋaːz', 'voice/sound', 'noun', '', 280],
  ['shor', 'shorr', 'शोर', 'ʃoːr', 'noise', 'noun', '', 282],
  ['khel', 'khell', 'खेल', 'kʰeːl', 'game', 'noun', '', 284],
  ['jeet', 'jit|jeett', 'जीत', 'dʒiːt̪', 'victory', 'noun', '', 286],
  ['haar', 'har|haarr', 'हार', 'ɦaːr', 'defeat', 'noun', '', 288],
  ['bhar', 'bharr', 'भर', 'bʰər', 'full/fill', 'adv', '', 290],
  ['chehra', 'chehraa|chehara', 'चेहरा', 'tʃeːɦraː', 'face', 'noun', '', 292],
  ['yaad', 'yad|yaadd', 'याद', 'jaːd̪', 'memory', 'noun', 'filmi', 171],
  ['neend', 'nind|neendd', 'नींद', 'niːnd̪', 'sleep', 'noun', '', 294],
  ['bhookh', 'bhukh|bhook', 'भूख', 'bʰuːkʰ', 'hunger', 'noun', '', 296],
  ['sapne', 'sapney', 'सपने', 'səpneː', 'dreams', 'noun', 'filmi', 298],

  // ---- Adjectives ---------------------------------------------------------
  ['accha', 'acha|achha|achchha', 'अच्छा', 'ətʃtʃʰaː', 'good', 'adj', '', 69],
  ['bura', 'buraa', 'बुरा', 'bʊraː', 'bad', 'adj', '', 302],
  ['bada', 'bara|badaa', 'बड़ा', 'bəɽaː', 'big', 'adj', '', 81],
  ['chhota', 'chota|chhotaa', 'छोटा', 'tʃʰoːʈaː', 'small', 'adj', '', 304],
  ['naya', 'nayaa', 'नया', 'nəjaː', 'new', 'adj', '', 306],
  ['purana', 'puraana', 'पुराना', 'pʊraːnaː', 'old', 'adj', '', 308],
  ['sundar', 'sundarr', 'सुंदर', 'sʊnd̪ər', 'beautiful', 'adj', '', 310],
  ['pura', 'pooraa|poora', 'पूरा', 'puːraː', 'complete', 'adj', '', 312],
  ['adha', 'aadha|adhaa', 'आधा', 'aːd̪ʰaː', 'half', 'adj', '', 314],
  ['saara', 'sara|saaraa', 'सारा', 'saːraː', 'whole/all', 'adj', '', 316],
  ['sab', 'sabb', 'सब', 'səb', 'all/everyone', 'pron', '', 33],
  ['kuch', 'kuchh|kucch', 'कुछ', 'kʊtʃʰ', 'some/something', 'pron', '', 35],
  ['koi', 'koyi|koee', 'कोई', 'koːiː', 'someone/any', 'pron', '', 41],
  ['bahut', 'bohot|bahot|bhot', 'बहुत', 'bəɦʊt̪', 'very/a lot', 'adv', '', 49],
  ['thoda', 'thora|thodaa', 'थोड़ा', 't̪ʰoːɽaː', 'a little', 'adj', '', 318],
  ['zyada', 'jyada|zyaada', 'ज़्यादा', 'zjaːd̪aː', 'more/too much', 'adj', '', 83],
  ['kam', 'kamm', 'कम', 'kəm', 'less/few', 'adj', '', 322],
  ['tez', 'tezz|tej', 'तेज़', 't̪eːz', 'fast/sharp', 'adj', '', 324],
  ['dheere', 'dhire|dheerey', 'धीरे', 'd̪ʰiːreː', 'slowly', 'adv', '', 326],
  ['sacha', 'sachcha|sachha', 'सच्चा', 'sətʃtʃaː', 'true/honest', 'adj', '', 328],
  ['jhootha', 'jhutha|jhoothaa', 'झूठा', 'dʒʰuːʈʰaː', 'false/liar', 'adj', '', 330],
  ['garam', 'garamm|garm', 'गरम', 'gərəm', 'hot', 'adj', '', 332],
  ['thanda', 'thandaa', 'ठंडा', 'ʈʰənɖaː', 'cold', 'adj', '', 334],
  ['khaali', 'khali|khaalii', 'ख़ाली', 'xaːliː', 'empty', 'adj', '', 336],
  ['tuta', 'tootaa|toota', 'टूटा', 'ʈuːʈaː', 'broken', 'adj', '', 338],
  ['akela', 'akelaa', 'अकेला', 'əkeːlaː', 'alone', 'adj', 'filmi', 340],
  ['pagal', 'pagall', 'पागल', 'paːgəl', 'crazy', 'adj', 'slang', 342],
  ['zaruri', 'zaroori|jaruri', 'ज़रूरी', 'zəruːriː', 'necessary', 'adj', '', 344],
  ['mushkil', 'mushkill', 'मुश्किल', 'mʊʃkɪl', 'difficult', 'adj', '', 346],
  ['aasan', 'aasaan|asaan', 'आसान', 'aːsaːn', 'easy', 'adj', '', 348],
  ['gehra', 'gehraa|gahra', 'गहरा', 'gəɦraː', 'deep', 'adj', '', 350],
  ['saaf', 'saf|saaff', 'साफ़', 'saːf', 'clean/clear', 'adj', '', 352],
  ['ganda', 'gandaa', 'गंदा', 'gənd̪aː', 'dirty', 'adj', '', 354],
  ['sasta', 'sastaa', 'सस्ता', 'səst̪aː', 'cheap', 'adj', '', 356],
  ['mehnga', 'mehngaa|mahanga', 'महँगा', 'məɦə̃gaː', 'expensive', 'adj', 'ncr', 358],

  // ---- Numbers ------------------------------------------------------------
  ['ek', 'ekk|aik', 'एक', 'eːk', 'one', 'adj', '', 1],
  ['do', 'doo', 'दो', 'd̪oː', 'two', 'adj', '', 360],
  ['teen', 'tin|teenn', 'तीन', 't̪iːn', 'three', 'adj', '', 362],
  ['char', 'chaar', 'चार', 'tʃaːr', 'four', 'adj', '', 364],
  ['panch', 'paanch|panchh', 'पाँच', 'pãːtʃ', 'five', 'adj', '', 366],
  ['chhah', 'chhe|che', 'छह', 'tʃʰəɦ', 'six', 'adj', '', 368],
  ['saat', 'sat|saatt', 'सात', 'saːt̪', 'seven', 'adj', '', 370],
  ['aath', 'ath|aathh', 'आठ', 'aːʈʰ', 'eight', 'adj', '', 372],
  ['nau', 'no|nauu', 'नौ', 'nɔː', 'nine', 'adj', '', 374],
  ['das', 'dus|dass', 'दस', 'd̪əs', 'ten', 'adj', '', 376],
  ['sau', 'sauu', 'सौ', 'sɔː', 'hundred', 'adj', '', 378],
  ['hazaar', 'hazar|hajaar', 'हज़ार', 'ɦəzaːr', 'thousand', 'adj', '', 380],
  ['lakh', 'lakhh', 'लाख', 'laːkʰ', 'hundred thousand', 'adj', 'corporate', 382],
  ['crore', 'karod|karor', 'करोड़', 'kəroːɽ', 'ten million', 'adj', 'corporate', 384],

  // ---- Interjections and discourse markers --------------------------------
  ['arre', 'are|arey', 'अरे', 'əreː', 'hey!', 'interj', 'slang', 386],
  ['haan', 'han|haa|ha', 'हाँ', 'ɦãː', 'yes', 'interj', '', 64],
  ['acha', 'achha|accha', 'अच्छा', 'ətʃtʃʰaː', 'okay/I see', 'interj', 'slang', 388],
  ['chalo', 'chlo', 'चलो', 'tʃəloː', "let's go / fine", 'interj', 'slang', 390],
  ['dekho', 'dekhho', 'देखो', 'd̪eːkʰoː', 'look', 'interj', '', 392],
  ['suno', 'sunno', 'सुनो', 'sʊnoː', 'listen', 'interj', '', 394],
  ['bhai', 'bhaai|bhaiya', 'भाई', 'bʰaːiː', 'brother/bro', 'noun', 'slang', 120],
  ['behen', 'bahen|bhen', 'बहन', 'bəɦən', 'sister', 'noun', '', 396],
  ['maa', 'ma|maaa', 'माँ', 'mãː', 'mother', 'noun', '', 398],
  ['baap', 'bap|baapp', 'बाप', 'baːp', 'father', 'noun', '', 400],
  ['papa', 'papaa', 'पापा', 'paːpaː', 'dad', 'noun', '', 402],
  ['beta', 'betaa', 'बेटा', 'beːʈaː', 'son', 'noun', '', 404],
  ['beti', 'betii', 'बेटी', 'beːʈiː', 'daughter', 'noun', '', 406],

  // ---- Fixture-critical odds and ends ------------------------------------
  // Words the golden Hinglish bars depend on. Kept here (not in a later bank)
  // so language ID and G2P cannot silently regress when banks are trimmed.
  ['saari', 'sari|saarii', 'सारी', 'saːriː', 'all (f)', 'adj', '', 410],
  ['toot', 'tut|toott', 'टूट', 'ʈuːʈ', 'break (stem)', 'verb', '', 411],
  ['har', 'harr', 'हर', 'ɦər', 'every', 'adj', '', 412],
  ['bik', 'bikk', 'बिक', 'bɪk', 'sell (stem)', 'verb', '', 413],
  ['yahi', 'yahee|yehi', 'यही', 'jəɦiː', 'this very', 'pron', '', 414],
  ['wahi', 'vahee|wohi|vaahi', 'वही', 'ʋəɦiː', 'that very', 'pron', '', 415],
  ['tod', 'tor|todd', 'तोड़', 't̪oːɽ', 'break (stem)', 'verb', '', 416],
  ['rakh', 'rakhh', 'रख', 'rəkʰ', 'keep (stem)', 'verb', '', 417],
  ['bacha', 'bachaa|bacha', 'बचा', 'bətʃaː', 'saved/left (m)', 'verb', '', 418],
  ['daal', 'dal|daall', 'दाल', 'd̪aːl', 'lentil / put', 'noun', '', 419],
  ['andaaz', 'andaaz|andaz', 'अंदाज़', 'əndaːz', 'style/manner', 'noun', 'filmi', 420],
  ['naaraaz', 'naraz|naraaz|naaraaz', 'नाराज़', 'naːraːz', 'upset/angry', 'adj', '', 421],
  ['poora', 'pooraa', 'पूरा', 'puːraː', 'complete', 'adj', '', 422],
  ['likha', 'likhaa', 'लिखा', 'lɪkʰaː', 'wrote (m)', 'verb', '', 423],
  ['rukta', 'ruktaa', 'रुकता', 'rʊkt̪aː', 'stops (m)', 'verb', '', 425],
  ['chalta', 'chaltaa', 'चलता', 'tʃəlt̪aː', 'moves (m)', 'verb', '', 426],
  ['rehta', 'rahta|rehtaa', 'रहता', 'rəɦt̪aː', 'stays (m)', 'verb', '', 427],
  ['haara', 'hara|haaraa', 'हारा', 'ɦaːraː', 'lost (m)', 'verb', '', 428],
];
