// lib/lexicon/hi-modifiers.ts
//
// Modifiers and the words that hang off them: adjectives, adverbs, quantifiers,
// connectives, interjections, and the Urdu/ghazal noun register. Nothing here
// overlaps hi-core.ts — this bank is what a line *does* once hi-core has given
// it a subject and a verb.
//
// The Urdu/ghazal register is carried in full even though it is not everyday
// conversational Hindi, because that is where the densest rhyme families live:
// -aar (intezaar, bahaar, deedar), -aat (jazbaat, halaat, mulaqaat), -ai
// (tanhai, judai, rusvai), -at (hasrat, chaahat, ibaadat), -ana (afsana,
// zamana, deewana). A rhyme index built from conversational vocabulary alone
// finds two-member families; built from this register it finds twelve.
//
// Transcription conventions, held constant across every bank:
//   - Hindi /h/ is the voiced glottal ɦ (Appendix E lists ɦ as Hindi-specific).
//   - Dental t̪ d̪ for Hindi t/d; retroflex ʈ ɖ ɽ only where genuinely retroflex.
//   - Perso-Arabic q x ɣ are written where the word is genuinely Perso-Arabic:
//     qaatil = qaːt̪ɪl, khumaar = xʊmaːr, ghazal = ɣəzəl.
//   - Vowel length is contrastive and always marked: ə vs aː, ɪ vs iː, ʊ vs uː.
//   - Nasalization is a tilde on the vowel, never a separate coda: yahaṁ = jəɦãː.
//     A nasal that is a real consonant stays one: tanhai = t̪ənɦaːiː.
//   - Word-final inherent schwa is never written: vinamra = ʋɪnəmr.

import type { HiRow } from './hi-lexeme';

export const HI_MODIFIER_ROWS: HiRow[] = [
  // ---- Adverbs of place ---------------------------------------------------
  ['yahan', 'yaha|yahaan|yahan', 'यहाँ', 'jəɦãː', 'here', 'adv', '', 2200],
  ['wahan', 'vahan|wahaan|vahaan', 'वहाँ', 'ʋəɦãː', 'there', 'adv', '', 2201],
  ['jahan', 'jaha|jahaan', 'जहाँ', 'dʒəɦãː', 'where (relative)', 'adv', '', 2202],
  ['yahin', 'yahi|yaheen', 'यहीं', 'jəɦĩː', 'right here', 'adv', '', 2203],
  ['wahin', 'vahin|waheen|vaheen', 'वहीं', 'ʋəɦĩː', 'right there', 'adv', '', 2204],
  ['idhar', 'edhar|idharr', 'इधर', 'ɪd̪ʰər', 'over here / this way', 'adv', '', 2205],
  ['udhar', 'oodhar|udharr', 'उधर', 'ʊd̪ʰər', 'over there / that way', 'adv', '', 2206],
  ['kidhar', 'kidharr', 'किधर', 'kɪd̪ʰər', 'which way', 'adv', '', 2207],
  ['kahin', 'kahi|kaheen', 'कहीं', 'kəɦĩː', 'somewhere/anywhere', 'adv', '', 2208],
  ['saamne', 'samne|saamney', 'सामने', 'saːmneː', 'in front / facing', 'adv', '', 2209],
  ['nazdeek', 'nazdik|najdeek', 'नज़दीक', 'nəzd̪iːk', 'near/close', 'adv', '', 2210],
  ['door', 'dur|doorr', 'दूर', 'd̪uːr', 'far', 'adv', 'filmi', 2211],
  ['alag', 'allag|alagg', 'अलग', 'ələg', 'separate/different', 'adv', '', 2212],
  ['wapas', 'vapas|waapas|vaapas', 'वापस', 'ʋaːpəs', 'back/returned', 'adv', '', 2213],

  // ---- Adverbs of time, degree, and manner --------------------------------
  ['ekdum', 'ekdam|ekdumm', 'एकदम', 'eːkd̪əm', 'totally/at once', 'adv', 'slang', 2214],
  ['tabhi', 'tabhee', 'तभी', 't̪əbʰiː', 'only then / that is why', 'adv', '', 2215],
  ['jabhi', 'jabhee', 'जभी', 'dʒəbʰiː', 'right when', 'adv', '', 2216],
  ['shayad', 'shaayad|shayed', 'शायद', 'ʃaːjəd̪', 'maybe/perhaps', 'adv', '', 2217],
  ['zaroor', 'zarur|jaroor|zaroorr', 'ज़रूर', 'zəruːr', 'certainly', 'adv', '', 2218],
  ['sachmuch', 'sachmuchh|sachmuch', 'सचमुच', 'sətʃmʊtʃ', 'really/truly', 'adv', '', 2219],
  ['achanak', 'achaanak|achanakk', 'अचानक', 'ətʃaːnək', 'suddenly', 'adv', '', 2220],
  ['turant', 'turantt|turunt', 'तुरंत', 't̪ʊrənt̪', 'immediately', 'adv', '', 2221],
  ['fauran', 'phauran|fauren', 'फ़ौरन', 'fɔːrən', 'at once', 'adv', '', 2222],
  ['jhat', 'jhatt', 'झट', 'dʒʰəʈ', 'in a flash', 'adv', 'slang', 2223],
  ['jhatpat', 'jhatpatt', 'झटपट', 'dʒʰəʈpəʈ', 'quickly/snappily', 'adv', 'slang', 2224],
  ['lagatar', 'lagaatar|lagataar', 'लगातार', 'ləgaːt̪aːr', 'continuously', 'adv', '', 2225],
  ['baarbaar', 'barbar|baarbar', 'बारबार', 'baːrbaːr', 'again and again', 'adv', '', 2226],
  ['aksar', 'aksarr|axar', 'अक्सर', 'əksər', 'often', 'adv', '', 2227],
  ['dobara', 'dubara|dobaaraa', 'दोबारा', 'd̪oːbaːraː', 'again/a second time', 'adv', '', 2228],
  ['pehle', 'pahle|pehley', 'पहले', 'pəɦleː', 'earlier/first', 'adv', '', 2229],
  ['baad', 'bad|baadd', 'बाद', 'baːd̪', 'after/later', 'adv', '', 2230],
  ['filhal', 'filhaal|filhall', 'फ़िलहाल', 'fɪlɦaːl', 'for now', 'adv', '', 2231],
  ['aakhir', 'akhir|aakhirr', 'आख़िर', 'aːxɪr', 'after all / finally', 'adv', 'filmi', 2232],
  ['aakhirkar', 'akhirkar|aakhirkaar', 'आख़िरकार', 'aːxɪrkaːr', 'ultimately', 'adv', '', 2233],
  ['khaaskar', 'khaskar|khaaskarr', 'ख़ासकर', 'xaːskər', 'especially', 'adv', '', 2234],
  ['chupchaap', 'chupchap|chupchaapp', 'चुपचाप', 'tʃʊptʃaːp', 'quietly/silently', 'adv', '', 2235],
  ['chupke', 'chupkey|chhupke', 'चुपके', 'tʃʊpkeː', 'secretly/on the sly', 'adv', '', 2236],
  ['lagbhag', 'lagbagg|lagbhagg', 'लगभग', 'ləgbʰəg', 'approximately', 'adv', '', 2237],
  ['takreeban', 'taqreeban|takriban', 'तक़रीबन', 't̪əqriːbən', 'roughly/about', 'adv', '', 2238],
  ['zyadatar', 'jyadatar|zyaadatar', 'ज़्यादातर', 'zjaːd̪aːt̪ər', 'mostly', 'adv', '', 2239],
  ['kaafi', 'kafi|kaafee', 'काफ़ी', 'kaːfiː', 'quite/enough', 'adv', '', 2240],
  ['kewal', 'keval|kewall', 'केवल', 'keːʋəl', 'only/merely', 'adv', '', 2241],
  ['muft', 'mufft|mupht', 'मुफ़्त', 'mʊft̪', 'for free', 'adv', 'slang', 2242],
  ['behad', 'behadd|behud', 'बेहद', 'beːɦəd̪', 'extremely/boundless', 'adv', 'filmi', 2243],
  ['hargiz', 'hargij|hargizz', 'हरगिज़', 'ɦərgɪz', 'by no means', 'adv', 'filmi', 2244],
  ['yakeenan', 'yaqeenan|yakinan', 'यक़ीनन', 'jəqiːnən', 'assuredly', 'adv', 'filmi', 2245],
  ['yun', 'yoon|yu', 'यूँ', 'jũː', 'thus/like this', 'adv', 'filmi', 2246],
  ['aise', 'aisey|ese', 'ऐसे', 'ɛːseː', 'like this / in this way', 'adv', '', 2247],
  ['bekaar', 'bekar|bekaarr', 'बेकार', 'beːkaːr', 'useless/idle', 'adj', '', 2248],
  ['faltu', 'faaltu|phaltu', 'फ़ालतू', 'faːlt̪uː', 'pointless/spare', 'adj', 'slang', 2249],
  ['bematlab', 'bemtlab|bematlub', 'बेमतलब', 'beːmət̪ləb', 'pointless/for no reason', 'adv', 'slang', 2250],
  ['khamakha', 'khaamkha|khamakhaa', 'ख़ामख़ा', 'xaːməxaː', 'needlessly', 'adv', 'slang', 2251],
  ['zabardasti', 'jabardasti|zabardastee', 'ज़बरदस्ती', 'zəbərd̪əst̪iː', 'forcibly', 'adv', 'slang', 2252],
  ['sabhi', 'sabhee|sabhi', 'सभी', 'səbʰiː', 'all of them', 'adv', '', 2253],

  // ---- Quantifiers and determiners ---------------------------------------
  ['har', 'harr|her', 'हर', 'ɦər', 'every', 'adj', '', 2254],
  ['kai', 'kayi|kaee', 'कई', 'kəiː', 'several', 'adj', '', 2255],
  ['itna', 'itnaa|etna', 'इतना', 'ɪt̪naː', 'this much (m)', 'adj', '', 2256],
  ['utna', 'utnaa|ootna', 'उतना', 'ʊt̪naː', 'that much (m)', 'adj', '', 2257],
  ['jitna', 'jitnaa', 'जितना', 'dʒɪt̪naː', 'as much as (m)', 'adj', '', 2258],
  ['aisa', 'aisaa|esa', 'ऐसा', 'ɛːsaː', 'such/like this (m)', 'adj', '', 2259],
  ['waisa', 'vaisa|waisaa', 'वैसा', 'ʋɛːsaː', 'like that (m)', 'adj', '', 2260],
  ['jaisa', 'jaisaa|jesa', 'जैसा', 'dʒɛːsaː', 'like/as (m)', 'adj', '', 2261],
  ['dono', 'donon|dono', 'दोनों', 'd̪oːnõː', 'both', 'adj', '', 2262],
  ['pehla', 'pahla|pehlaa', 'पहला', 'pəɦlaː', 'first (m)', 'adj', '', 2263],
  ['doosra', 'dusra|doosraa', 'दूसरा', 'd̪uːsraː', 'second/other (m)', 'adj', '', 2264],
  ['teesra', 'tisra|teesraa', 'तीसरा', 't̪iːsraː', 'third (m)', 'adj', '', 2265],
  ['aakhri', 'akhri|aakhiri', 'आख़िरी', 'aːxɪriː', 'last/final', 'adj', '', 2266],
  ['agla', 'aglaa|uglaa', 'अगला', 'əglaː', 'next (m)', 'adj', '', 2267],
  ['pichla', 'pichhla|pichlaa', 'पिछला', 'pɪtʃʰlaː', 'previous (m)', 'adj', '', 2268],
  ['kul', 'kull|cool', 'कुल', 'kʊl', 'total', 'adj', 'corporate', 2269],
  ['adhik', 'adhikk|adhic', 'अधिक', 'əd̪ʰɪk', 'more/greater', 'adj', 'corporate', 2270],

  // ---- Connectives --------------------------------------------------------
  ['halaanki', 'halanki|haalaanki', 'हालाँकि', 'ɦaːlãːkɪ', 'although', 'conj', '', 2271],
  ['chunki', 'chunkey|choonki', 'चूँकि', 'tʃũːkɪ', 'since/because', 'conj', '', 2272],
  ['taki', 'taaki|takey', 'ताकि', 't̪aːkɪ', 'so that', 'conj', '', 2273],
  ['balki', 'balkey|balkee', 'बल्कि', 'bəlkɪ', 'rather/in fact', 'conj', '', 2274],
  ['yaani', 'yani|yaanee', 'यानी', 'jaːniː', 'that is / meaning', 'conj', '', 2275],
  ['jabki', 'jabkey|jabkee', 'जबकि', 'dʒəbkɪ', 'whereas/while', 'conj', '', 2276],
  ['kintu', 'kintoo|kintu', 'किंतु', 'kɪnt̪ʊ', 'but (formal)', 'conj', '', 2277],
  ['parantu', 'parantoo|prantu', 'परंतु', 'pərənt̪ʊ', 'however (formal)', 'conj', '', 2278],
  ['tatha', 'tathaa', 'तथा', 't̪ət̪ʰaː', 'and (formal)', 'conj', '', 2279],
  ['evam', 'evum|ewam', 'एवं', 'eːʋə̃', 'and (formal)', 'conj', '', 2280],
  ['athva', 'athvaa|athwa', 'अथवा', 'ət̪ʰəʋaː', 'or (formal)', 'conj', '', 2281],
  ['isliye', 'isliyay|isliey', 'इसलिये', 'ɪslɪjeː', 'therefore', 'conj', '', 2282],
  ['chahe', 'chaahe|chahey', 'चाहे', 'tʃaːɦeː', 'whether/even if', 'conj', '', 2283],

  // ---- Colours ------------------------------------------------------------
  ['laal', 'lal|laall', 'लाल', 'laːl', 'red', 'adj', '', 2284],
  ['neela', 'nila|neelaa', 'नीला', 'niːlaː', 'blue', 'adj', '', 2285],
  ['peela', 'pila|peelaa', 'पीला', 'piːlaː', 'yellow', 'adj', '', 2286],
  ['hara', 'haraa|hera', 'हरा', 'ɦəraː', 'green', 'adj', '', 2287],
  ['kaala', 'kala|kaalaa', 'काला', 'kaːlaː', 'black', 'adj', '', 2288],
  ['safed', 'safaid|sufed', 'सफ़ेद', 'səfeːd̪', 'white', 'adj', '', 2289],
  ['bhura', 'bhoora|bhuraa', 'भूरा', 'bʰuːraː', 'brown', 'adj', '', 2290],
  ['gulaabi', 'gulabi|gulaabee', 'गुलाबी', 'gʊlaːbiː', 'pink', 'adj', 'filmi', 2291],
  ['naarangi', 'narangi|naarangee', 'नारंगी', 'naːrəŋgiː', 'orange', 'adj', '', 2292],
  ['sunehra', 'sunahra|sunehraa', 'सुनहरा', 'sʊnəɦraː', 'golden', 'adj', 'filmi', 2293],
  ['rangeen', 'rangin|rangeenn', 'रंगीन', 'rəŋgiːn', 'colourful', 'adj', 'filmi', 2294],

  // ---- Size and shape -----------------------------------------------------
  ['lamba', 'lambaa|lumba', 'लंबा', 'ləmbaː', 'long/tall (m)', 'adj', '', 2295],
  ['mota', 'motaa|mottaa', 'मोटा', 'moːʈaː', 'fat/thick (m)', 'adj', '', 2296],
  ['patla', 'patlaa|puttla', 'पतला', 'pət̪laː', 'thin (m)', 'adj', '', 2297],
  ['dubla', 'dublaa|doobla', 'दुबला', 'd̪ʊblaː', 'skinny (m)', 'adj', '', 2298],
  ['gol', 'goll|gole', 'गोल', 'goːl', 'round', 'adj', '', 2299],
  ['chaukor', 'chokor|chaukorr', 'चौकोर', 'tʃɔːkoːr', 'square', 'adj', '', 2300],
  ['uncha', 'ooncha|unchaa', 'ऊँचा', 'ũːtʃaː', 'high/tall (m)', 'adj', '', 2301],
  ['neecha', 'nicha|neechaa', 'नीचा', 'niːtʃaː', 'low (m)', 'adj', '', 2302],
  ['chaura', 'chaudaa|chauraa', 'चौड़ा', 'tʃɔːɽaː', 'wide (m)', 'adj', '', 2303],
  ['tang', 'tangg|thang', 'तंग', 't̪əŋg', 'narrow/tight', 'adj', '', 2304],
  ['baarik', 'barik|baareek', 'बारीक', 'baːriːk', 'fine/minute', 'adj', '', 2305],
  ['vishaal', 'vishal|wishaal', 'विशाल', 'ʋɪʃaːl', 'vast/immense', 'adj', '', 2306],
  ['nanha', 'nanhaa|nannha', 'नन्हा', 'nənɦaː', 'tiny (m)', 'adj', 'filmi', 2307],

  // ---- Taste, texture, and quality ---------------------------------------
  ['meetha', 'mitha|meethaa', 'मीठा', 'miːʈʰaː', 'sweet (m)', 'adj', '', 2308],
  ['khatta', 'khata|khattaa', 'खट्टा', 'kʰəʈʈaː', 'sour (m)', 'adj', '', 2309],
  ['teekha', 'tikha|teekhaa', 'तीखा', 't̪iːkʰaː', 'spicy/sharp (m)', 'adj', '', 2310],
  ['namkeen', 'namkin|namkeenn', 'नमकीन', 'nəmkiːn', 'salty/savoury', 'adj', '', 2311],
  ['karwa', 'kadwa|karvaa', 'कड़वा', 'kəɽʋaː', 'bitter (m)', 'adj', '', 2312],
  ['naram', 'narm|narum', 'नरम', 'nərəm', 'soft', 'adj', '', 2313],
  ['sakht', 'sakhtt|sakht', 'सख़्त', 'səxt̪', 'hard/strict', 'adj', '', 2314],
  ['bhaari', 'bhari|bhaaree', 'भारी', 'bʰaːriː', 'heavy', 'adj', '', 2315],
  ['halka', 'halkaa|hulka', 'हल्का', 'ɦəlkaː', 'light (m)', 'adj', '', 2316],
  ['geela', 'gila|geelaa', 'गीला', 'giːlaː', 'wet (m)', 'adj', '', 2317],
  ['sookha', 'sukha|sookhaa', 'सूखा', 'suːkʰaː', 'dry (m)', 'adj', '', 2318],
  ['chikna', 'chiknaa|chickna', 'चिकना', 'tʃɪknaː', 'smooth/slippery (m)', 'adj', '', 2319],
  ['khurdura', 'khurduraa|khurdra', 'खुरदुरा', 'kʰʊrd̪ʊraː', 'rough (m)', 'adj', '', 2320],
  ['thos', 'thoss|those', 'ठोस', 'ʈʰoːs', 'solid/concrete', 'adj', 'corporate', 2321],
  ['taaza', 'taza|taaja', 'ताज़ा', 't̪aːzaː', 'fresh', 'adj', '', 2322],
  ['kaccha', 'kacha|kachcha', 'कच्चा', 'kətʃtʃaː', 'raw/unripe (m)', 'adj', '', 2323],
  ['pakka', 'paka|pakkaa', 'पक्का', 'pəkkaː', 'firm/ripe/certain (m)', 'adj', 'slang', 2324],
  ['mazboot', 'majboot|mazboott', 'मज़बूत', 'məzbuːt̪', 'strong/sturdy', 'adj', '', 2325],
  ['kamzor', 'kamjor|kamzorr', 'कमज़ोर', 'kəmzoːr', 'weak', 'adj', '', 2326],
  ['naazuk', 'nazuk|najuk', 'नाज़ुक', 'naːzʊk', 'delicate', 'adj', 'filmi', 2327],
  ['chamakdar', 'chamakdaar|chamkdar', 'चमकदार', 'tʃəməkd̪aːr', 'shiny', 'adj', '', 2328],
  ['roshan', 'roshann|raushan', 'रोशन', 'roːʃən', 'lit/luminous', 'adj', 'filmi', 2329],
  ['dhundhla', 'dhundla|dhundhlaa', 'धुंधला', 'd̪ʰʊnd̪ʰlaː', 'blurry/hazy (m)', 'adj', 'filmi', 2330],
  ['gaadha', 'gadha|gaadhaa', 'गाढ़ा', 'gaːɽʰaː', 'thick/dense (m)', 'adj', '', 2331],
  ['suhana', 'suhaana|suhanaa', 'सुहाना', 'sʊɦaːnaː', 'pleasant (m)', 'adj', 'filmi', 2332],
  ['khoobsurat', 'khubsurat|khoobsoorat', 'ख़ूबसूरत', 'xuːbsuːrət̪', 'beautiful', 'adj', 'filmi', 2333],
  ['nakli', 'naklee|nakhli', 'नकली', 'nəkliː', 'fake', 'adj', '', 2334],
  ['asli', 'aslee|asali', 'असली', 'əsliː', 'real/genuine', 'adj', '', 2335],
  ['anmol', 'anmoll|unmol', 'अनमोल', 'ənmoːl', 'priceless', 'adj', 'filmi', 2336],
  ['behtar', 'behtarr|behter', 'बेहतर', 'beːɦt̪ər', 'better', 'adj', 'corporate', 2337],
  ['lajawab', 'lajawaab|lajwab', 'लाजवाब', 'laːdʒʋaːb', 'peerless', 'adj', 'filmi', 2338],

  // ---- Character ----------------------------------------------------------
  ['bahadur', 'bahaadur|bahadurr', 'बहादुर', 'bəɦaːd̪ʊr', 'brave', 'adj', '', 2339],
  ['kaayar', 'kayar|kaayarr', 'कायर', 'kaːjər', 'cowardly', 'adj', '', 2340],
  ['imaandaar', 'imandar|imaandar', 'ईमानदार', 'iːmaːnd̪aːr', 'honest', 'adj', '', 2341],
  ['beimaan', 'beiman|bayimaan', 'बेईमान', 'beːiːmaːn', 'dishonest', 'adj', '', 2342],
  ['chalaak', 'chalak|chaalaak', 'चालाक', 'tʃaːlaːk', 'clever/sly', 'adj', '', 2343],
  ['seedha', 'sidha|seedhaa', 'सीधा', 'siːd̪ʰaː', 'straight/straightforward (m)', 'adj', '', 2344],
  ['ghamandi', 'ghamandee|ghamndi', 'घमंडी', 'gʰəmənɖiː', 'arrogant', 'adj', '', 2345],
  ['vinamra', 'winamra|vinamr', 'विनम्र', 'ʋɪnəmr', 'humble', 'adj', 'corporate', 2346],
  ['ziddi', 'jiddi|ziddee', 'ज़िद्दी', 'zɪdd̪iː', 'stubborn', 'adj', '', 2347],
  ['aalsi', 'alsi|aalsee', 'आलसी', 'aːlsiː', 'lazy', 'adj', '', 2348],
  ['mehnati', 'mehanti|mehnatee', 'मेहनती', 'meːɦnət̪iː', 'hardworking', 'adj', 'corporate', 2349],
  ['shareef', 'sharif|shareeff', 'शरीफ़', 'ʃəriːf', 'decent/gentle', 'adj', '', 2350],
  ['badmash', 'badmaash|badmash', 'बदमाश', 'bəd̪maːʃ', 'rascally', 'adj', 'slang', 2351],
  ['kameena', 'kamina|kameenaa', 'कमीना', 'kəmiːnaː', 'mean/lowly (m)', 'adj', 'slang', 2352],
  ['sharmila', 'sharmilaa|sharmeela', 'शर्मीला', 'ʃərmiːlaː', 'shy (m)', 'adj', '', 2353],
  ['gareeb', 'garib|ghareeb', 'ग़रीब', 'ɣəriːb', 'poor', 'adj', '', 2354],
  ['ameer', 'amir|ameerr', 'अमीर', 'əmiːr', 'rich', 'adj', '', 2355],
  ['nek', 'nekk|naik', 'नेक', 'neːk', 'virtuous', 'adj', 'filmi', 2356],
  ['zaalim', 'zalim|jaalim', 'ज़ालिम', 'zaːlɪm', 'cruel/tyrannical', 'adj', 'filmi', 2357],
  ['bewakoof', 'bevkoof|bewaqoof', 'बेवक़ूफ़', 'beːʋəquːf', 'foolish', 'adj', 'slang', 2358],
  ['samajhdaar', 'samajhdar|samajdaar', 'समझदार', 'səmədʒʰd̪aːr', 'sensible', 'adj', '', 2359],
  ['nadaan', 'nadan|naadaan', 'नादान', 'naːd̪aːn', 'naive', 'adj', 'filmi', 2360],
  ['masoom', 'masum|masoomm', 'मासूम', 'maːsuːm', 'innocent', 'adj', 'filmi', 2361],
  ['sharabi', 'sharaabi|sharabee', 'शराबी', 'ʃəraːbiː', 'drunken', 'adj', 'filmi', 2362],
  ['wafadar', 'vafadar|wafaadaar', 'वफ़ादार', 'ʋəfaːd̪aːr', 'loyal', 'adj', 'filmi', 2363],

  // ---- States and conditions ---------------------------------------------
  ['thaka', 'thakaa|thakka', 'थका', 't̪ʰəkaː', 'tired (m)', 'adj', '', 2364],
  ['pareshan', 'preshan|pareshaan', 'परेशान', 'pəreːʃaːn', 'troubled/worried', 'adj', '', 2365],
  ['khush', 'khushh|khus', 'ख़ुश', 'xʊʃ', 'happy', 'adj', '', 2366],
  ['dukhi', 'dukhee|dukhi', 'दुखी', 'd̪ʊkʰiː', 'sad', 'adj', '', 2367],
  ['naaraaz', 'naraz|naaraaj', 'नाराज़', 'naːraːz', 'displeased', 'adj', '', 2368],
  ['bezaar', 'bezar|bejaar', 'बेज़ार', 'beːzaːr', 'fed up', 'adj', 'filmi', 2369],
  ['bechain', 'bechen|bechainn', 'बेचैन', 'beːtʃɛːn', 'restless', 'adj', 'filmi', 2370],
  ['shaant', 'shant|shaantt', 'शांत', 'ʃaːnt̪', 'calm', 'adj', '', 2371],
  ['tanha', 'tanhaa|tanha', 'तन्हा', 't̪ənɦaː', 'lonely', 'adj', 'filmi', 2372],
  ['majboor', 'majbur|mazboor', 'मजबूर', 'mədʒbuːr', 'helpless/compelled', 'adj', 'filmi', 2373],
  ['azaad', 'azad|aazaad', 'आज़ाद', 'aːzaːd̪', 'free', 'adj', '', 2374],
  ['zinda', 'jinda|zindaa', 'ज़िंदा', 'zɪnd̪aː', 'alive', 'adj', 'filmi', 2375],
  ['murda', 'murdaa|moorda', 'मुर्दा', 'mʊrd̪aː', 'dead', 'adj', '', 2376],
  ['bhookha', 'bhukha|bhookhaa', 'भूखा', 'bʰuːkʰaː', 'hungry (m)', 'adj', '', 2377],
  ['pyaasa', 'pyasa|pyaasaa', 'प्यासा', 'pjaːsaː', 'thirsty (m)', 'adj', 'filmi', 2378],
  ['jaaga', 'jagaa|jaagaa', 'जागा', 'dʒaːgaː', 'awake/woken (m)', 'adj', '', 2379],
  ['beemar', 'bimar|beemaar', 'बीमार', 'biːmaːr', 'ill', 'adj', '', 2380],
  ['tandurust', 'tandrust|tandurustt', 'तंदुरुस्त', 't̪ənd̪ʊrʊst̪', 'healthy', 'adj', '', 2381],
  ['udaas', 'udas|oodaas', 'उदास', 'ʊd̪aːs', 'melancholy', 'adj', 'filmi', 2382],
  ['ghayal', 'ghaayal|ghayall', 'घायल', 'gʰaːjəl', 'wounded', 'adj', 'filmi', 2383],
  ['zakhmi', 'jakhmi|zakhmee', 'ज़ख़्मी', 'zəxmiː', 'injured', 'adj', 'filmi', 2384],
  ['nakaam', 'nakam|naakaam', 'नाकाम', 'naːkaːm', 'unsuccessful', 'adj', 'filmi', 2385],
  ['kaamyaab', 'kamyab|kaamyab', 'कामयाब', 'kaːmjaːb', 'successful', 'adj', 'corporate', 2386],
  ['tayyar', 'taiyar|tayyaar', 'तैयार', 't̪ɛːjaːr', 'ready', 'adj', '', 2387],
  ['hairan', 'hairaan|heran', 'हैरान', 'ɦɛːraːn', 'astonished', 'adj', '', 2388],
  ['vyast', 'vyastt|wyast', 'व्यस्त', 'ʋjəst̪', 'busy', 'adj', 'corporate', 2389],
  ['khoya', 'khoyaa|khoia', 'खोया', 'kʰoːjaː', 'lost (m)', 'adj', 'filmi', 2390],
  ['gumraah', 'gumrah|gumraahh', 'गुमराह', 'gʊmraːɦ', 'led astray', 'adj', 'filmi', 2391],
  ['barbaad', 'barbad|barbaadd', 'बरबाद', 'bərbaːd̪', 'ruined', 'adj', 'filmi', 2392],
  ['bedard', 'bedardd|bedarad', 'बेदर्द', 'beːd̪ərd̪', 'heartless', 'adj', 'filmi', 2393],

  // ---- Urdu register: the -aar family ------------------------------------
  ['intezaar', 'intzar|intezar', 'इंतज़ार', 'ɪnt̪əzaːr', 'waiting', 'noun', 'filmi', 2394],
  ['ikraar', 'iqraar|ikrar', 'इक़रार', 'ɪqraːr', 'avowal/confession', 'noun', 'filmi', 2395],
  ['inkaar', 'inkar|inkaarr', 'इनकार', 'ɪnkaːr', 'refusal', 'noun', 'filmi', 2396],
  ['deedar', 'didar|deedaar', 'दीदार', 'd̪iːd̪aːr', 'glimpse of the beloved', 'noun', 'filmi', 2397],
  ['bahaar', 'bahar|bahaarr', 'बहार', 'bəɦaːr', 'spring/bloom', 'noun', 'filmi', 2398],
  ['khumaar', 'khumar|khumaarr', 'ख़ुमार', 'xʊmaːr', 'intoxication/languor', 'noun', 'filmi', 2399],
  ['guzaar', 'guzar|gujaar', 'गुज़ार', 'gʊzaːr', 'spending/passing (of time)', 'noun', 'filmi', 2400],

  // ---- Urdu register: the -am family -------------------------------------
  ['sitam', 'sitamm|situm', 'सितम', 'sɪt̪əm', 'cruelty', 'noun', 'filmi', 2401],
  ['karam', 'karamm|krum', 'करम', 'kərəm', 'grace/kindness', 'noun', 'filmi', 2402],
  ['alam', 'aalam|alamm', 'आलम', 'aːləm', 'world/condition', 'noun', 'filmi', 2403],
  ['sanam', 'sanamm|sanum', 'सनम', 'sənəm', 'beloved/idol', 'noun', 'filmi', 2404],
  ['mausam', 'mosam|mausamm', 'मौसम', 'mɔːsəm', 'weather/season', 'noun', 'filmi', 2405],
  ['shabnam', 'shabnamm|shabnum', 'शबनम', 'ʃəbnəm', 'dew', 'noun', 'filmi', 2406],
  ['humdum', 'hamdam|humdumm', 'हमदम', 'ɦəmd̪əm', 'close companion', 'noun', 'filmi', 2407],

  // ---- Urdu register: the -il family -------------------------------------
  ['mehfil', 'mehfill|mahfil', 'महफ़िल', 'məɦfɪl', 'gathering/soiree', 'noun', 'filmi', 2408],
  ['qaatil', 'katil|qatil', 'क़ातिल', 'qaːt̪ɪl', 'killer', 'noun', 'filmi', 2409],
  ['saahil', 'sahil|saahill', 'साहिल', 'saːɦɪl', 'shore', 'noun', 'filmi', 2410],
  ['bismil', 'bismill|bismil', 'बिस्मिल', 'bɪsmɪl', 'wounded one', 'noun', 'filmi', 2411],

  // ---- Urdu register: the -ar and -andar family -------------------------
  ['manzar', 'manjar|manzarr', 'मंज़र', 'mənzər', 'scene/vista', 'noun', 'filmi', 2412],
  ['samandar', 'samundar|samandarr', 'समंदर', 'səmənd̪ər', 'sea', 'noun', 'filmi', 2413],
  ['patthar', 'pathar|paththar', 'पत्थर', 'pət̪t̪ʰər', 'stone', 'noun', 'filmi', 2414],
  ['muqaddar', 'mukaddar|muqaddarr', 'मुक़द्दर', 'mʊqədd̪ər', 'destiny', 'noun', 'filmi', 2415],
  ['sikandar', 'sikander|sikandarr', 'सिकंदर', 'sɪkənd̪ər', 'conqueror/Alexander', 'noun', 'filmi', 2416],
  ['qadar', 'kadar|qadarr', 'क़दर', 'qəd̪ər', 'worth/esteem', 'noun', 'filmi', 2417],
  ['asar', 'asarr|aser', 'असर', 'əsər', 'effect', 'noun', 'filmi', 2418],

  // ---- Urdu register: the -era family -----------------------------------
  ['andhera', 'andheraa|andhera', 'अँधेरा', 'ə̃d̪ʰeːraː', 'darkness', 'noun', 'filmi', 2419],
  ['savera', 'saveraa|sawera', 'सवेरा', 'səʋeːraː', 'dawn', 'noun', 'filmi', 2420],
  ['basera', 'baseraa|basera', 'बसेरा', 'bəseːraː', 'roost/dwelling', 'noun', 'filmi', 2421],
  ['sehra', 'sehraa|sehara', 'सेहरा', 'seːɦraː', "bridegroom's veil", 'noun', 'filmi', 2422],

  // ---- Urdu register: the -ai family ------------------------------------
  ['tanhai', 'tanhaai|tanhayi', 'तन्हाई', 't̪ənɦaːiː', 'loneliness', 'noun', 'filmi', 2423],
  ['rusvai', 'rusvaai|ruswai', 'रुसवाई', 'rʊsʋaːiː', 'disgrace', 'noun', 'filmi', 2424],
  ['judai', 'judaai|judayi', 'जुदाई', 'dʒʊd̪aːiː', 'separation', 'noun', 'filmi', 2425],
  ['sunai', 'sunaai|sunayi', 'सुनाई', 'sʊnaːiː', 'audibility', 'noun', '', 2426],
  ['dikhai', 'dikhaai|dikhayi', 'दिखाई', 'd̪ɪkʰaːiː', 'visibility', 'noun', '', 2427],
  ['kamai', 'kamaai|kamayi', 'कमाई', 'kəmaːiː', 'earnings', 'noun', 'corporate', 2428],

  // ---- Urdu register: open-vowel finals ---------------------------------
  ['bewafa', 'bevafa|bewafaa', 'बेवफ़ा', 'beːʋəfaː', 'unfaithful', 'adj', 'filmi', 2429],
  ['wafa', 'vafa|wafaa', 'वफ़ा', 'ʋəfaː', 'fidelity', 'noun', 'filmi', 2430],
  ['dafa', 'dafaa|dufa', 'दफ़ा', 'd̪əfaː', 'occasion/time', 'noun', '', 2431],
  ['khata', 'khataa|khta', 'ख़ता', 'xət̪aː', 'fault/error', 'noun', 'filmi', 2432],
  ['adaa', 'ada|adaaa', 'अदा', 'əd̪aː', 'grace/gesture', 'noun', 'filmi', 2433],
  ['sada', 'sadaa|sda', 'सदा', 'səd̪aː', 'always/ever', 'adv', 'filmi', 2434],
  ['fanaa', 'fana|phana', 'फ़ना', 'fənaː', 'annihilation', 'noun', 'filmi', 2435],
  ['nasha', 'nashaa|nesha', 'नशा', 'nəʃaː', 'intoxication', 'noun', 'filmi', 2436],
  ['jalwa', 'jalvaa|jalwaa', 'जलवा', 'dʒəlʋaː', 'splendour/display', 'noun', 'filmi', 2437],
  ['parda', 'pardaa|purda', 'पर्दा', 'pərd̪aː', 'veil/curtain', 'noun', 'filmi', 2438],
  ['rishta', 'rishtaa|rista', 'रिश्ता', 'rɪʃt̪aː', 'relationship', 'noun', '', 2439],
  ['nagma', 'nagmaa|nagama', 'नग़्मा', 'nəɣmaː', 'song/melody', 'noun', 'filmi', 2440],
  ['saaya', 'saya|saayaa', 'साया', 'saːjaː', 'shadow/shade', 'noun', 'filmi', 2441],

  // ---- Urdu register: the -ana family ----------------------------------
  ['tarana', 'taraana|taranaa', 'तराना', 't̪əraːnaː', 'anthem/tune', 'noun', 'filmi', 2442],
  ['afsana', 'afsaana|afsanaa', 'अफ़साना', 'əfsaːnaː', 'tale', 'noun', 'filmi', 2443],
  ['zamana', 'zamaana|jamana', 'ज़माना', 'zəmaːnaː', 'era/the world', 'noun', 'filmi', 2444],
  ['deewana', 'diwana|deewanaa', 'दीवाना', 'd̪iːʋaːnaː', 'madly in love', 'adj', 'filmi', 2445],
  ['parwana', 'parvana|parwanaa', 'परवाना', 'pərʋaːnaː', 'moth/lover', 'noun', 'filmi', 2446],
  ['begana', 'begaana|beganaa', 'बेगाना', 'beːgaːnaː', 'stranger/alien', 'noun', 'filmi', 2447],
  ['yaarana', 'yaaraana|yarana', 'याराना', 'jaːraːnaː', 'camaraderie', 'noun', 'filmi', 2448],
  ['nishana', 'nishaana|nishanaa', 'निशाना', 'nɪʃaːnaː', 'target/aim', 'noun', '', 2449],
  ['khazana', 'khazaana|khajana', 'ख़ज़ाना', 'xəzaːnaː', 'treasure', 'noun', 'filmi', 2450],
  ['bahana', 'bahaana|bahanaa', 'बहाना', 'bəɦaːnaː', 'excuse/pretext', 'noun', '', 2451],

  // ---- Urdu register: the -aaz family ----------------------------------
  ['riwaaj', 'rivaj|riwaj', 'रिवाज', 'rɪʋaːdʒ', 'custom', 'noun', 'filmi', 2452],
  ['andaaz', 'andaz|andaaj', 'अंदाज़', 'ənd̪aːz', 'manner/style', 'noun', 'filmi', 2453],
  ['alfaaz', 'alfaz|alfaaj', 'अल्फ़ाज़', 'əlfaːz', 'words', 'noun', 'filmi', 2454],
  ['raaz', 'raz|raaj', 'राज़', 'raːz', 'secret', 'noun', 'filmi', 2455],
  ['aaghaz', 'aghaz|aaghaaz', 'आग़ाज़', 'aːɣaːz', 'beginning', 'noun', 'filmi', 2456],

  // ---- Urdu register: the -aam family ----------------------------------
  ['anjaam', 'anjam|anjaamm', 'अंजाम', 'əndʒaːm', 'outcome', 'noun', 'filmi', 2457],
  ['ilzaam', 'ilzam|iljaam', 'इल्ज़ाम', 'ɪlzaːm', 'accusation', 'noun', 'filmi', 2458],
  ['salaam', 'salam|salaamm', 'सलाम', 'səlaːm', 'salutation', 'noun', 'filmi', 2459],
  ['paigaam', 'paigam|paighaam', 'पैग़ाम', 'pɛːɣaːm', 'message', 'noun', 'filmi', 2460],
  ['aaraam', 'aram|aaraamm', 'आराम', 'aːraːm', 'rest/comfort', 'noun', '', 2461],
  ['kalaam', 'kalam|kalaamm', 'कलाम', 'kəlaːm', 'discourse/verse', 'noun', 'filmi', 2462],

  // ---- Urdu register: the -aat family ---------------------------------
  ['jazbaat', 'jazbat|jajbaat', 'जज़्बात', 'dʒəzbaːt̪', 'emotions', 'noun', 'filmi', 2463],
  ['halaat', 'halat|haalaat', 'हालात', 'ɦaːlaːt̪', 'circumstances', 'noun', 'filmi', 2464],
  ['mulaqaat', 'mulakat|mulaaqaat', 'मुलाक़ात', 'mʊlaːqaːt̪', 'meeting/encounter', 'noun', 'filmi', 2465],

  // ---- Urdu register: the -aab and -aal family ------------------------
  ['sawaal', 'saval|sawal', 'सवाल', 'səʋaːl', 'question', 'noun', '', 2466],
  ['jawaab', 'javab|jawab', 'जवाब', 'dʒəʋaːb', 'answer', 'noun', '', 2467],
  ['khwaab', 'khwab|khaab', 'ख़्वाब', 'xʋaːb', 'dream', 'noun', 'filmi', 2468],
  ['hisaab', 'hisab|hisaabb', 'हिसाब', 'ɦɪsaːb', 'account/reckoning', 'noun', 'corporate', 2469],
  ['azaab', 'azab|ajaab', 'अज़ाब', 'əzaːb', 'torment', 'noun', 'filmi', 2470],
  ['shabaab', 'shabab|shabaabb', 'शबाब', 'ʃəbaːb', 'youth/bloom', 'noun', 'filmi', 2471],
  ['sharaab', 'sharab|sharaabb', 'शराब', 'ʃəraːb', 'wine/liquor', 'noun', 'filmi', 2472],
  ['kitaab', 'kitab|kitaabb', 'किताब', 'kɪt̪aːb', 'book', 'noun', '', 2473],
  ['aftaab', 'aftab|aaftaab', 'आफ़ताब', 'aːft̪aːb', 'the sun', 'noun', 'filmi', 2474],
  ['mehtaab', 'mahtab|mehtab', 'महताब', 'məɦt̪aːb', 'the moon', 'noun', 'filmi', 2475],
  ['gulaab', 'gulab|gulaabb', 'गुलाब', 'gʊlaːb', 'rose', 'noun', 'filmi', 2476],
  ['naqaab', 'nakab|naqab', 'नक़ाब', 'nəqaːb', 'mask/veil', 'noun', 'filmi', 2477],

  // ---- Urdu register: the -aq and -oon family -------------------------
  ['ittefaq', 'ittefak|ittifaq', 'इत्तेफ़ाक़', 'ɪtt̪eːfaːq', 'coincidence', 'noun', 'filmi', 2478],
  ['firaq', 'firak|firaaq', 'फ़िराक़', 'fɪraːq', 'separation/pining', 'noun', 'filmi', 2479],
  ['junoon', 'junun|junoonn', 'जुनून', 'dʒʊnuːn', 'passion/frenzy', 'noun', 'filmi', 2480],
  ['sukoon', 'sukun|sukoonn', 'सुकून', 'sʊkuːn', 'peace/calm', 'noun', 'filmi', 2481],

  // ---- Urdu register: the -at abstractions ---------------------------
  ['hasrat', 'hasratt|hasrut', 'हसरत', 'ɦəsrət̪', 'longing', 'noun', 'filmi', 2482],
  ['shohrat', 'shohratt|shauhrat', 'शोहरत', 'ʃoːɦrət̪', 'fame', 'noun', 'filmi', 2483],
  ['daulat', 'daulatt|dolat', 'दौलत', 'd̪ɔːlət̪', 'wealth', 'noun', 'filmi', 2484],
  ['ulfat', 'ulfatt|ulfut', 'उल्फ़त', 'ʊlfət̪', 'affection', 'noun', 'filmi', 2485],
  ['mohabbat', 'muhabbat|mohobbat', 'मोहब्बत', 'moːɦəbbət̪', 'love', 'noun', 'filmi', 2486],
  ['nafrat', 'nafratt|nafrut', 'नफ़रत', 'nəfrət̪', 'hatred', 'noun', 'filmi', 2487],
  ['hairat', 'hairatt|heirat', 'हैरत', 'ɦɛːrət̪', 'astonishment', 'noun', 'filmi', 2488],
  ['raahat', 'rahat|raahatt', 'राहत', 'raːɦət̪', 'relief', 'noun', 'filmi', 2489],
  ['chaahat', 'chahat|chaahatt', 'चाहत', 'tʃaːɦət̪', 'desire/longing', 'noun', 'filmi', 2490],
  ['ibaadat', 'ibadat|ibaadatt', 'इबादत', 'ɪbaːd̪ət̪', 'worship', 'noun', 'filmi', 2491],
  ['shiddat', 'shiddatt|shidat', 'शिद्दत', 'ʃɪdd̪ət̪', 'intensity', 'noun', 'filmi', 2492],
  ['zaroorat', 'zarurat|jaroorat', 'ज़रूरत', 'zəruːrət̪', 'need', 'noun', '', 2493],
  ['aadat', 'adat|aadatt', 'आदत', 'aːd̪ət̪', 'habit', 'noun', '', 2494],
  ['shararat', 'shararatt|sharaarat', 'शरारत', 'ʃəraːrət̪', 'mischief', 'noun', 'filmi', 2495],
  ['wahshat', 'vahshat|wahshatt', 'वहशत', 'ʋəɦʃət̪', 'frenzy/dread', 'noun', 'filmi', 2496],

  // ---- Urdu register: consonant-final monosyllables ------------------
  ['zikr', 'jikr|zikar', 'ज़िक्र', 'zɪkr', 'mention', 'noun', 'filmi', 2497],
  ['fikr', 'fikar|phikr', 'फ़िक्र', 'fɪkr', 'worry', 'noun', 'filmi', 2498],
  ['shukr', 'shukar|shukrr', 'शुक्र', 'ʃʊkr', 'gratitude', 'noun', 'filmi', 2499],
  ['sabr', 'sabar|sabrr', 'सब्र', 'səbr', 'patience', 'noun', 'filmi', 2500],
  ['hijr', 'hijar|hijrr', 'हिज्र', 'ɦɪdʒr', 'separation', 'noun', 'filmi', 2501],
  ['wasl', 'vasl|wasal', 'वस्ल', 'ʋəsl', 'union', 'noun', 'filmi', 2502],
  ['nazm', 'nazam|najm', 'नज़्म', 'nəzm', 'poem', 'noun', 'filmi', 2503],
  ['talab', 'talabb|talub', 'तलब', 't̪ələb', 'craving/summons', 'noun', 'filmi', 2504],
  ['sher', 'sherr|shair', 'शेर', 'ʃeːr', 'couplet/lion', 'noun', 'filmi', 2505],
  ['ghazal', 'gazal|ghazall', 'ग़ज़ल', 'ɣəzəl', 'ghazal', 'noun', 'filmi', 2506],
  ['noor', 'nur|noorr', 'नूर', 'nuːr', 'radiance', 'noun', 'filmi', 2507],
  ['qaid', 'kaid|qaidd', 'क़ैद', 'qɛːd̪', 'captivity', 'noun', 'filmi', 2508],

  // ---- Urdu register: the -eer family --------------------------------
  ['takdeer', 'taqdeer|takdir', 'तक़दीर', 't̪əqd̪iːr', 'destiny', 'noun', 'filmi', 2509],
  ['tasveer', 'tasvir|tasweer', 'तस्वीर', 't̪əsʋiːr', 'picture', 'noun', 'filmi', 2510],
  ['zameer', 'zamir|jameer', 'ज़मीर', 'zəmiːr', 'conscience', 'noun', 'filmi', 2511],
  ['faqeer', 'fakir|faqir', 'फ़क़ीर', 'fəqiːr', 'mendicant', 'noun', 'filmi', 2512],

  // ---- Interjections and discourse markers --------------------------
  ['abey', 'abe|abey', 'अबे', 'əbeː', 'hey you!', 'interj', 'slang', 2513],
  ['oye', 'oy|oye', 'ओए', 'oːjeː', 'oi!', 'interj', 'slang', 2514],
  ['bhaisaab', 'bhaisab|bhaisaabb', 'भाईसाब', 'bʰaːiːsaːb', 'good grief / mate', 'interj', 'slang', 2515],
  ['waah', 'wah|vaah', 'वाह', 'ʋaːɦ', 'wow!', 'interj', 'filmi', 2516],
  ['haaye', 'haay|haaay', 'हाय', 'ɦaːj', 'alas!', 'interj', 'filmi', 2517],
  ['uff', 'uf|uffff', 'उफ़्फ़', 'ʊf', 'ugh!', 'interj', 'slang', 2518],
  ['chhi', 'chi|chhee', 'छी', 'tʃʰiː', 'yuck!', 'interj', 'slang', 2519],
  ['hatt', 'hat|hutt', 'हट', 'ɦəʈ', 'get lost!', 'interj', 'slang', 2520],
  ['oho', 'ohoo|oho', 'ओहो', 'oːɦoː', 'oho!', 'interj', 'slang', 2521],
  ['dhat', 'dhatt|dhut', 'धत्', 'd̪ʰət̪', 'tsk / get away', 'interj', 'slang', 2522],
  ['toba', 'taubaa|tauba', 'तौबा', 't̪ɔːbaː', 'heaven forbid!', 'interj', 'filmi', 2523],
  ['khair', 'khairr|kher', 'ख़ैर', 'xɛːr', 'anyway / well then', 'interj', 'filmi', 2524],
  ['kaash', 'kash|kaashh', 'काश', 'kaːʃ', 'if only!', 'interj', 'filmi', 2525],
  ['shabaash', 'shabash|shaabaash', 'शाबाश', 'ʃaːbaːʃ', 'well done!', 'interj', '', 2526],
  ['lo', 'loo|lo', 'लो', 'loː', 'here, take it', 'interj', 'slang', 2527],
  ['chhodo', 'chodo|chhoro', 'छोड़ो', 'tʃʰoːɽoː', 'forget it', 'interj', 'slang', 2528],
  ['bhaag', 'bhag|bhaagg', 'भाग', 'bʰaːg', 'scram!', 'interj', 'slang', 2529],
  ['dhanyavaad', 'dhanyavad|dhanyawaad', 'धन्यवाद', 'd̪ʰənjəʋaːd̪', 'thank you', 'interj', '', 2530],
  ['shukriya', 'shukriyaa|shukria', 'शुक्रिया', 'ʃʊkrɪjaː', 'thanks', 'interj', 'filmi', 2531],

  // ---- Hinglish slang: judgements -----------------------------------
  ['maaf', 'maf|maaff', 'माफ़', 'maːf', 'forgiven/excused', 'adj', '', 2532],
  ['theek', 'thik|theekk', 'ठीक', 'ʈʰiːk', 'fine/correct', 'adj', '', 2533],
  ['sahi', 'sahee|shi', 'सही', 'səɦiː', 'right/correct', 'adj', 'slang', 2534],
  ['galat', 'ghalat|galatt', 'ग़लत', 'ɣələt̪', 'wrong', 'adj', '', 2535],
  ['khaas', 'khas|khaass', 'ख़ास', 'xaːs', 'special', 'adj', '', 2536],
  ['aam', 'amm|aamm', 'आम', 'aːm', 'ordinary/common', 'adj', '', 2537],
  ['mast', 'mastt|must', 'मस्त', 'məst̪', 'awesome/blissed out', 'adj', 'slang', 2538],
  ['jhakaas', 'jhakas|jhakaass', 'झकास', 'dʒʰəkaːs', 'fantastic', 'adj', 'slang', 2539],
  ['bindaas', 'bindas|bindaass', 'बिंदास', 'bɪnd̪aːs', 'carefree', 'adj', 'slang', 2540],
  ['tagda', 'takda|tagdaa', 'तगड़ा', 't̪əgɽaː', 'sturdy/hefty (m)', 'adj', 'slang', 2541],
  ['dhaasu', 'dhasu|dhaansu', 'धाँसू', 'd̪ʰãːsuː', 'terrific', 'adj', 'slang', 2542],
  ['chindi', 'chindee|chhindi', 'चिंदी', 'tʃɪnd̪iː', 'petty/two-bit', 'adj', 'slang', 2543],
  ['kanjoos', 'kanjus|kanjoosss', 'कंजूस', 'kəndʒuːs', 'miserly', 'adj', 'slang', 2544],
  ['fokat', 'phokat|fokatt', 'फोकट', 'foːkəʈ', 'free of cost', 'adj', 'slang', 2545],
  ['besharam', 'besharamm|beshram', 'बेशरम', 'beːʃərəm', 'shameless', 'adj', 'slang', 2546],
  ['zabardast', 'jabardast|zabardastt', 'ज़बरदस्त', 'zəbərd̪əst̪', 'terrific/forceful', 'adj', 'slang', 2547],
  ['chakachak', 'chakaachak|chakachakk', 'चकाचक', 'tʃəkaːtʃək', 'spotless/spiffy', 'adj', 'slang', 2548],
  ['dhinchak', 'dhinchakk|dhinchack', 'धिनचक', 'd̪ʰɪntʃək', 'gaudy/flashy', 'adj', 'slang', 2549],
  ['lafanga', 'lafangaa|laphanga', 'लफ़ंगा', 'ləfəŋgaː', 'loafer/layabout (m)', 'adj', 'slang', 2550],
  ['chichhora', 'chichhoraa|chhichora', 'छिछोरा', 'tʃʰɪtʃʰoːraː', 'juvenile/cheap (m)', 'adj', 'slang', 2551],

  // ---- Hinglish slang: nouns ----------------------------------------
  ['yaara', 'yaaraa|yara', 'यारा', 'jaːraː', 'friend (vocative)', 'noun', 'slang', 2552],
  ['guru', 'guroo|gurru', 'गुरु', 'gʊrʊ', 'guru/mate', 'noun', 'slang', 2553],
  ['jugaad', 'jugad|jugaadd', 'जुगाड़', 'dʒʊgaːɽ', 'improvised fix', 'noun', 'slang', 2554],
  ['bakwas', 'bakvas|bakwaas', 'बकवास', 'bəkʋaːs', 'nonsense', 'noun', 'slang', 2555],
  ['timepass', 'timepas|taimpass', 'टाइमपास', 'ʈaːjmpaːs', 'idle pastime', 'noun', 'slang', 2556],
  ['lafda', 'laphda|lafdaa', 'लफड़ा', 'ləfɽaː', 'mess/entanglement', 'noun', 'slang', 2557],
  ['panga', 'pangaa|punga', 'पंगा', 'pəŋgaː', 'trouble/tussle', 'noun', 'slang', 2558],
  ['jhol', 'jholl|jhole', 'झोल', 'dʒʰoːl', 'discrepancy/fishiness', 'noun', 'slang', 2559],
  ['setting', 'seting|settingg', 'सेटिंग', 'seːʈɪŋg', 'arrangement/fix', 'noun', 'slang', 2560],
  ['scene', 'seen|sceen', 'सीन', 'siːn', 'situation', 'noun', 'slang', 2561],
  ['tension', 'tenshan|tensionn', 'टेंशन', 'ʈeːnʃən', 'worry/stress', 'noun', 'slang', 2562],
  ['faida', 'fayda|faayda', 'फ़ायदा', 'faːɪd̪aː', 'benefit', 'noun', 'corporate', 2563],
  ['nuksaan', 'nuksan|nuqsaan', 'नुक़सान', 'nʊqsaːn', 'loss/harm', 'noun', 'corporate', 2564],
  ['sharam', 'sharamm|shurm', 'शरम', 'ʃərəm', 'shame', 'noun', '', 2565],
  ['chakkar', 'chakar|chakkarr', 'चक्कर', 'tʃəkkər', 'round/dizziness/affair', 'noun', 'slang', 2566],
  ['kamaal', 'kamal|kamaall', 'कमाल', 'kəmaːl', 'wonder/marvel', 'noun', 'filmi', 2567],
  ['gazab', 'ghazab|gajab', 'ग़ज़ब', 'ɣəzəb', 'outrage/astonishing thing', 'noun', 'filmi', 2568],
  ['nautanki', 'nautankee|notanki', 'नौटंकी', 'nɔːʈəŋkiː', 'melodrama', 'noun', 'slang', 2569],
];
