// lib/lexicon/hi-nouns.ts
//
// Concrete nouns: people, places, things, institutions, and the vocabulary of
// everyday domains that hi-core deliberately leaves to this bank. Nothing here
// overlaps hi-core.ts — extended family, food, clothing, tech, corporate life,
// transport, health, and the NCR register live here.
//
// Transcription conventions, held constant across every bank:
//   - Hindi /h/ is the voiced glottal ɦ (Appendix E lists ɦ as Hindi-specific).
//   - Dental t̪ d̪ for Hindi t/d; retroflex ʈ ɖ ɽ only where genuinely retroflex.
//   - Vowel length is contrastive and always marked: ə vs aː, ɪ vs iː, ʊ vs uː.
//   - Nasalization is a tilde on the vowel, never a separate coda: maiṁ = mɛ̃ː.
//   - Word-final inherent schwa is never written: kamal = kəməl, not kəmələ.

import type { HiRow } from './hi-lexeme';

export const HI_NOUN_ROWS: HiRow[] = [
  // ---- Family and kinship -------------------------------------------------
  ['dada', 'daada|dadaji', 'दादा', 'daːd̪aː', 'grandfather (paternal)', 'noun', '', 500],
  ['dadi', 'daadi|dadiji', 'दादी', 'daːd̪iː', 'grandmother (paternal)', 'noun', '', 501],
  ['nana', 'naana|nanaji', 'नाना', 'naːnaː', 'grandfather (maternal)', 'noun', '', 502],
  ['nani', 'naani|naniji', 'नानी', 'naːniː', 'grandmother (maternal)', 'noun', '', 503],
  ['chacha', 'chaacha|chachaji', 'चाचा', 'tʃaːtʃaː', "father's younger brother", 'noun', '', 504],
  ['chachi', 'chaachi|chachiji', 'चाची', 'tʃaːtʃiː', "father's brother's wife", 'noun', '', 505],
  ['mama', 'maama|mamaji', 'मामा', 'maːmaː', "mother's brother", 'noun', '', 506],
  ['mami', 'maami|mamiji', 'मामी', 'maːmiː', "mother's brother's wife", 'noun', '', 507],
  ['bua', 'booa|buaji', 'बुआ', 'bʊaː', "father's sister", 'noun', '', 508],
  ['fufa', 'foofa|fufaji', 'फूफा', 'pʰuːpʰaː', "father's sister's husband", 'noun', '', 509],
  ['pati', 'pattii|pati', 'पति', 'pət̪i', 'husband', 'noun', '', 510],
  ['patni', 'patnii|patnee', 'पत्नी', 'pət̪niː', 'wife', 'noun', '', 511],
  ['biwi', 'beevi|bivi', 'बीवी', 'biːʋiː', 'wife (colloquial)', 'noun', 'slang', 512],
  ['shohar', 'sohar|shoharr', 'शोहर', 'ʃoːɦər', 'husband (Urdu)', 'noun', 'filmi', 513],
  ['parivar', 'pariwaar|parivaar', 'परिवार', 'pəriʋaːr', 'family', 'noun', '', 514],
  ['rishtedaar', 'rishtedar|rishtedaar', 'रिश्तेदार', 'rɪʃt̪eːd̪aːr', 'relative', 'noun', '', 515],
  ['padosi', 'padosii|parosi', 'पड़ोसी', 'pəɽoːsiː', 'neighbour', 'noun', 'ncr', 516],
  ['mehman', 'mehmaan|mehman', 'मेहमान', 'meːɦmaːn', 'guest', 'noun', '', 517],
  ['pota', 'potaa|potta', 'पोता', 'poːt̪aː', 'grandson', 'noun', '', 518],
  ['poti', 'potii|potee', 'पोती', 'poːt̪iː', 'granddaughter', 'noun', '', 519],
  ['damaad', 'damaad|damaad', 'दामाद', 'd̪aːmaːd̪', 'son-in-law', 'noun', '', 520],
  ['bahu', 'bahuu|bahu', 'बहू', 'bəɦuː', 'daughter-in-law', 'noun', '', 521],
  ['saas', 'saass|saasu', 'सास', 'saːs', 'mother-in-law', 'noun', '', 522],
  ['sasur', 'sasurr|sasoor', 'ससुर', 'səsʊr', 'father-in-law', 'noun', '', 523],
  ['jeth', 'jethh|jaith', 'जेठ', 'dʒeːʈʰ', "husband's elder brother", 'noun', '', 524],
  ['devar', 'devr|devarr', 'देवर', 'd̪eːʋər', "husband's younger brother", 'noun', '', 525],
  ['nanad', 'nanadd|nanad', 'ननद', 'nənd̪', "husband's sister", 'noun', '', 526],
  ['salaa', 'sala|salaa', 'साला', 'saːlaː', "wife's brother", 'noun', 'slang', 527],
  ['saali', 'saalee|sali', 'साली', 'saːliː', "wife's sister", 'noun', '', 528],
  ['bhabhi', 'bhabhii|bhabhi', 'भाभी', 'bʰaːbʰiː', 'sister-in-law', 'noun', '', 529],
  ['bachpan', 'bachpann|bachpan', 'बचपन', 'bətʃpən', 'childhood', 'noun', '', 530],
  ['joda', 'jodaa|joda', 'जोड़ा', 'dʒoːɽaː', 'pair/couple', 'noun', '', 531],
  ['khandaan', 'khandan|khandaan', 'ख़ानदान', 'xəndaːn', 'lineage/clan', 'noun', 'filmi', 532],
  ['vansh', 'wansh|vansh', 'वंश', 'ʋənʃ', 'dynasty/lineage', 'noun', '', 533],
  ['naukar', 'naukaar|nokar', 'नौकर', 'nɔːkər', 'servant', 'noun', '', 534],
  ['naukarani', 'naukarani|nokrani', 'नौकरानी', 'nɔːkəraːniː', 'maid', 'noun', '', 535],
  ['malik', 'malikk|maalik', 'मालिक', 'maːlɪk', 'owner/master', 'noun', '', 536],
  ['guru', 'guroo|gurru', 'गुरु', 'gʊrʊ', 'teacher/guru', 'noun', '', 537],
  ['shishya', 'shishyaa|shishya', 'शिष्य', 'ʃɪʃjaː', 'disciple/student', 'noun', '', 538],
  ['sathi', 'saathi|sathii', 'साथी', 'saːt̪ʰiː', 'companion/partner', 'noun', 'filmi', 539],

  // ---- Body ---------------------------------------------------------------
  ['kaan', 'kaan|kaann', 'कान', 'kaːn', 'ear', 'noun', '', 540],
  ['naak', 'naak|naakk', 'नाक', 'naːk', 'nose', 'noun', '', 541],
  ['muh', 'munh|muuh', 'मुँह', 'mũːɦ', 'mouth/face', 'noun', '', 542],
  ['honth', 'honthh|honṭh', 'होंठ', 'ɦõːʈʰ', 'lip', 'noun', '', 543],
  ['daant', 'daant|daant', 'दाँत', 'd̪ãːt̪', 'tooth', 'noun', '', 544],
  ['jeebh', 'jeebhh|jibh', 'जीभ', 'dʒiːbʰ', 'tongue', 'noun', '', 545],
  ['gala', 'galaa|gala', 'गला', 'gəlaː', 'throat/neck', 'noun', '', 546],
  ['kamar', 'kamarr|kamar', 'कमर', 'kəmər', 'waist/lower back', 'noun', '', 547],
  ['pet', 'pett|pet', 'पेट', 'peːʈ', 'belly/stomach', 'noun', '', 548],
  ['seena', 'seenaa|sina', 'सीना', 'siːnaː', 'chest', 'noun', '', 549],
  ['peeth', 'peethh|pith', 'पीठ', 'piːʈʰ', 'back', 'noun', '', 550],
  ['kandha', 'kandhaa|kandha', 'कंधा', 'kənd̪ʰaː', 'shoulder', 'noun', '', 551],
  ['kohni', 'kohnii|kohnee', 'कोहनी', 'koːɦniː', 'elbow', 'noun', '', 552],
  ['kalai', 'kalaai|kalai', 'कलाई', 'kəlaːiː', 'wrist', 'noun', '', 553],
  ['ungli', 'unglii|unglee', 'उँगली', 'ũːgliː', 'finger', 'noun', '', 554],
  ['nakhun', 'nakhunn|nakhoon', 'नाख़ुन', 'naːxʊn', 'fingernail', 'noun', '', 555],
  ['baal', 'baal|baall', 'बाल', 'baːl', 'hair', 'noun', '', 556],
  ['daadhi', 'daadhii|dadhi', 'दाढ़ी', 'daːɽʰiː', 'beard', 'noun', '', 557],
  ['mooch', 'moochh|much', 'मूँछ', 'mũːtʃʰ', 'moustache', 'noun', '', 558],
  ['bhaun', 'bhaun|bhau', 'भौं', 'bʰãːʊn', 'eyebrow', 'noun', '', 559],
  ['gal', 'gall|gaal', 'गाल', 'gaːl', 'cheek', 'noun', '', 560],
  ['gardan', 'gardann|gardan', 'गर्दन', 'gərd̪ən', 'neck', 'noun', '', 561],
  ['haddi', 'haddii|hadi', 'हड्डी', 'ɦəɖɖiː', 'bone', 'noun', '', 562],
  ['maans', 'maans|mans', 'माँस', 'mãːs', 'flesh/meat', 'noun', '', 563],
  ['twacha', 'tvacha|twachaa', 'त्वचा', 't̪ʋətʃaː', 'skin', 'noun', '', 564],
  ['dimaag', 'dimaag|dimaag', 'दिमाग़', 'd̪ɪmaːɣ', 'brain/mind', 'noun', '', 565],
  ['jigar', 'jigarr|jigar', 'जिगर', 'dʒɪgər', 'liver/heart (fig.)', 'noun', 'filmi', 566],
  ['paseena', 'paseenaa|pasina', 'पसीना', 'pəsinaː', 'sweat', 'noun', '', 567],
  ['aansu', 'aansoo|ansu', 'आँसू', 'ãːsuː', 'tear', 'noun', '', 568],
  ['thook', 'thookk|thuk', 'थूक', 't̪ʰuːk', 'saliva', 'noun', '', 569],
  ['rag', 'ragg|rag', 'रग', 'rəg', 'vein/nerve', 'noun', '', 570],
  ['nas', 'nass|nas', 'नस', 'nəs', 'vein/nerve', 'noun', '', 571],
  ['gutna', 'gutnaa|gutna', 'घुटना', 'gʊʈnaː', 'knee', 'noun', '', 572],
  ['pindli', 'pindlii|pindlee', 'पिंडली', 'pɪnd̪liː', 'calf/shin', 'noun', '', 573],
  ['jangh', 'janghh|jang', 'जाँघ', 'dʒãːgʰ', 'thigh', 'noun', '', 574],
  ['kamarband', 'kamarbandd|kamarband', 'कमरबंद', 'kəmərbənd̪', 'waistband/sash', 'noun', '', 575],
  ['sharir', 'sharirr|sharir', 'शरीर', 'ʃəriːr', 'body', 'noun', '', 576],
  ['roog', 'roog|rog', 'रोग', 'roːg', 'disease', 'noun', '', 577],
  ['bimari', 'bimaari|bimari', 'बीमारी', 'biːmaːriː', 'illness', 'noun', '', 578],
  ['tabyat', 'tabiyat|tabiyatt', 'तबीयत', 't̪əbɪjət̪', 'health/condition', 'noun', '', 579],

  // ---- Food and drink -----------------------------------------------------
  ['roti', 'rotee|rotii', 'रोटी', 'roːʈiː', 'bread/roti', 'noun', '', 580],
  ['dal', 'daal|dall', 'दाल', 'daːl', 'lentils', 'noun', '', 581],
  ['chawal', 'chawal|chaawal', 'चावल', 'tʃaːʋəl', 'rice', 'noun', '', 582],
  ['sabzi', 'sabzii|subzi', 'सब्ज़ी', 'səbziː', 'vegetable/curry', 'noun', '', 583],
  ['gosht', 'gosht|ghost', 'गोश्त', 'goːʃt̪', 'meat', 'noun', '', 584],
  ['machli', 'machlii|machlee', 'मछली', 'mətʃliː', 'fish', 'noun', '', 585],
  ['anda', 'andaa|anda', 'अंडा', 'əɳɖaː', 'egg', 'noun', '', 586],
  ['dahi', 'dahee|dahi', 'दही', 'd̪əɦiː', 'yoghurt', 'noun', '', 587],
  ['lassi', 'lasee|lassi', 'लस्सी', 'ləsiː', 'lassi', 'noun', 'ncr', 588],
  ['chai', 'chaaee|chaay', 'चाय', 'tʃaːj', 'tea', 'noun', '', 589],
  ['coffee', 'koffee|kofi', 'कॉफ़ी', 'kɔːfiː', 'coffee', 'noun', '', 590],
  ['namak', 'namakk|namak', 'नमक', 'nəmək', 'salt', 'noun', '', 591],
  ['mirch', 'mirchh|mirch', 'मिर्च', 'mɪrtʃ', 'chilli', 'noun', '', 592],
  ['masala', 'masalaa|masala', 'मसाला', 'məsalaː', 'spice/masala', 'noun', '', 593],
  ['ghee', 'gheee|ghi', 'घी', 'gʰiː', 'clarified butter', 'noun', '', 594],
  ['mithai', 'mithaai|mithai', 'मिठाई', 'mɪʈʰaːiː', 'sweet/confection', 'noun', '', 595],
  ['halwa', 'halvaa|halwa', 'हलवा', 'ɦəlʋaː', 'halwa', 'noun', '', 596],
  ['kheer', 'kheerr|khir', 'खीर', 'kʰiːr', 'rice pudding', 'noun', '', 597],
  ['samosa', 'samosa|samossaa', 'समोसा', 'səmoːsaː', 'samosa', 'noun', 'ncr', 598],
  ['pakora', 'pakoraa|pakoda', 'पकोड़ा', 'pəkoːɽaː', 'fritter/pakora', 'noun', '', 599],
  ['paratha', 'paraatha|pratha', 'पराठा', 'pəraːʈʰaː', 'paratha', 'noun', 'ncr', 600],
  ['puri', 'puree|poori', 'पूरी', 'puːriː', 'puri (fried bread)', 'noun', '', 601],
  ['sabun', 'sabunn|saabun', 'साबुन', 'saːbʊn', 'soap', 'noun', '', 602],
  ['tel', 'tell|tel', 'तेल', 't̪eːl', 'oil', 'noun', '', 603],
  ['shakkar', 'shakarr|shakar', 'शक्कर', 'ʃəkkər', 'sugar', 'noun', '', 604],
  ['cheeni', 'cheenii|chini', 'चीनी', 'tʃiːniː', 'sugar (refined)', 'noun', '', 605],
  ['atta', 'aataa|atta', 'आटा', 'aːʈaː', 'flour', 'noun', '', 606],
  ['gehun', 'gehunn|gehun', 'गेहूँ', 'geːɦũː', 'wheat', 'noun', '', 607],
  ['anaaj', 'anaaj|anaj', 'अनाज', 'ənaːdʒ', 'grain/cereal', 'noun', '', 608],
  ['phal', 'phall|fal', 'फल', 'pʰəl', 'fruit', 'noun', '', 609],
  ['sabji', 'sabjii|sabjee', 'सब्जी', 'səbdʒiː', 'vegetable', 'noun', '', 610],
  ['aam', 'aamm|am', 'आम', 'aːm', 'mango', 'noun', '', 611],
  ['kela', 'kelaa|kela', 'केला', 'keːlaː', 'banana', 'noun', '', 612],
  ['aloo', 'alu|aloo', 'आलू', 'aːluː', 'potato', 'noun', '', 613],
  ['pyaaz', 'pyaaj|pyaz', 'प्याज़', 'pjaːz', 'onion', 'noun', '', 614],
  ['tamatar', 'tamataar|tamatar', 'टमाटर', 'ʈəmaːʈər', 'tomato', 'noun', '', 615],
  ['adrak', 'adrakk|adrak', 'अदरक', 'əd̪rək', 'ginger', 'noun', '', 616],
  ['lahsun', 'lahsunn|lahsun', 'लहसुन', 'ləɦsʊn', 'garlic', 'noun', '', 617],
  ['doodh', 'dudh|doodhh', 'दूध', 'duːd̪ʰ', 'milk', 'noun', '', 618],
  ['paneer', 'paneerr|panir', 'पनीर', 'pəniːr', 'cottage cheese', 'noun', 'ncr', 619],
  ['biryani', 'biryaani|biryani', 'बिरयानी', 'bɪrjaːniː', 'biryani', 'noun', 'ncr', 620],
  ['tandoori', 'tandoorii|tanduri', 'तंदूरी', 't̪ənd̪uːriː', 'tandoori (style)', 'noun', 'ncr', 621],
  ['thali', 'thali|thaalee', 'थाली', 't̪ʰaːliː', 'plate/meal platter', 'noun', '', 622],
  ['bartan', 'bartann|bartan', 'बर्तन', 'bərt̪ən', 'utensil/dish', 'noun', '', 623],
  ['chammach', 'chamach|chammach', 'चम्मच', 'tʃəmmətʃ', 'spoon', 'noun', '', 624],
  ['katori', 'katorii|katori', 'कटोरी', 'kəʈoːriː', 'small bowl', 'noun', '', 625],
  ['glass', 'glas|glass', 'ग्लास', 'glaːs', 'glass', 'noun', '', 626],
  ['bottle', 'botl|bottl', 'बोतल', 'boːt̪əl', 'bottle', 'noun', '', 627],
  ['nimbu', 'nimboo|nimbu', 'नींबू', 'nĩːbuː', 'lemon/lime', 'noun', '', 628],
  ['sharbat', 'sharbatt|sharbat', 'शरबत', 'ʃərbət̪', 'sherbet/drink', 'noun', '', 629],

  // ---- Clothing and appearance --------------------------------------------
  ['kapda', 'kapdaa|kapra', 'कपड़ा', 'kəpɽaː', 'cloth/fabric', 'noun', '', 630],
  ['libaas', 'libas|libaas', 'लिबास', 'lɪbaːs', 'attire/dress', 'noun', 'filmi', 631],
  ['shirt', 'shart|shirt', 'शर्ट', 'ʃərʈ', 'shirt', 'noun', '', 632],
  ['pant', 'pantt|paint', 'पैंट', 'pɛ̃ʈ', 'trousers', 'noun', '', 633],
  ['saree', 'saari|sari', 'साड़ी', 'saːɽiː', 'sari', 'noun', '', 634],
  ['kurta', 'kurtaa|kurta', 'कुर्ता', 'kʊrt̪aː', 'kurta', 'noun', '', 635],
  ['dupatta', 'dupataa|dupatta', 'दुपट्टा', 'd̪ʊpəʈaː', 'dupatta/scarf', 'noun', '', 636],
  ['joota', 'jootaa|juta', 'जूता', 'dʒuːt̪aː', 'shoe', 'noun', '', 637],
  ['chappal', 'chapal|chappal', 'चप्पल', 'tʃəppəl', 'sandal/flip-flop', 'noun', '', 638],
  ['topi', 'topee|topi', 'टोपी', 'ʈoːpiː', 'cap/hat', 'noun', '', 639],
  ['mojri', 'mojrii|mojri', 'मोजरी', 'moːdʒriː', 'traditional shoe', 'noun', '', 640],
  ['angarkha', 'angarkhaa|angrakha', 'अंगरखा', 'əŋgərkʰaː', 'tunic/angarkha', 'noun', '', 641],
  ['salwar', 'salwaar|salvar', 'सलवार', 'səlʋaːr', 'salwar (trousers)', 'noun', '', 642],
  ['kameez', 'kameej|kameez', 'कमीज़', 'kəmiːz', 'kameez/tunic', 'noun', '', 643],
  ['suit', 'suit|soot', 'सूट', 'suːʈ', 'suit', 'noun', 'corporate', 644],
  ['tie', 'tai|tie', 'टाई', 'ʈaːiː', 'necktie', 'noun', 'corporate', 645],
  ['belt', 'beltt|belt', 'बेल्ट', 'beːlʈ', 'belt', 'noun', '', 646],
  ['sandal', 'sandl|sandal', 'सैंडल', 'sɛ̃ɖəl', 'sandal', 'noun', '', 647],
  ['jewar', 'jewar|jever', 'जेवर', 'dʒeːʋər', 'jewellery', 'noun', '', 648],
  ['kangan', 'kangann|kangan', 'कंगन', 'kəŋgən', 'bangle', 'noun', '', 649],
  ['mangalsutra', 'mangalsutr|mangalsutra', 'मंगलसूत्र', 'məŋgəlsuːt̪r', 'wedding necklace', 'noun', '', 650],
  ['sindoor', 'sindur|sindoor', 'सिंदूर', 'sɪnd̪uːr', 'vermilion', 'noun', '', 651],
  ['bindi', 'bindii|bindi', 'बिंदी', 'bɪnd̪iː', 'bindi', 'noun', '', 652],
  ['mehndi', 'mehndii|mehendi', 'मेहंदी', 'meːɦənd̪iː', 'henna', 'noun', '', 653],
  ['sringaar', 'shringaar|sringar', 'श्रृंगार', 'ʃrɪŋgaːr', 'adornment', 'noun', 'filmi', 654],
  ['rang', 'rangg|rang', 'रंग', 'rəŋg', 'colour', 'noun', '', 655],
  ['soorat', 'surat|soorat', 'सूरत', 'suːrət̪', 'appearance/face', 'noun', 'filmi', 656],
  ['shakl', 'shakal|shakl', 'शक्ल', 'ʃəkl', 'face/appearance', 'noun', '', 657],
  ['roop', 'roop|rooop', 'रूप', 'ruːp', 'form/beauty', 'noun', 'filmi', 658],
  ['huliya', 'huliyaa|huliya', 'हुलिया', 'ɦʊlijaː', 'disguise/appearance', 'noun', '', 659],

  // ---- Home and furniture -------------------------------------------------
  ['kamra', 'kamraa|kamra', 'कमरा', 'kəmraː', 'room', 'noun', '', 660],
  ['makaan', 'makaan|makan', 'मकान', 'məkaːn', 'house/building', 'noun', '', 661],
  ['darwaza', 'darwaazaa|darwaza', 'दरवाज़ा', 'd̪ərʋaːzaː', 'door', 'noun', '', 662],
  ['khidki', 'khidkii|khidkee', 'खिड़की', 'kʰɪɽkiː', 'window', 'noun', '', 663],
  ['deewar', 'diwaar|deewar', 'दीवार', 'd̪iːʋaːr', 'wall', 'noun', '', 664],
  ['chhat', 'chhatt|chat', 'छत', 'tʃʰət̪', 'roof', 'noun', '', 665],
  ['seedhi', 'seedhii|seedhee', 'सीढ़ी', 'siːɽʰiː', 'stairs/ladder', 'noun', '', 666],
  ['rasoi', 'rasoii|rasoi', 'रसोई', 'rəsoːiː', 'kitchen', 'noun', '', 667],
  ['kursi', 'kursii|kursee', 'कुर्सी', 'kʊrsiː', 'chair', 'noun', '', 668],
  ['mez', 'mej|maej', 'मेज़', 'meːz', 'table', 'noun', '', 669],
  ['takiya', 'takiyaa|takiya', 'तकिया', 't̪əkɪjaː', 'pillow', 'noun', '', 670],
  ['chadar', 'chadarr|chadar', 'चादर', 'tʃaːd̪ər', 'bedsheet', 'noun', '', 671],
  ['bistar', 'bistarr|bistar', 'बिस्तर', 'bɪst̪ər', 'bed/bedding', 'noun', '', 672],
  ['almari', 'almarii|almari', 'अलमारी', 'əlmariː', 'cupboard/wardrobe', 'noun', '', 673],
  ['tijori', 'tijorii|tijori', 'तिजोरी', 't̪ɪdʒoːriː', 'safe/strongbox', 'noun', '', 674],
  ['chabhi', 'chabhii|chaabi', 'चाबी', 'tʃaːbiː', 'key', 'noun', '', 675],
  ['taala', 'taalaa|tala', 'ताला', 't̪aːlaː', 'lock', 'noun', '', 676],
  ['batti', 'battii|bati', 'बत्ती', 'bət̪iː', 'wick/lamp', 'noun', '', 677],
  ['diya', 'diyaa|dia', 'दिया', 'd̪ɪjaː', 'oil lamp', 'noun', '', 678],
  ['bijli', 'bijlii|bijlee', 'बिजली', 'bɪdʒliː', 'electricity', 'noun', '', 679],
  ['pankha', 'pankhaa|pankha', 'पंखा', 'pəŋkʰaː', 'fan', 'noun', '', 680],
  ['cooler', 'coolr|kular', 'कूलर', 'kuːlər', 'cooler', 'noun', 'ncr', 681],
  ['AC', 'aasi|ac', 'एसी', 'eːsiː', 'air conditioner', 'noun', 'ncr', 682],
  ['fridge', 'frij|fridge', 'फ्रिज', 'pʰrɪdʒ', 'refrigerator', 'noun', '', 683],
  ['geyser', 'geyser|gijar', 'गीज़र', 'giːzər', 'water heater', 'noun', 'ncr', 684],
  ['nali', 'nali|nalee', 'नाली', 'naːliː', 'drain/gutter', 'noun', 'ncr', 685],
  ['tanki', 'tankii|tanki', 'टंकी', 'ʈəŋkiː', 'tank/reservoir', 'noun', '', 686],
  ['motor', 'motr|motor', 'मोटर', 'moːʈər', 'motor/pump', 'noun', '', 687],
  ['aangan', 'aangann|angan', 'आँगन', 'ãːgən', 'courtyard', 'noun', '', 688],
  ['chabutra', 'chabutraa|chabutra', 'चबूतरा', 'tʃəbuːt̪raː', 'platform/terrace', 'noun', '', 689],
  ['baagh', 'bagh|baagh', 'बाग', 'baːg', 'garden', 'noun', '', 690],
  ['kuan', 'kuaan|kuan', 'कुआँ', 'kʊãː', 'well', 'noun', '', 691],
  ['chulha', 'chulhaa|chulha', 'चूल्हा', 'tʃuːlʰaː', 'stove/hearth', 'noun', '', 692],
  ['chimta', 'chimtaa|chimta', 'चिमटा', 'tʃɪmʈaː', 'tongs', 'noun', '', 693],
  ['kadahi', 'kadaahii|kadahi', 'कड़ाही', 'kəɽaːɦiː', 'wok/kadhai', 'noun', '', 694],
  ['tawa', 'tavaa|tawa', 'तवा', 't̪əʋaː', 'griddle', 'noun', '', 695],
  ['chakla', 'chaklaa|chakla', 'चक्ला', 'tʃəklaː', 'rolling board', 'noun', '', 696],
  ['belan', 'belann|belan', 'बेलन', 'beːlən', 'rolling pin', 'noun', '', 697],
  ['jhadu', 'jhaduu|jhadu', 'झाड़ू', 'dʒʰaːɽuː', 'broom', 'noun', '', 698],
  ['pocha', 'pochaa|pocha', 'पोछा', 'poːtʃaː', 'mop/cloth', 'noun', 'ncr', 699],

  // ---- Animals -----------------------------------------------------------
  ['kutta', 'kutaa|kutta', 'कुत्ता', 'kʊt̪aː', 'dog', 'noun', '', 700],
  ['billi', 'billee|billi', 'बिल्ली', 'bɪlliː', 'cat', 'noun', '', 701],
  ['gaay', 'gay|gaay', 'गाय', 'gaːj', 'cow', 'noun', '', 702],
  ['bhains', 'bhains|bhains', 'भैंस', 'bʰɛ̃s', 'buffalo', 'noun', '', 703],
  ['bakri', 'bakrii|bakri', 'बकरी', 'bəkriː', 'goat', 'noun', '', 704],
  ['bakra', 'bakraa|bakra', 'बकरा', 'bəkraː', 'he-goat', 'noun', '', 705],
  ['murga', 'murgal|murga', 'मुर्गा', 'mʊrgaː', 'rooster', 'noun', '', 706],
  ['murgi', 'murgii|murgi', 'मुर्गी', 'mʊrgiː', 'hen', 'noun', '', 707],
  ['ghoda', 'ghodaa|ghoda', 'घोड़ा', 'gʰoːɽaː', 'horse', 'noun', '', 708],
  ['gadha', 'gadhaa|gadha', 'गधा', 'gəd̪ʰaː', 'donkey', 'noun', '', 709],
  ['haathi', 'hathi|haathi', 'हाथी', 'ɦaːt̪ʰiː', 'elephant', 'noun', '', 710],
  ['sher', 'sherr|sher', 'शेर', 'ʃeːr', 'lion/tiger', 'noun', '', 711],
  ['bagh', 'baghh|bagh', 'बाघ', 'baːgʰ', 'tiger', 'noun', '', 712],
  ['bandar', 'bandarr|bandar', 'बंदर', 'bənd̪ər', 'monkey', 'noun', '', 713],
  ['khargosh', 'khargosh|khargosh', 'खरगोश', 'kʰərgoːʃ', 'rabbit', 'noun', '', 714],
  ['chuha', 'chuhaa|chuha', 'चूहा', 'tʃuːɦaː', 'rat/mouse', 'noun', '', 715],
  ['samp', 'samp|saanp', 'साँप', 'sãːp', 'snake', 'noun', '', 716],
  ['cheenti', 'cheentii|chinti', 'चींटी', 'tʃĩːʈiː', 'ant', 'noun', '', 717],
  ['makhi', 'makhii|makhi', 'मक्खी', 'məkʰiː', 'fly (insect)', 'noun', '', 718],
  ['machhar', 'machharr|machhar', 'मच्छर', 'mətʃʰər', 'mosquito', 'noun', 'ncr', 719],
  ['kabootar', 'kabutar|kabootar', 'कबूतर', 'kəbuːt̪ər', 'pigeon', 'noun', '', 720],
  ['kauwa', 'kauvaa|kauwa', 'कौवा', 'kɔːʋaː', 'crow', 'noun', '', 721],
  ['mor', 'morr|mor', 'मोर', 'moːr', 'peacock', 'noun', '', 722],
  ['tota', 'totaa|tota', 'तोता', 't̪oːt̪aː', 'parrot', 'noun', '', 723],
  ['ullu', 'ullu|ulloo', 'उल्लू', 'ʊlluː', 'owl', 'noun', 'slang', 724],
  ['bheriya', 'bheriyaa|bheriya', 'भेड़िया', 'bʰeːɽɪjaː', 'wolf', 'noun', '', 725],
  ['lomdi', 'lomdii|lomdi', 'लोमड़ी', 'loːmɽiː', 'fox', 'noun', '', 726],
  ['magarmach', 'magarmach|magarmach', 'मगरमच्छ', 'məgərmətʃʰ', 'crocodile', 'noun', '', 727],
  ['mendhak', 'mendhakk|mendhak', 'मेंढक', 'mẽːɽʰək', 'frog', 'noun', '', 728],
  ['machhli', 'machhlii|machli', 'मछली', 'mətʃʰliː', 'fish (animal)', 'noun', '', 729],

  // ---- Nature and plants --------------------------------------------------
  ['ped', 'pedd|ped', 'पेड़', 'peːɽ', 'tree', 'noun', '', 730],
  ['phool', 'phool|fool', 'फूल', 'pʰuːl', 'flower', 'noun', '', 731],
  ['paudha', 'paudhaa|poudha', 'पौधा', 'pɔːd̪ʰaː', 'plant/sapling', 'noun', '', 732],
  ['patta', 'pattaa|patta', 'पत्ता', 'pət̪aː', 'leaf', 'noun', '', 733],
  ['jhaad', 'jhaad|jhad', 'झाड़', 'dʒʰaːɽ', 'bush/shrub', 'noun', '', 734],
  ['nadi', 'nadii|nadi', 'नदी', 'nəd̪iː', 'river', 'noun', '', 735],
  ['talab', 'talabb|talab', 'तालाब', 't̪aːlaːb', 'pond/lake', 'noun', '', 736],
  ['pahad', 'pahadd|pahad', 'पहाड़', 'pəɦaːɽ', 'mountain/hill', 'noun', '', 737],
  ['jungle', 'jungl|jungle', 'जंगल', 'dʒəŋgəl', 'forest/jungle', 'noun', '', 738],
  ['ret', 'rett|ret', 'रेत', 'reːt̪', 'sand', 'noun', '', 739],
  ['mitti', 'mittii|miti', 'मिट्टी', 'mɪʈʈiː', 'soil/earth', 'noun', '', 740],
  ['kankar', 'kankarr|kankar', 'कंकड़', 'kəŋkəɽ', 'gravel/pebble', 'noun', '', 741],
  ['patthar', 'pathar|patthar', 'पत्थर', 'pət̪t̪ʰər', 'stone/rock', 'noun', '', 742],
  ['chattan', 'chattann|chatan', 'चट्टान', 'tʃəʈaːn', 'cliff/rock face', 'noun', '', 743],
  ['barf', 'barff|barf', 'बर्फ', 'bərf', 'ice/snow', 'noun', '', 744],
  ['toofan', 'tufan|toofan', 'तूफ़ान', 'tuːfaːn', 'storm', 'noun', '', 745],
  ['andhi', 'andhii|andhi', 'आँधी', 'ãːd̪ʰiː', 'dust storm', 'noun', 'ncr', 746],
  ['garaj', 'garajj|gurj', 'गरज', 'gəraːdʒ', 'thunder', 'noun', '', 747],
  ['kadak', 'kadakk|kadak', 'कड़ाक', 'kəɽaːk', 'severe cold snap', 'noun', 'ncr', 748],
  ['sard', 'sardd|sard', 'सर्द', 'sərd̪', 'cold (weather)', 'noun', '', 749],
  ['garmi', 'garmii|garmi', 'गर्मी', 'gərmɪiː', 'heat/summer', 'noun', '', 750],
  ['sardi', 'sardii|sardi', 'सर्दी', 'sərd̪iː', 'cold/winter', 'noun', '', 751],
  ['barkha', 'barkhaa|barsaat', 'बरखा', 'bərkʰaː', 'rainy season', 'noun', 'filmi', 752],
  ['khet', 'khett|khet', 'खेत', 'kʰeːt̪', 'field/farm', 'noun', '', 753],
  ['khalihan', 'khalihann|khalihan', 'खलिहान', 'kʰəlɪɦaːn', 'threshing floor', 'noun', '', 754],
  ['kisan', 'kisann|kisan', 'किसान', 'kɪsaːn', 'farmer', 'noun', '', 755],
  ['mazdoor', 'mazdoorr|mazdur', 'मज़दूर', 'məzd̪uːr', 'labourer', 'noun', '', 756],
  ['hal', 'hall|hal', 'हल', 'ɦəl', 'plough', 'noun', '', 757],
  ['kuda', 'kudaa|kuda', 'कूड़ा', 'kuːɽaː', 'garbage', 'noun', 'ncr', 758],
  ['kachra', 'kachraa|kachra', 'कचरा', 'kətʃraː', 'trash/waste', 'noun', 'ncr', 759],

  // ---- Education and school -----------------------------------------------
  ['school', 'skool|school', 'स्कूल', 'skuːl', 'school', 'noun', '', 760],
  ['college', 'kollege|college', 'कॉलेज', 'kɔːleːdʒ', 'college', 'noun', '', 761],
  ['vidyalaya', 'vidyalaya|vidyalaya', 'विद्यालय', 'ʋɪd̪jaːləj', 'school (formal)', 'noun', '', 762],
  ['university', 'yunivarsiti|university', 'यूनिवर्सिटी', 'juːnɪʋərsɪʈiː', 'university', 'noun', '', 763],
  ['class', 'klas|class', 'क्लास', 'klaːs', 'class', 'noun', '', 764],
  ['padhai', 'padhaai|padai', 'पढ़ाई', 'pəɽʰaːiː', 'studies/education', 'noun', '', 765],
  ['imtihaan', 'imtihaan|imtehan', 'इम्तिहान', 'ɪmt̪ɪɦaːn', 'exam', 'noun', '', 766],
  ['pariksha', 'parikshaa|pariksha', 'परीक्षा', 'pəriːkʃaː', 'examination', 'noun', '', 767],
  ['number', 'nambar|number', 'नंबर', 'nəmbər', 'number/mark', 'noun', '', 768],
  ['degree', 'digree|degree', 'डिग्री', 'ɖigriː', 'degree', 'noun', '', 769],
  ['daktar', 'daktar|doctor', 'डॉक्टर', 'ɖɔkʈər', 'doctor (title)', 'noun', '', 770],
  ['vakil', 'vakill|vakil', 'वकील', 'ʋəkiːl', 'lawyer', 'noun', '', 771],
  ['engineer', 'enjinear|engineer', 'इंजीनियर', 'ɪndʒiːnɪjər', 'engineer', 'noun', 'tech', 772],
  ['master', 'mastar|master', 'मास्टर', 'maːsʈər', 'teacher/master', 'noun', '', 773],
  ['principal', 'prinsipal|principal', 'प्रिंसिपल', 'prɪnsɪpəl', 'principal', 'noun', '', 774],
  ['student', 'student|stoodent', 'स्टूडेंट', 'sʈuːɖeːnʈ', 'student', 'noun', '', 775],
  ['teacher', 'teecher|teacher', 'टीचर', 'ʈiːtʃər', 'teacher', 'noun', '', 776],
  ['copy', 'kopii|copy', 'कॉपी', 'kɔːpiː', 'notebook/copy', 'noun', '', 777],
  ['kalam', 'kalamm|kalam', 'कलम', 'kələm', 'pen', 'noun', '', 778],
  ['pencil', 'pensil|pencil', 'पेंसिल', 'peːnsɪl', 'pencil', 'noun', '', 779],
  ['kagaz', 'kagaj|kagaz', 'कागज', 'kaːgədʒ', 'paper', 'noun', '', 780],
  ['kitaab', 'kitab|kitaab', 'किताब', 'kɪt̪aːb', 'book', 'noun', '', 781],
  ['pustak', 'pustakk|pustak', 'पुस्तक', 'pust̪ək', 'book (formal)', 'noun', '', 782],
  ['sawal', 'sawal|sawal', 'सवाल', 'səʋaːl', 'question', 'noun', '', 783],
  ['jawab', 'jawab|javaab', 'जवाब', 'dʒəʋaːb', 'answer', 'noun', '', 784],
  ['homework', 'homvark|homework', 'होमवर्क', 'ɦoːmʋərk', 'homework', 'noun', '', 785],
  ['project', 'projekt|project', 'प्रोजेक्ट', 'proːdʒekʈ', 'project', 'noun', 'corporate', 786],
  ['subject', 'sabjekt|subject', 'सब्जेक्ट', 'səbdʒekʈ', 'subject (school)', 'noun', '', 787],
  ['science', 'sains|science', 'साइंस', 'saːɪns', 'science', 'noun', '', 788],
  ['math', 'maths|math', 'मैथ', 'mɛːt̪ʰ', 'mathematics', 'noun', '', 789],

  // ---- Corporate and business ---------------------------------------------
  ['company', 'kampani|company', 'कंपनी', 'kəmpniː', 'company', 'noun', 'corporate', 790],
  ['office', 'offis|office', 'ऑफिस', 'ɔːfɪs', 'office', 'noun', 'corporate', 791],
  ['boss', 'boss|bos', 'बॉस', 'bɔːs', 'boss', 'noun', 'corporate', 792],
  ['naukri', 'naukrii|nokri', 'नौकरी', 'nɔːkriː', 'job', 'noun', 'corporate', 793],
  ['salary', 'salary|selri', 'सैलरी', 'sɛːlriː', 'salary', 'noun', 'corporate', 794],
  ['vetan', 'vetann|vetan', 'वेतन', 'ʋeːt̪ən', 'wage/salary', 'noun', 'corporate', 795],
  ['profit', 'profit|prophit', 'प्रॉफिट', 'prɔːfɪʈ', 'profit', 'noun', 'corporate', 796],
  ['loss', 'los|loss', 'लॉस', 'lɔːs', 'loss', 'noun', 'corporate', 797],
  ['meeting', 'meeting|miting', 'मीटिंग', 'miːʈɪŋg', 'meeting', 'noun', 'corporate', 798],
  // 'deal' intentionally omitted — it is English (CMUdict) and lives in the
  // English tagged banks; a Hindi romanization entry would steal the language
  // ID call on every corporate bar.
  ['contract', 'kontract|contract', 'कॉन्ट्रैक्ट', 'kɔːnʈrɛːkʈ', 'contract', 'noun', 'corporate', 800],
  ['client', 'klayent|client', 'क्लाइंट', 'kləɪnʈ', 'client', 'noun', 'corporate', 801],
  ['customer', 'kastamar|customer', 'कस्टमर', 'kəsʈəmər', 'customer', 'noun', 'corporate', 802],
  ['market', 'markit|market', 'मार्केट', 'maːrket̪', 'market', 'noun', 'corporate', 803],
  ['business', 'biznis|business', 'बिज़नेस', 'bɪznəs', 'business', 'noun', 'corporate', 804],
  ['dukan', 'dukaan|dukan', 'दुकान', 'd̪ʊkaːn', 'shop/store', 'noun', '', 805],
  ['dokaan', 'dokaan|dokan', 'दोकान', 'doːkaːn', 'shop (colloquial)', 'noun', 'ncr', 806],
  ['rate', 'reyt|rate', 'रेट', 'reːʈ', 'rate/price', 'noun', 'corporate', 807],
  ['daam', 'daam|dam', 'दाम', 'daːm', 'price/cost', 'noun', '', 808],
  ['kiraya', 'kirayaa|kiraya', 'किराया', 'kɪraːjaː', 'rent', 'noun', '', 809],
  ['loan', 'lon|loan', 'लोन', 'loːn', 'loan', 'noun', 'corporate', 810],
  ['karz', 'karzz|karz', 'कर्ज', 'kərz', 'debt/loan', 'noun', '', 811],
  ['byaj', 'byaj|biyaj', 'ब्याज', 'bjaːdʒ', 'interest (finance)', 'noun', 'corporate', 812],
  ['bank', 'bankk|bank', 'बैंक', 'bɛ̃k', 'bank', 'noun', 'corporate', 813],
  ['account', 'akaunt|account', 'अकाउंट', 'əkãːʊnʈ', 'account', 'noun', 'corporate', 814],
  ['cheque', 'chek|cheque', 'चेक', 'tʃeːk', 'cheque', 'noun', 'corporate', 815],
  ['bill', 'bill|bil', 'बिल', 'bɪl', 'bill', 'noun', 'corporate', 816],
  ['invoice', 'invoice|invoys', 'इनवॉइस', 'ɪnʋɔːɪs', 'invoice', 'noun', 'corporate', 817],
  ['tax', 'taks|tax', 'टैक्स', 'ʈɛːks', 'tax', 'noun', 'corporate', 818],
  ['GST', 'gisti|gst', 'जीएसटी', 'dʒiːeːesʈiː', 'GST', 'noun', 'corporate', 819],

  // ---- Technology ---------------------------------------------------------
  ['phone', 'fon|phone', 'फोन', 'pʰoːn', 'telephone', 'noun', 'tech', 820],
  ['mobile', 'mobail|mobile', 'मोबाइल', 'moːbaːɪl', 'mobile phone', 'noun', 'tech', 821],
  ['computer', 'kampyootar|computer', 'कंप्यूटर', 'kəmpjuːʈər', 'computer', 'noun', 'tech', 822],
  ['laptop', 'laptop|laptop', 'लैपटॉप', 'lɛːpʈɔːp', 'laptop', 'noun', 'tech', 823],
  ['internet', 'internet|intarnet', 'इंटरनेट', 'ɪnʈərneːʈ', 'internet', 'noun', 'tech', 824],
  ['email', 'imeel|email', 'ईमेल', 'iːmeːl', 'email', 'noun', 'tech', 825],
  ['message', 'messej|message', 'मैसेज', 'mɛːseːdʒ', 'message', 'noun', 'tech', 826],
  ['app', 'aap|app', 'ऐप', 'ɛːp', 'app', 'noun', 'tech', 827],
  ['website', 'vebsait|website', 'वेबसाइट', 'ʋeːbsaːɪʈ', 'website', 'noun', 'tech', 828],
  ['data', 'deyta|data', 'डेटा', 'ɖeːʈaː', 'data', 'noun', 'tech', 829],
  ['server', 'sarvar|server', 'सर्वर', 'sərʋər', 'server', 'noun', 'tech', 830],
  ['password', 'pasvard|password', 'पासवर्ड', 'paːsʋərd', 'password', 'noun', 'tech', 831],
  ['screen', 'skreen|screen', 'स्क्रीन', 'skriːn', 'screen', 'noun', 'tech', 832],
  ['camera', 'kaimra|camera', 'कैमरा', 'kɛːmr', 'camera', 'noun', 'tech', 833],
  ['video', 'vidiou|video', 'वीडियो', 'ʋiːɖioː', 'video', 'noun', 'tech', 834],
  ['photo', 'foto|photo', 'फोटो', 'pʰoːʈoː', 'photo', 'noun', 'tech', 835],
  ['file', 'fayl|file', 'फाइल', 'pʰaːɪl', 'file', 'noun', 'tech', 836],
  ['folder', 'foldar|folder', 'फोल्डर', 'pʰoːlɖər', 'folder', 'noun', 'tech', 837],
  ['software', 'softveer|software', 'सॉफ्टवेयर', 'sɔːfʈʋeːjər', 'software', 'noun', 'tech', 838],
  ['hardware', 'hardveer|hardware', 'हार्डवेयर', 'ɦaːrɖʋeːjər', 'hardware', 'noun', 'tech', 839],
  ['network', 'netvark|network', 'नेटवर्क', 'neːʈʋərk', 'network', 'noun', 'tech', 840],
  ['wifi', 'vaifai|wifi', 'वाईफाई', 'ʋaːɪpʰaːɪ', 'Wi-Fi', 'noun', 'tech', 841],
  ['charger', 'chaarjar|charger', 'चार्जर', 'tʃaːrdʒər', 'charger', 'noun', 'tech', 842],
  ['battery', 'baitri|battery', 'बैटरी', 'bɛːʈriː', 'battery', 'noun', 'tech', 843],
  ['signal', 'signaal|signal', 'सिग्नल', 'sɪgnəl', 'signal', 'noun', 'tech', 844],
  ['code', 'kod|code', 'कोड', 'koːɖ', 'code', 'noun', 'tech', 845],
  ['bug', 'bagg|bug', 'बग', 'bəg', 'bug (software)', 'noun', 'tech', 846],
  ['update', 'apdeyt|update', 'अपडेट', 'əpɖeːʈ', 'update', 'noun', 'tech', 847],
  ['download', 'daunlod|download', 'डाउनलोड', 'ɖãːʊnloːɖ', 'download', 'noun', 'tech', 848],
  ['link', 'link|link', 'लिंक', 'lɪŋk', 'link', 'noun', 'tech', 849],

  // ---- Transport and travel -----------------------------------------------
  ['gaadi', 'gadi|gaadi', 'गाड़ी', 'gaːɽiː', 'vehicle/car', 'noun', '', 850],
  ['car', 'kaar|car', 'कार', 'kaːr', 'car', 'noun', '', 851],
  ['bus', 'buss|bas', 'बस', 'bəs', 'bus', 'noun', '', 852],
  ['train', 'treyn|train', 'ट्रेन', 'ʈreːn', 'train', 'noun', '', 853],
  ['metro', 'metro|metro', 'मेट्रो', 'meːʈroː', 'metro', 'noun', 'ncr', 854],
  ['auto', 'auto|auto', 'ऑटो', 'ɔːʈoː', 'auto-rickshaw', 'noun', 'ncr', 855],
  ['rickshaw', 'riksha|rickshaw', 'रिक्शा', 'rɪkʃaː', 'rickshaw', 'noun', 'ncr', 856],
  ['cycle', 'saikil|cycle', 'साइकिल', 'saːɪkɪl', 'bicycle', 'noun', '', 857],
  ['bike', 'baik|bike', 'बाइक', 'baːɪk', 'bike/motorcycle', 'noun', '', 858],
  ['scooter', 'skootar|scooter', 'स्कूटर', 'skuːʈər', 'scooter', 'noun', '', 859],
  ['ticket', 'tiket|ticket', 'टिकट', 'ʈɪkəʈ', 'ticket', 'noun', '', 860],
  ['station', 'steshan|station', 'स्टेशन', 'sʈeːʃən', 'station', 'noun', '', 861],
  ['airport', 'eyrport|airport', 'एयरपोर्ट', 'eːjərpoːrʈ', 'airport', 'noun', '', 862],
  ['flight', 'flait|flight', 'फ्लाइट', 'pʰlaːɪʈ', 'flight', 'noun', '', 863],
  ['adda', 'addaa|adda', 'अड्डा', 'əɽaː', 'hangout/spot', 'noun', 'ncr', 864],
  ['yatra', 'yatraa|yatra', 'यात्रा', 'jaːt̪raː', 'journey/trip', 'noun', '', 865],
  ['rasta', 'rastaa|rasta', 'रास्ता', 'rəst̪aː', 'route/way', 'noun', '', 866],
  ['hooter', 'hutar|hooter', 'हूटर', 'ɦuːʈər', 'car horn', 'noun', 'slang', 867],
  ['traffic', 'traafik|traffic', 'ट्रैफ़िक', 'ʈrɛːfɪk', 'traffic', 'noun', 'ncr', 868],
  // English borrowings that CMUdict already owns (jam, driver, conductor) are
  // omitted — a Hindi row for them steals the language-ID call.
  ['saman', 'samann|samaan', 'सामान', 'saːmaːn', 'luggage/goods', 'noun', '', 872],
  ['thela', 'thelaa|thela', 'ठेला', 'ʈʰeːlaː', 'handcart', 'noun', 'ncr', 873],
  ['bazaar', 'bazar|bazaar', 'बाज़ार', 'baːzaːr', 'market/bazaar', 'noun', '', 874],
  ['marg', 'marag|marg', 'मार्ग', 'maːrg', 'road/path (formal)', 'noun', '', 875],
  ['pul', 'pull|pul', 'पुल', 'pʊl', 'bridge', 'noun', '', 876],
  ['chowk', 'chowkk|chauk', 'चौक', 'tʃɔːk', 'crossroads/square', 'noun', 'ncr', 877],
  ['makaam', 'makam|makaamm', 'मकाम', 'məkaːm', 'stopping place/stage', 'noun', '', 878],
  ['kanta', 'kantaa|kaanta', 'कांटा', 'kãːʈaː', 'toll/checkpoint', 'noun', 'ncr', 879],
  ['addaa', 'adda|addaa', 'अड्डा', 'əɖɖaː', 'hangout/stand', 'noun', 'slang', 880],
  ['chalak', 'chaalak|chalak', 'चालक', 'tʃaːlək', 'driver (Hindi)', 'noun', '', 881],
  ['yatri', 'yaatri|yatree', 'यात्री', 'jaːt̪riː', 'passenger/traveller', 'noun', '', 882],
  ['tikat', 'tikit|tikat', 'टिकट', 'ʈikəʈ', 'ticket', 'noun', 'ncr', 883],
];
