// lib/lexicon/hi-verbs.ts
//
// Verbs, and — deliberately — their inflections. Hindi rhyme lives in the
// inflectional ending, not the root: -taa/-tii/-te, -aa/-ii/-e, -egaa/-egii/
// -ẽge, -o, -ũː, -ũːgaa, -kar. A bank of bare infinitives would rhyme every
// verb in the language with every other verb and nothing else, which is useless
// to a writer. So the high-frequency paradigm cells are listed as their own
// entries, each with its own IPA, because that is what a line actually ends on.
//
// Transcription conventions are the ones in hi-core.ts, plus one that matters
// more here than anywhere else: the IPA is what is *pronounced*, not what is
// spelled. Romanized Hindi writes schwas that native speech deletes, so
// `karna` is kərnaː and `samajhna` is səmədʒʰnaː, while the vowel-initial
// suffixes pull the medial schwa out again — `samjha` is səmdʒʰaː, `nikla` is
// nɪklaː. Syllable counts are derived from these strings, so a letter-by-letter
// transliteration would silently break every rhyme in the file.

import type { HiRow } from './hi-lexeme';

export const HI_VERB_ROWS: HiRow[] = [
  // ---- Infinitives: buying, selling, money, exchange ----------------------
  ['bhejna', 'bhejnaa|bejna', 'भेजना', 'bʰeːdʒnaː', 'to send', 'verb', '', 1400],
  ['kharidna', 'kharidnaa|khareedna', 'खरीदना', 'kʰəriːd̪naː', 'to buy', 'verb', '', 1401],
  ['bechna', 'bechnaa|bechnna', 'बेचना', 'beːtʃnaː', 'to sell', 'verb', '', 1402],
  ['kamana', 'kamaana|kmana', 'कमाना', 'kəmaːnaː', 'to earn', 'verb', 'corporate', 1403],
  ['kharchna', 'kharchnaa|kharachna', 'खर्चना', 'kʰərtʃnaː', 'to spend', 'verb', '', 1404],
  ['mangna', 'maangna|maangnaa', 'माँगना', 'mãːgnaː', 'to ask for', 'verb', '', 1405],
  ['lautna', 'lotna|lautnaa', 'लौटना', 'lɔːʈnaː', 'to return', 'verb', '', 1406],
  ['bantna', 'baantna|baantnaa', 'बाँटना', 'bãːʈnaː', 'to distribute', 'verb', '', 1407],
  ['jodna', 'jodnaa|jornaa', 'जोड़ना', 'dʒoːɽnaː', 'to join/add', 'verb', '', 1408],
  ['ginna', 'ginnaa|gin', 'गिनना', 'gɪnnaː', 'to count', 'verb', '', 1409],
  ['tolna', 'tolnaa', 'तोलना', 't̪oːlnaː', 'to weigh', 'verb', '', 1410],
  ['napna', 'naapna|naapnaa', 'नापना', 'naːpnaː', 'to measure', 'verb', '', 1411],
  ['bikna', 'biknaa', 'बिकना', 'bɪknaː', 'to be sold', 'verb', '', 1412],
  ['lootna', 'lutna|lootnaa', 'लूटना', 'luːʈnaː', 'to loot', 'verb', '', 1413],
  ['lutna', 'lutnaa', 'लुटना', 'lʊʈnaː', 'to be robbed', 'verb', '', 1414],
  ['churana', 'churaana|chorana', 'चुराना', 'tʃʊraːnaː', 'to steal', 'verb', '', 1415],
  ['thagna', 'thagnaa', 'ठगना', 'ʈʰəgnaː', 'to cheat', 'verb', '', 1416],

  // ---- Infinitives: winning, losing, knowing, telling ---------------------
  ['jeetna', 'jitna|jeetnaa', 'जीतना', 'dʒiːt̪naː', 'to win', 'verb', '', 1420],
  ['harna', 'haarna|haarnaa', 'हारना', 'ɦaːrnaː', 'to lose', 'verb', '', 1421],
  ['sikhna', 'seekhna|sikhnaa', 'सीखना', 'siːkʰnaː', 'to learn', 'verb', '', 1422],
  ['sikhana', 'sikhaana|sikhaanaa', 'सिखाना', 'sɪkʰaːnaː', 'to teach', 'verb', '', 1423],
  ['padhana', 'padhaana|parhana', 'पढ़ाना', 'pəɽʰaːnaː', 'to teach/instruct', 'verb', '', 1424],
  ['batana', 'bataana|btana', 'बताना', 'bət̪aːnaː', 'to tell', 'verb', '', 1425],
  ['dikhana', 'dikhaana|dikhaanaa', 'दिखाना', 'd̪ɪkʰaːnaː', 'to show', 'verb', '', 1426],
  ['samjhana', 'samjhaana|samajhana', 'समझाना', 'səmdʒʰaːnaː', 'to explain', 'verb', '', 1427],
  ['jaanna', 'janna|jaannaa', 'जानना', 'dʒaːnnaː', 'to know', 'verb', '', 1428],
  ['maanna', 'manna|maannaa', 'मानना', 'maːnnaː', 'to accept/believe', 'verb', '', 1429],
  ['pehchanna', 'pehchaanna|pahchanna', 'पहचानना', 'pəɦtʃaːnnaː', 'to recognize', 'verb', '', 1430],
  ['bhoolna', 'bhulna|bhoolnaa', 'भूलना', 'bʰuːlnaː', 'to forget', 'verb', '', 1431],
  ['bhulana', 'bhulaana|bhoolana', 'भुलाना', 'bʰʊlaːnaː', 'to make forget', 'verb', '', 1432],
  ['khojna', 'khojnaa', 'खोजना', 'kʰoːdʒnaː', 'to search', 'verb', '', 1433],
  ['dhoondhna', 'dhundhna|dhoondna', 'ढूँढना', 'ɖʰũːɖʰnaː', 'to search for', 'verb', '', 1434],
  ['sunana', 'sunaana|sunaanaa', 'सुनाना', 'sʊnaːnaː', 'to recite/tell', 'verb', '', 1435],

  // ---- Infinitives: motion and the body -----------------------------------
  ['ghumna', 'ghoomna|ghumnaa', 'घूमना', 'gʰuːmnaː', 'to roam', 'verb', '', 1440],
  ['nikalna', 'nikalnaa|niklna', 'निकलना', 'nɪkəlnaː', 'to go out', 'verb', '', 1441],
  ['nikaalna', 'nikalna|nikaalnaa', 'निकालना', 'nɪkaːlnaː', 'to take out', 'verb', '', 1442],
  ['pahuchna', 'pahunchna|pahuchnaa', 'पहुँचना', 'pəɦʊ̃tʃnaː', 'to arrive', 'verb', '', 1443],
  ['laana', 'lana|laanaa', 'लाना', 'laːnaː', 'to bring', 'verb', '', 1444],
  ['daudna', 'daudnaa|dornaa', 'दौड़ना', 'd̪ɔːɽnaː', 'to run', 'verb', '', 1445],
  ['kudna', 'koodna|kudnaa', 'कूदना', 'kuːd̪naː', 'to jump', 'verb', '', 1446],
  ['uchhalna', 'uchalna|uchhalnaa', 'उछलना', 'ʊtʃʰəlnaː', 'to leap', 'verb', '', 1447],
  ['fisalna', 'phisalna|fisalnaa', 'फिसलना', 'pʰɪsəlnaː', 'to slip', 'verb', '', 1448],
  ['chadhna', 'chadna|charhna', 'चढ़ना', 'tʃəɽʰnaː', 'to climb', 'verb', '', 1449],
  ['utarna', 'utarnaa', 'उतरना', 'ʊt̪ərnaː', 'to descend', 'verb', '', 1450],
  ['baithna', 'bethna|baithnaa', 'बैठना', 'bɛːʈʰnaː', 'to sit', 'verb', '', 1451],
  ['rukna', 'ruknaa', 'रुकना', 'rʊknaː', 'to stop', 'verb', '', 1452],
  ['rokna', 'roknaa', 'रोकना', 'roːknaː', 'to stop (tr)', 'verb', '', 1453],
  ['thaharna', 'thaharnaa|thehrna', 'ठहरना', 'ʈʰəɦərnaː', 'to halt/stay', 'verb', '', 1454],
  ['jhukna', 'jhuknaa', 'झुकना', 'dʒʰʊknaː', 'to bow', 'verb', '', 1455],
  ['ghusna', 'ghusnaa', 'घुसना', 'gʰʊsnaː', 'to barge in', 'verb', 'slang', 1456],
  ['tairna', 'terna|tairnaa', 'तैरना', 't̪ɛːrnaː', 'to swim', 'verb', '', 1457],
  ['udna', 'udnaa|urnaa', 'उड़ना', 'ʊɽnaː', 'to fly', 'verb', '', 1458],
  ['udana', 'udaana|uraana', 'उड़ाना', 'ʊɽaːnaː', 'to fly/blow away', 'verb', '', 1459],
  ['nachna', 'naachna|naachnaa', 'नाचना', 'naːtʃnaː', 'to dance', 'verb', 'filmi', 1460],
  ['jagna', 'jaagna|jaagnaa', 'जागना', 'dʒaːgnaː', 'to wake', 'verb', '', 1461],
  ['thakna', 'thaknaa', 'थकना', 't̪ʰəknaː', 'to get tired', 'verb', '', 1462],
  ['dubna', 'doobna|dubnaa', 'डूबना', 'ɖuːbnaː', 'to sink/drown', 'verb', '', 1463],
  ['hatna', 'hatnaa', 'हटना', 'ɦəʈnaː', 'to move aside', 'verb', '', 1464],

  // ---- Infinitives: handling things ---------------------------------------
  ['pakadna', 'pakadnaa|pakarna', 'पकड़ना', 'pəkəɽnaː', 'to catch/hold', 'verb', '', 1470],
  ['chhinna', 'chhinnaa|cheenna', 'छीनना', 'tʃʰiːnnaː', 'to snatch', 'verb', '', 1471],
  ['kaatna', 'katna|kaatnaa', 'काटना', 'kaːʈnaː', 'to cut', 'verb', '', 1472],
  ['phodna', 'fodna|phornaa', 'फोड़ना', 'pʰoːɽnaː', 'to burst', 'verb', '', 1473],
  ['tootna', 'tutna|tootnaa', 'टूटना', 'ʈuːʈnaː', 'to break apart', 'verb', '', 1474],
  ['daalna', 'dalna|daalnaa', 'डालना', 'ɖaːlnaː', 'to put/pour', 'verb', '', 1475],
  ['bharna', 'bharnaa', 'भरना', 'bʰərnaː', 'to fill', 'verb', '', 1476],
  ['dabana', 'dabaana|dbana', 'दबाना', 'd̪əbaːnaː', 'to press', 'verb', '', 1477],
  ['uthana', 'uthaana|uthaanaa', 'उठाना', 'ʊʈʰaːnaː', 'to lift', 'verb', '', 1478],
  ['girana', 'giraana|giraanaa', 'गिराना', 'gɪraːnaː', 'to drop', 'verb', '', 1479],
  ['kholna', 'kholnaa', 'खोलना', 'kʰoːlnaː', 'to open', 'verb', '', 1480],
  ['khulna', 'khulnaa', 'खुलना', 'kʰʊlnaː', 'to open (intr)', 'verb', '', 1481],
  ['dikhna', 'dikhnaa', 'दिखना', 'd̪ɪkʰnaː', 'to be visible', 'verb', '', 1482],
  ['dhakna', 'dhaknaa', 'ढकना', 'ɖʰəknaː', 'to cover', 'verb', '', 1483],
  ['phenkna', 'fenkna|phenknaa', 'फेंकना', 'pʰẽːknaː', 'to throw', 'verb', '', 1484],
  ['kheenchna', 'khinchna|kheechna', 'खींचना', 'kʰĩːtʃnaː', 'to pull', 'verb', '', 1485],
  ['dhakelna', 'dhakelnaa', 'धकेलना', 'd̪ʰəkeːlnaː', 'to push', 'verb', '', 1486],
  ['peetna', 'pitna|peetnaa', 'पीटना', 'piːʈnaː', 'to beat', 'verb', '', 1487],
  ['talna', 'talnaa', 'तलना', 't̪əlnaː', 'to fry', 'verb', '', 1488],
  ['pakna', 'paknaa', 'पकना', 'pəknaː', 'to ripen/cook', 'verb', '', 1489],
  ['pakana', 'pakaana|pkana', 'पकाना', 'pəkaːnaː', 'to cook', 'verb', '', 1490],
  ['chakhna', 'chakhnaa', 'चखना', 'tʃəkʰnaː', 'to taste', 'verb', '', 1491],
  ['dhona', 'dhonaa', 'धोना', 'd̪ʰoːnaː', 'to wash', 'verb', '', 1492],
  ['pehenna', 'pehanna|pahanna', 'पहनना', 'pəɦənnaː', 'to wear', 'verb', '', 1493],
  ['utaarna', 'utarna|utaarnaa', 'उतारना', 'ʊt̪aːrnaː', 'to take off', 'verb', '', 1494],
  ['silna', 'silnaa', 'सिलना', 'sɪlnaː', 'to be sewn', 'verb', '', 1495],
  ['bunna', 'bunnaa', 'बुनना', 'bʊnnaː', 'to weave', 'verb', '', 1496],
  ['peesna', 'pisna|peesnaa', 'पीसना', 'piːsnaː', 'to grind', 'verb', '', 1497],
  ['rangna', 'rangnaa', 'रंगना', 'rəŋgnaː', 'to dye', 'verb', '', 1498],
  ['sajna', 'sajnaa', 'सजना', 'sədʒnaː', 'to be adorned', 'verb', 'filmi', 1499],
  ['sajana', 'sajaana|sjana', 'सजाना', 'sədʒaːnaː', 'to decorate', 'verb', '', 1500],
  ['taalna', 'talna|taalnaa', 'टालना', 'ʈaːlnaː', 'to postpone', 'verb', 'corporate', 1501],
  ['nibhana', 'nibhaana|nibhaanaa', 'निभाना', 'nɪbʰaːnaː', 'to fulfil/keep up', 'verb', '', 1502],

  // ---- Infinitives: change of state --------------------------------------
  ['badalna', 'badalnaa|badlna', 'बदलना', 'bəd̪əlnaː', 'to change', 'verb', '', 1505],
  ['sudharna', 'sudharnaa|sudhrna', 'सुधरना', 'sʊd̪ʰərnaː', 'to improve', 'verb', '', 1506],
  ['bigadna', 'bigadnaa|bigarna', 'बिगड़ना', 'bɪgəɽnaː', 'to be spoiled', 'verb', '', 1507],
  ['banna', 'bannaa', 'बनना', 'bənnaː', 'to become', 'verb', '', 1508],
  ['phailna', 'failna|phailnaa', 'फैलना', 'pʰɛːlnaː', 'to spread', 'verb', '', 1509],
  ['pighalna', 'pighalnaa|pighlna', 'पिघलना', 'pɪgʰəlnaː', 'to melt', 'verb', '', 1510],
  ['jalna', 'jalnaa', 'जलना', 'dʒəlnaː', 'to burn', 'verb', '', 1511],
  ['jalana', 'jalaana|jlana', 'जलाना', 'dʒəlaːnaː', 'to set alight', 'verb', '', 1512],
  ['bujhna', 'bujhnaa', 'बुझना', 'bʊdʒʰnaː', 'to be put out', 'verb', '', 1513],
  ['chamakna', 'chamaknaa|chmakna', 'चमकना', 'tʃəməknaː', 'to shine', 'verb', '', 1514],
  ['bhadakna', 'bhadaknaa|bharakna', 'भड़कना', 'bʰəɽəknaː', 'to flare up', 'verb', '', 1515],
  ['atakna', 'ataknaa', 'अटकना', 'əʈəknaː', 'to get stuck', 'verb', '', 1516],
  ['bhatakna', 'bhataknaa', 'भटकना', 'bʰəʈəknaː', 'to wander', 'verb', 'filmi', 1517],
  ['latakna', 'lataknaa', 'लटकना', 'ləʈəknaː', 'to hang', 'verb', '', 1518],
  ['sarakna', 'saraknaa', 'सरकना', 'sərəknaː', 'to slide', 'verb', '', 1519],
  ['dhalna', 'dhalnaa', 'ढलना', 'ɖʰəlnaː', 'to set/decline', 'verb', 'filmi', 1520],
  ['behna', 'bahna|behnaa', 'बहना', 'bəɦnaː', 'to flow', 'verb', '', 1521],
  ['barasna', 'barasnaa|barsna', 'बरसना', 'bərəsnaː', 'to rain down', 'verb', '', 1522],
  ['garajna', 'garajnaa|garjna', 'गरजना', 'gərədʒnaː', 'to thunder', 'verb', '', 1523],
  ['tapakna', 'tapaknaa', 'टपकना', 'ʈəpəknaː', 'to drip', 'verb', '', 1524],
  ['chhupna', 'chupna|chhupnaa', 'छुपना', 'tʃʰʊpnaː', 'to hide', 'verb', '', 1525],
  ['chhupana', 'chupana|chhupaana', 'छुपाना', 'tʃʰʊpaːnaː', 'to hide (tr)', 'verb', '', 1526],
  ['chhutna', 'chutna|chhootna', 'छूटना', 'tʃʰuːʈnaː', 'to be left behind', 'verb', '', 1527],
  ['khona', 'khonaa', 'खोना', 'kʰoːnaː', 'to lose', 'verb', '', 1528],
  ['paana', 'pana|paanaa', 'पाना', 'paːnaː', 'to obtain', 'verb', '', 1529],

  // ---- Infinitives: feeling, voice, conflict ------------------------------
  ['hasana', 'hansana|hasaana', 'हँसाना', 'ɦə̃saːnaː', 'to make laugh', 'verb', '', 1532],
  ['rulana', 'rulaana|rolana', 'रुलाना', 'rʊlaːnaː', 'to make cry', 'verb', 'filmi', 1533],
  ['muskurana', 'muskuraana|muskrana', 'मुस्कुराना', 'mʊskʊraːnaː', 'to smile', 'verb', 'filmi', 1534],
  ['ghabrana', 'ghabraana|ghabarana', 'घबराना', 'gʰəbraːnaː', 'to panic', 'verb', '', 1535],
  ['sharmana', 'sharmaana|sharamana', 'शरमाना', 'ʃərmaːnaː', 'to feel shy', 'verb', '', 1536],
  ['chahna', 'chaahna|chahnaa', 'चाहना', 'tʃaːɦnaː', 'to want', 'verb', '', 1537],
  ['tarasna', 'tarasnaa|tarsna', 'तरसना', 't̪ərəsnaː', 'to yearn', 'verb', 'filmi', 1538],
  ['tadapna', 'tadapnaa|tarapna', 'तड़पना', 't̪əɽəpnaː', 'to writhe/pine', 'verb', 'filmi', 1539],
  ['machalna', 'machalnaa', 'मचलना', 'mətʃəlnaː', 'to be restless', 'verb', 'filmi', 1540],
  ['sehna', 'sahna|sehnaa', 'सहना', 'səɦnaː', 'to bear', 'verb', '', 1541],
  ['jhelna', 'jhelnaa', 'झेलना', 'dʒʰeːlnaː', 'to endure', 'verb', 'slang', 1542],
  ['kaanpna', 'kanpna|kaanpnaa', 'काँपना', 'kãːpnaː', 'to tremble', 'verb', '', 1543],
  ['chubhna', 'chubhnaa', 'चुभना', 'tʃʊbʰnaː', 'to prick', 'verb', '', 1544],
  ['chillana', 'chillaana|chilana', 'चिल्लाना', 'tʃɪllaːnaː', 'to shout', 'verb', '', 1545],
  ['cheekhna', 'chikhna|cheekhnaa', 'चीखना', 'tʃiːkʰnaː', 'to scream', 'verb', '', 1546],
  ['pukarna', 'pukaarna|pukaarnaa', 'पुकारना', 'pʊkaːrnaː', 'to call out', 'verb', 'filmi', 1547],
  ['ladna', 'ladnaa|larnaa', 'लड़ना', 'ləɽnaː', 'to fight', 'verb', '', 1548],
  ['jhagadna', 'jhagadnaa|jhagarna', 'झगड़ना', 'dʒʰəgəɽnaː', 'to quarrel', 'verb', '', 1549],
  ['dantna', 'daantna|daantnaa', 'डाँटना', 'ɖãːʈnaː', 'to scold', 'verb', '', 1550],
  ['dhamkana', 'dhamkaana|dhamakana', 'धमकाना', 'd̪ʰəmkaːnaː', 'to threaten', 'verb', '', 1551],
  ['thukrana', 'thukraana|thukarana', 'ठुकराना', 'ʈʰʊkraːnaː', 'to reject', 'verb', '', 1552],
  ['satana', 'sataana|stana', 'सताना', 'sət̪aːnaː', 'to torment', 'verb', 'filmi', 1553],
  ['bachna', 'bachnaa', 'बचना', 'bətʃnaː', 'to be saved', 'verb', '', 1554],
  ['bachana', 'bachaana|bchana', 'बचाना', 'bətʃaːnaː', 'to save', 'verb', '', 1555],
  ['sambhalna', 'sambhalnaa|sambhlna', 'संभलना', 'səmbʰəlnaː', 'to steady oneself', 'verb', '', 1556],
  ['bulana', 'bulaana|bulana', 'बुलाना', 'bʊlaːnaː', 'to call', 'verb', '', 1557],
  ['milana', 'milaana|milana', 'मिलाना', 'mɪlaːnaː', 'to mix/introduce', 'verb', '', 1558],
  ['bajana', 'bajaana|bjana', 'बजाना', 'bədʒaːnaː', 'to play (music)', 'verb', '', 1559],
  ['bajna', 'bajnaa', 'बजना', 'bədʒnaː', 'to ring', 'verb', '', 1560],
  ['gaana', 'gana|gaanaa', 'गाना', 'gaːnaː', 'to sing / song', 'verb', 'filmi', 1561],
  ['jhoomna', 'jhumna|jhoomnaa', 'झूमना', 'dʒʰuːmnaː', 'to sway', 'verb', 'filmi', 1562],
  ['machana', 'machaana|mchana', 'मचाना', 'mətʃaːnaː', 'to cause (a ruckus)', 'verb', 'slang', 1563],
  ['bitana', 'bitaana|biitana', 'बिताना', 'bɪt̪aːnaː', 'to spend (time)', 'verb', '', 1564],
  ['gujarna', 'guzarna|gujarnaa', 'गुज़रना', 'gʊzərnaː', 'to pass', 'verb', '', 1565],
  ['lagana', 'lagaana|lgana', 'लगाना', 'ləgaːnaː', 'to apply/attach', 'verb', '', 1566],
  ['bhagana', 'bhagaana|bhgana', 'भगाना', 'bʰəgaːnaː', 'to drive away', 'verb', '', 1567],
  ['thopna', 'thopnaa', 'थोपना', 't̪ʰoːpnaː', 'to impose', 'verb', 'corporate', 1568],

  // ---- Habitual: -ta / -ti / -te ------------------------------------------
  ['bhejta', 'bhejtaa', 'भेजता', 'bʰeːdʒt̪aː', 'sends (m)', 'verb', '', 1570],
  ['bhejti', 'bhejtii', 'भेजती', 'bʰeːdʒt̪iː', 'sends (f)', 'verb', '', 1571],
  ['bhejte', 'bhejtey', 'भेजते', 'bʰeːdʒt̪eː', 'send (pl)', 'verb', '', 1572],
  ['dekhta', 'dekhtaa|dekta', 'देखता', 'd̪eːkʰt̪aː', 'sees (m)', 'verb', '', 1573],
  ['dekhti', 'dekhtii', 'देखती', 'd̪eːkʰt̪iː', 'sees (f)', 'verb', '', 1574],
  ['dekhte', 'dekhtey', 'देखते', 'd̪eːkʰt̪eː', 'see (pl)', 'verb', '', 1575],
  ['sunta', 'suntaa', 'सुनता', 'sʊnt̪aː', 'hears (m)', 'verb', '', 1576],
  ['sunti', 'suntii', 'सुनती', 'sʊnt̪iː', 'hears (f)', 'verb', '', 1577],
  ['sunte', 'suntey', 'सुनते', 'sʊnt̪eː', 'hear (pl)', 'verb', '', 1578],
  ['bolta', 'boltaa', 'बोलता', 'boːlt̪aː', 'speaks (m)', 'verb', '', 1579],
  ['bolti', 'boltii', 'बोलती', 'boːlt̪iː', 'speaks (f)', 'verb', '', 1580],
  ['bolte', 'boltey', 'बोलते', 'boːlt̪eː', 'speak (pl)', 'verb', '', 1581],
  ['likhta', 'likhtaa', 'लिखता', 'lɪkʰt̪aː', 'writes (m)', 'verb', '', 1582],
  ['likhti', 'likhtii', 'लिखती', 'lɪkʰt̪iː', 'writes (f)', 'verb', '', 1583],
  ['likhte', 'likhtey', 'लिखते', 'lɪkʰt̪eː', 'write (pl)', 'verb', '', 1584],
  ['padhta', 'padhtaa|parhta', 'पढ़ता', 'pəɽʰt̪aː', 'reads (m)', 'verb', '', 1585],
  ['padhti', 'padhtii|parhti', 'पढ़ती', 'pəɽʰt̪iː', 'reads (f)', 'verb', '', 1586],
  ['khata', 'khaataa', 'खाता', 'kʰaːt̪aː', 'eats (m)', 'verb', '', 1587],
  ['khati', 'khaatii', 'खाती', 'kʰaːt̪iː', 'eats (f)', 'verb', '', 1588],
  ['khate', 'khaatey', 'खाते', 'kʰaːt̪eː', 'eat (pl)', 'verb', '', 1589],
  ['peeta', 'pita|peetaa', 'पीता', 'piːt̪aː', 'drinks (m)', 'verb', '', 1590],
  ['peeti', 'piti|peetii', 'पीती', 'piːt̪iː', 'drinks (f)', 'verb', '', 1591],
  ['deta', 'detaa', 'देता', 'd̪eːt̪aː', 'gives (m)', 'verb', '', 1592],
  ['deti', 'detii', 'देती', 'd̪eːt̪iː', 'gives (f)', 'verb', '', 1593],
  ['dete', 'detey', 'देते', 'd̪eːt̪eː', 'give (pl)', 'verb', '', 1594],
  ['leta', 'letaa', 'लेता', 'leːt̪aː', 'takes (m)', 'verb', '', 1595],
  ['leti', 'letii', 'लेती', 'leːt̪iː', 'takes (f)', 'verb', '', 1596],
  ['lete', 'letey', 'लेते', 'leːt̪eː', 'take (pl)', 'verb', '', 1597],
  ['milta', 'miltaa', 'मिलता', 'mɪlt̪aː', 'is found (m)', 'verb', '', 1598],
  ['milti', 'miltii', 'मिलती', 'mɪlt̪iː', 'is found (f)', 'verb', '', 1599],
  ['milte', 'miltey', 'मिलते', 'mɪlt̪eː', 'meet (pl)', 'verb', '', 1600],
  ['chalta', 'chaltaa', 'चलता', 'tʃəlt̪aː', 'moves (m)', 'verb', '', 1601],
  ['chalti', 'chaltii', 'चलती', 'tʃəlt̪iː', 'moves (f)', 'verb', '', 1602],
  ['chalte', 'chaltey', 'चलते', 'tʃəlt̪eː', 'move (pl)', 'verb', '', 1603],
  ['samajhta', 'samajhtaa|samajta', 'समझता', 'səmədʒʰt̪aː', 'understands (m)', 'verb', '', 1604],
  ['samajhti', 'samajhtii|samajti', 'समझती', 'səmədʒʰt̪iː', 'understands (f)', 'verb', '', 1605],
  ['sochta', 'sochtaa', 'सोचता', 'soːtʃt̪aː', 'thinks (m)', 'verb', '', 1606],
  ['sochti', 'sochtii', 'सोचती', 'soːtʃt̪iː', 'thinks (f)', 'verb', '', 1607],
  ['sochte', 'sochtey', 'सोचते', 'soːtʃt̪eː', 'think (pl)', 'verb', '', 1608],
  ['banata', 'banaataa', 'बनाता', 'bənaːt̪aː', 'makes (m)', 'verb', '', 1609],
  ['banati', 'banaatii', 'बनाती', 'bənaːt̪iː', 'makes (f)', 'verb', '', 1610],
  ['rakhta', 'rakhtaa', 'रखता', 'rəkʰt̪aː', 'keeps (m)', 'verb', '', 1611],
  ['rakhti', 'rakhtii', 'रखती', 'rəkʰt̪iː', 'keeps (f)', 'verb', '', 1612],
  ['marta', 'martaa', 'मरता', 'mərt̪aː', 'dies (m)', 'verb', '', 1613],
  ['marti', 'martii', 'मरती', 'mərt̪iː', 'dies (f)', 'verb', '', 1614],
  ['rehta', 'rahta|rehtaa', 'रहता', 'rəɦt̪aː', 'stays (m)', 'verb', '', 1615],
  ['rehti', 'rahti|rehtii', 'रहती', 'rəɦt̪iː', 'stays (f)', 'verb', '', 1616],
  ['rehte', 'rahte|rehtey', 'रहते', 'rəɦt̪eː', 'stay (pl)', 'verb', '', 1617],
  ['aata', 'ata|aataa', 'आता', 'aːt̪aː', 'comes (m)', 'verb', '', 1618],
  ['aati', 'ati|aatii', 'आती', 'aːt̪iː', 'comes (f)', 'verb', '', 1619],
  ['aate', 'ate|aatey', 'आते', 'aːt̪eː', 'come (pl)', 'verb', '', 1620],
  ['jati', 'jaati|jaatii', 'जाती', 'dʒaːt̪iː', 'goes (f)', 'verb', '', 1621],
  ['jate', 'jaate|jaatey', 'जाते', 'dʒaːt̪eː', 'go (pl)', 'verb', '', 1622],
  ['lagti', 'lagtii', 'लगती', 'ləgt̪iː', 'seems (f)', 'verb', '', 1623],
  ['lagte', 'lagtey', 'लगते', 'ləgt̪eː', 'seem (pl)', 'verb', '', 1624],
  ['jeetta', 'jitta|jeettaa', 'जीतता', 'dʒiːt̪t̪aː', 'wins (m)', 'verb', '', 1625],
  ['hasta', 'hansta|hastaa', 'हँसता', 'ɦə̃st̪aː', 'laughs (m)', 'verb', '', 1626],
  ['hasti', 'hansti|hastii', 'हँसती', 'ɦə̃st̪iː', 'laughs (f)', 'verb', '', 1627],
  ['rota', 'rotaa', 'रोता', 'roːt̪aː', 'cries (m)', 'verb', '', 1628],
  ['rote', 'rotey', 'रोते', 'roːt̪eː', 'cry (pl)', 'verb', '', 1629],
  ['sota', 'sotaa', 'सोता', 'soːt̪aː', 'sleeps (m)', 'verb', '', 1630],
  ['soti', 'sotii', 'सोती', 'soːt̪iː', 'sleeps (f)', 'verb', '', 1631],
  ['uthta', 'uthtaa', 'उठता', 'ʊʈʰt̪aː', 'rises (m)', 'verb', '', 1632],
  ['uthti', 'uthtii', 'उठती', 'ʊʈʰt̪iː', 'rises (f)', 'verb', '', 1633],
  ['baithta', 'bethta|baithtaa', 'बैठता', 'bɛːʈʰt̪aː', 'sits (m)', 'verb', '', 1634],
  ['baithte', 'bethte|baithtey', 'बैठते', 'bɛːʈʰt̪eː', 'sit (pl)', 'verb', '', 1635],
  ['rukta', 'ruktaa', 'रुकता', 'rʊkt̪aː', 'stops (m)', 'verb', '', 1636],
  ['rukti', 'ruktii', 'रुकती', 'rʊkt̪iː', 'stops (f)', 'verb', '', 1637],
  ['nikalta', 'nikaltaa', 'निकलता', 'nɪkəlt̪aː', 'goes out (m)', 'verb', '', 1638],
  ['nikalti', 'nikaltii', 'निकलती', 'nɪkəlt̪iː', 'goes out (f)', 'verb', '', 1639],
  ['chahta', 'chaahta|chahtaa', 'चाहता', 'tʃaːɦt̪aː', 'wants (m)', 'verb', '', 1640],
  ['chahti', 'chaahti|chahtii', 'चाहती', 'tʃaːɦt̪iː', 'wants (f)', 'verb', '', 1641],
  ['chahte', 'chaahte|chahtey', 'चाहते', 'tʃaːɦt̪eː', 'want (pl)', 'verb', '', 1642],
  ['jaanta', 'janta|jaantaa', 'जानता', 'dʒaːnt̪aː', 'knows (m)', 'verb', '', 1643],
  ['jaanti', 'janti|jaantii', 'जानती', 'dʒaːnt̪iː', 'knows (f)', 'verb', '', 1644],
  ['maanta', 'manta|maantaa', 'मानता', 'maːnt̪aː', 'believes (m)', 'verb', '', 1645],
  ['bhoolta', 'bhulta|bhooltaa', 'भूलता', 'bʰuːlt̪aː', 'forgets (m)', 'verb', '', 1646],
  ['bhoolti', 'bhulti|bhooltii', 'भूलती', 'bʰuːlt̪iː', 'forgets (f)', 'verb', '', 1647],
  ['batata', 'bataataa', 'बताता', 'bət̪aːt̪aː', 'tells (m)', 'verb', '', 1648],
  ['batati', 'bataatii', 'बताती', 'bət̪aːt̪iː', 'tells (f)', 'verb', '', 1649],
  ['gata', 'gaataa', 'गाता', 'gaːt̪aː', 'sings (m)', 'verb', 'filmi', 1650],
  ['gati', 'gaatii', 'गाती', 'gaːt̪iː', 'sings (f)', 'verb', 'filmi', 1651],
  ['nachta', 'naachta|naachtaa', 'नाचता', 'naːtʃt̪aː', 'dances (m)', 'verb', '', 1652],
  ['nachti', 'naachti|naachtii', 'नाचती', 'naːtʃt̪iː', 'dances (f)', 'verb', '', 1653],
  ['sikhta', 'seekhta|sikhtaa', 'सीखता', 'siːkʰt̪aː', 'learns (m)', 'verb', '', 1654],
  ['pakadta', 'pakadtaa|pakarta', 'पकड़ता', 'pəkəɽt̪aː', 'catches (m)', 'verb', '', 1655],
  ['daudta', 'daudtaa|dorta', 'दौड़ता', 'd̪ɔːɽt̪aː', 'runs (m)', 'verb', '', 1656],
  ['ghumta', 'ghoomta|ghumtaa', 'घूमता', 'gʰuːmt̪aː', 'roams (m)', 'verb', '', 1657],
  ['dikhata', 'dikhaataa', 'दिखाता', 'd̪ɪkʰaːt̪aː', 'shows (m)', 'verb', '', 1658],
  ['dikhati', 'dikhaatii', 'दिखाती', 'd̪ɪkʰaːt̪iː', 'shows (f)', 'verb', '', 1659],

  // ---- Perfective: -a / -i / -e -------------------------------------------
  ['bheja', 'bhejaa', 'भेजा', 'bʰeːdʒaː', 'sent (m)', 'verb', '', 1665],
  ['bheji', 'bhejii', 'भेजी', 'bʰeːdʒiː', 'sent (f)', 'verb', '', 1666],
  ['bheje', 'bhejey', 'भेजे', 'bʰeːdʒeː', 'sent (pl)', 'verb', '', 1667],
  ['dekhi', 'dekhii', 'देखी', 'd̪eːkʰiː', 'saw (f)', 'verb', '', 1668],
  ['dekhe', 'dekhey', 'देखे', 'd̪eːkʰeː', 'saw (pl)', 'verb', '', 1669],
  ['suna', 'sunaa', 'सुना', 'sʊnaː', 'heard (m)', 'verb', '', 1670],
  ['suni', 'sunii', 'सुनी', 'sʊniː', 'heard (f)', 'verb', '', 1671],
  ['sune', 'suney', 'सुने', 'sʊneː', 'heard (pl)', 'verb', '', 1672],
  ['bola', 'bolaa', 'बोला', 'boːlaː', 'spoke (m)', 'verb', '', 1673],
  ['boli', 'bolii', 'बोली', 'boːliː', 'spoke (f)', 'verb', '', 1674],
  ['bole', 'boley', 'बोले', 'boːleː', 'spoke (pl)', 'verb', '', 1675],
  ['likha', 'likhaa', 'लिखा', 'lɪkʰaː', 'wrote (m)', 'verb', '', 1676],
  ['likhi', 'likhii', 'लिखी', 'lɪkʰiː', 'wrote (f)', 'verb', '', 1677],
  ['likhe', 'likhey', 'लिखे', 'lɪkʰeː', 'wrote (pl)', 'verb', '', 1678],
  ['padha', 'padhaa|parha', 'पढ़ा', 'pəɽʰaː', 'read (m)', 'verb', '', 1679],
  ['padhi', 'padhii|parhi', 'पढ़ी', 'pəɽʰiː', 'read (f)', 'verb', '', 1680],
  ['khaya', 'khayaa|khaaya', 'खाया', 'kʰaːjaː', 'ate (m)', 'verb', '', 1681],
  ['khayi', 'khai|khaayi', 'खाई', 'kʰaːiː', 'ate (f)', 'verb', '', 1682],
  ['khaye', 'khae|khaaye', 'खाए', 'kʰaːeː', 'ate (pl)', 'verb', '', 1683],
  ['piya', 'piyaa|pia', 'पिया', 'pɪjaː', 'drank (m)', 'verb', '', 1684],
  ['piye', 'piyey|pie', 'पिये', 'pɪjeː', 'drank (pl)', 'verb', '', 1685],
  ['diye', 'diyey|die', 'दिये', 'd̪ɪjeː', 'gave (pl)', 'verb', '', 1686],
  ['mili', 'milii', 'मिली', 'mɪliː', 'got/met (f)', 'verb', '', 1687],
  ['mile', 'miley', 'मिले', 'mɪleː', 'got/met (pl)', 'verb', '', 1688],
  ['chala', 'chalaa', 'चला', 'tʃəlaː', 'walked (m)', 'verb', '', 1689],
  ['chali', 'chalii', 'चली', 'tʃəliː', 'walked (f)', 'verb', '', 1690],
  ['chale', 'chaley', 'चले', 'tʃəleː', 'walked (pl)', 'verb', '', 1691],
  ['samjha', 'samjhaa|samja', 'समझा', 'səmdʒʰaː', 'understood (m)', 'verb', '', 1692],
  ['samjhi', 'samjhii|samji', 'समझी', 'səmdʒʰiː', 'understood (f)', 'verb', '', 1693],
  ['samjhe', 'samjhey|samje', 'समझे', 'səmdʒʰeː', 'understood (pl)', 'verb', '', 1694],
  ['socha', 'sochaa', 'सोचा', 'soːtʃaː', 'thought (m)', 'verb', '', 1695],
  ['sochi', 'sochii', 'सोची', 'soːtʃiː', 'thought (f)', 'verb', '', 1696],
  ['banaya', 'banayaa|bnaya', 'बनाया', 'bənaːjaː', 'made (m)', 'verb', '', 1697],
  ['banayi', 'banai|banaayi', 'बनाई', 'bənaːiː', 'made (f)', 'verb', '', 1698],
  ['banaye', 'banae|banaaye', 'बनाए', 'bənaːeː', 'made (pl)', 'verb', '', 1699],
  ['rakha', 'rakhaa', 'रखा', 'rəkʰaː', 'kept (m)', 'verb', '', 1700],
  ['rakhi', 'rakhii', 'रखी', 'rəkʰiː', 'kept (f)', 'verb', '', 1701],
  ['mara', 'maraa', 'मरा', 'məraː', 'died (m)', 'verb', '', 1702],
  ['mari', 'marii', 'मरी', 'məriː', 'died (f)', 'verb', '', 1703],
  ['aaye', 'aae|aayey', 'आए', 'aːeː', 'came (pl)', 'verb', '', 1704],
  ['gaye', 'gae|gayey', 'गए', 'gəjeː', 'went (pl)', 'verb', '', 1705],
  ['jeeta', 'jita|jeetaa', 'जीता', 'dʒiːt̪aː', 'won (m)', 'verb', '', 1706],
  ['jeeti', 'jiti|jeetii', 'जीती', 'dʒiːt̪iː', 'won (f)', 'verb', '', 1707],
  ['hara', 'haaraa|haara', 'हारा', 'ɦaːraː', 'lost (m)', 'verb', '', 1708],
  ['hari', 'haarii|haari', 'हारी', 'ɦaːriː', 'lost (f)', 'verb', '', 1709],
  ['sikha', 'seekha|sikhaa', 'सीखा', 'siːkʰaː', 'learnt (m)', 'verb', '', 1710],
  ['bataya', 'batayaa|btaya', 'बताया', 'bət̪aːjaː', 'told (m)', 'verb', '', 1711],
  ['batayi', 'batai|bataayi', 'बताई', 'bət̪aːiː', 'told (f)', 'verb', '', 1712],
  ['dikhaya', 'dikhayaa', 'दिखाया', 'd̪ɪkʰaːjaː', 'showed (m)', 'verb', '', 1713],
  ['dikhayi', 'dikhai|dikhaayi', 'दिखाई', 'd̪ɪkʰaːiː', 'showed (f)', 'verb', '', 1714],
  ['utha', 'uthaa', 'उठा', 'ʊʈʰaː', 'rose (m)', 'verb', '', 1715],
  ['uthi', 'uthii', 'उठी', 'ʊʈʰiː', 'rose (f)', 'verb', '', 1716],
  ['ruka', 'rukaa', 'रुका', 'rʊkaː', 'stopped (m)', 'verb', '', 1717],
  ['ruki', 'rukii', 'रुकी', 'rʊkiː', 'stopped (f)', 'verb', '', 1718],
  ['nikla', 'niklaa|nikala', 'निकला', 'nɪklaː', 'came out (m)', 'verb', '', 1719],
  ['nikli', 'niklii|nikali', 'निकली', 'nɪkliː', 'came out (f)', 'verb', '', 1720],
  ['pahucha', 'pahuncha|pahuchaa', 'पहुँचा', 'pəɦʊ̃tʃaː', 'arrived (m)', 'verb', '', 1721],
  ['pahuchi', 'pahunchi|pahuchii', 'पहुँची', 'pəɦʊ̃tʃiː', 'arrived (f)', 'verb', '', 1722],
  ['laya', 'layaa|laaya', 'लाया', 'laːjaː', 'brought (m)', 'verb', '', 1723],
  ['layi', 'lai|laayi', 'लाई', 'laːiː', 'brought (f)', 'verb', '', 1724],
  ['bhoola', 'bhula|bhoolaa', 'भूला', 'bʰuːlaː', 'forgot (m)', 'verb', '', 1725],
  ['khoya', 'khoyaa', 'खोया', 'kʰoːjaː', 'lost (m)', 'verb', 'filmi', 1726],
  ['khoyi', 'khoi|khoyii', 'खोई', 'kʰoːiː', 'lost (f)', 'verb', 'filmi', 1727],
  ['chhoda', 'chhodaa|chora', 'छोड़ा', 'tʃʰoːɽaː', 'left (m)', 'verb', '', 1728],
  ['chhodi', 'chhodii|chori', 'छोड़ी', 'tʃʰoːɽiː', 'left (f)', 'verb', '', 1729],
  ['toda', 'todaa|tora', 'तोड़ा', 't̪oːɽaː', 'broke (m)', 'verb', '', 1730],
  ['badla', 'badlaa|badala', 'बदला', 'bəd̪laː', 'changed (m)', 'verb', '', 1731],
  ['bana', 'banaa', 'बना', 'bənaː', 'became/made (m)', 'verb', '', 1732],
  ['bani', 'banii', 'बनी', 'bəniː', 'became/made (f)', 'verb', '', 1733],
  ['pakda', 'pakdaa|pakada', 'पकड़ा', 'pəkɽaː', 'caught (m)', 'verb', '', 1734],
  ['dauda', 'daudaa|dora', 'दौड़ा', 'd̪ɔːɽaː', 'ran (m)', 'verb', '', 1735],
  ['jaga', 'jagaa|jaaga', 'जागा', 'dʒaːgaː', 'woke (m)', 'verb', '', 1736],
  ['thaka', 'thakaa', 'थका', 't̪ʰəkaː', 'tired (m)', 'verb', '', 1737],
  ['hansa', 'hasa|hansaa', 'हँसा', 'ɦə̃saː', 'laughed (m)', 'verb', '', 1738],
  ['roya', 'royaa', 'रोया', 'roːjaː', 'cried (m)', 'verb', '', 1739],
  ['soya', 'soyaa', 'सोया', 'soːjaː', 'slept (m)', 'verb', '', 1740],
  ['jala', 'jalaa', 'जला', 'dʒəlaː', 'burnt (m)', 'verb', '', 1741],
  ['khula', 'khulaa', 'खुला', 'kʰʊlaː', 'opened (m)', 'verb', '', 1742],
  ['gira', 'giraa', 'गिरा', 'gɪraː', 'fell (m)', 'verb', '', 1743],

  // ---- Future: -ega / -egi / -enge ----------------------------------------
  ['bhejega', 'bhejegaa', 'भेजेगा', 'bʰeːdʒeːgaː', 'will send (m)', 'verb', '', 1750],
  ['bhejegi', 'bhejegii', 'भेजेगी', 'bʰeːdʒeːgiː', 'will send (f)', 'verb', '', 1751],
  ['bhejenge', 'bhejengey', 'भेजेंगे', 'bʰeːdʒẽːgeː', 'will send (pl)', 'verb', '', 1752],
  ['karega', 'karegaa|kregaa', 'करेगा', 'kəreːgaː', 'will do (m)', 'verb', '', 1753],
  ['karegi', 'karegii', 'करेगी', 'kəreːgiː', 'will do (f)', 'verb', '', 1754],
  ['karenge', 'karengey|krenge', 'करेंगे', 'kərẽːgeː', 'will do (pl)', 'verb', '', 1755],
  ['kare', 'karey|kre', 'करे', 'kəreː', 'may do', 'verb', '', 1756],
  ['jayega', 'jaayega|jayegaa', 'जाएगा', 'dʒaːeːgaː', 'will go (m)', 'verb', '', 1757],
  ['jayegi', 'jaayegi|jayegii', 'जाएगी', 'dʒaːeːgiː', 'will go (f)', 'verb', '', 1758],
  ['jayenge', 'jaayenge|jayengey', 'जाएँगे', 'dʒaːẽːgeː', 'will go (pl)', 'verb', '', 1759],
  ['aayega', 'ayega|aayegaa', 'आएगा', 'aːeːgaː', 'will come (m)', 'verb', '', 1760],
  ['aayegi', 'ayegi|aayegii', 'आएगी', 'aːeːgiː', 'will come (f)', 'verb', '', 1761],
  ['aayenge', 'ayenge|aayengey', 'आएँगे', 'aːẽːgeː', 'will come (pl)', 'verb', '', 1762],
  ['dega', 'degaa', 'देगा', 'd̪eːgaː', 'will give (m)', 'verb', '', 1763],
  ['degi', 'degii', 'देगी', 'd̪eːgiː', 'will give (f)', 'verb', '', 1764],
  ['denge', 'dengey', 'देंगे', 'd̪ẽːgeː', 'will give (pl)', 'verb', '', 1765],
  ['lega', 'legaa', 'लेगा', 'leːgaː', 'will take (m)', 'verb', '', 1766],
  ['legi', 'legii', 'लेगी', 'leːgiː', 'will take (f)', 'verb', '', 1767],
  ['lenge', 'lengey', 'लेंगे', 'lẽːgeː', 'will take (pl)', 'verb', '', 1768],
  ['dekhega', 'dekhegaa', 'देखेगा', 'd̪eːkʰeːgaː', 'will see (m)', 'verb', '', 1769],
  ['dekhegi', 'dekhegii', 'देखेगी', 'd̪eːkʰeːgiː', 'will see (f)', 'verb', '', 1770],
  ['dekhenge', 'dekhengey', 'देखेंगे', 'd̪eːkʰẽːgeː', 'will see (pl)', 'verb', '', 1771],
  ['sunega', 'sunegaa', 'सुनेगा', 'sʊneːgaː', 'will hear (m)', 'verb', '', 1772],
  ['sunegi', 'sunegii', 'सुनेगी', 'sʊneːgiː', 'will hear (f)', 'verb', '', 1773],
  ['sunenge', 'sunengey', 'सुनेंगे', 'sʊnẽːgeː', 'will hear (pl)', 'verb', '', 1774],
  ['bolega', 'bolegaa', 'बोलेगा', 'boːleːgaː', 'will speak (m)', 'verb', '', 1775],
  ['bolenge', 'bolengey', 'बोलेंगे', 'boːlẽːgeː', 'will speak (pl)', 'verb', '', 1776],
  ['milega', 'milegaa', 'मिलेगा', 'mɪleːgaː', 'will be found (m)', 'verb', '', 1777],
  ['milegi', 'milegii', 'मिलेगी', 'mɪleːgiː', 'will be found (f)', 'verb', '', 1778],
  ['milenge', 'milengey', 'मिलेंगे', 'mɪlẽːgeː', 'will meet (pl)', 'verb', '', 1779],
  ['chalega', 'chalegaa', 'चलेगा', 'tʃəleːgaː', 'will work/move (m)', 'verb', '', 1780],
  ['chalegi', 'chalegii', 'चलेगी', 'tʃəleːgiː', 'will work/move (f)', 'verb', '', 1781],
  ['chalenge', 'chalengey', 'चलेंगे', 'tʃəlẽːgeː', 'will move (pl)', 'verb', '', 1782],
  ['rahega', 'rahegaa|rhega', 'रहेगा', 'rəɦeːgaː', 'will stay (m)', 'verb', '', 1783],
  ['rahegi', 'rahegii', 'रहेगी', 'rəɦeːgiː', 'will stay (f)', 'verb', '', 1784],
  ['rahenge', 'rahengey', 'रहेंगे', 'rəɦẽːgeː', 'will stay (pl)', 'verb', '', 1785],
  ['lagega', 'lagegaa', 'लगेगा', 'ləgeːgaː', 'will seem (m)', 'verb', '', 1786],
  ['lagegi', 'lagegii', 'लगेगी', 'ləgeːgiː', 'will seem (f)', 'verb', '', 1787],
  ['samjhega', 'samjhegaa', 'समझेगा', 'səmdʒʰeːgaː', 'will understand (m)', 'verb', '', 1788],
  ['samjhenge', 'samjhengey', 'समझेंगे', 'səmdʒʰẽːgeː', 'will understand (pl)', 'verb', '', 1789],
  ['sochega', 'sochegaa', 'सोचेगा', 'soːtʃeːgaː', 'will think (m)', 'verb', '', 1790],
  ['sochenge', 'sochengey', 'सोचेंगे', 'soːtʃẽːgeː', 'will think (pl)', 'verb', '', 1791],
  ['likhega', 'likhegaa', 'लिखेगा', 'lɪkʰeːgaː', 'will write (m)', 'verb', '', 1792],
  ['khayega', 'khaayega|khayegaa', 'खाएगा', 'kʰaːeːgaː', 'will eat (m)', 'verb', '', 1793],
  ['khayenge', 'khaayenge', 'खाएँगे', 'kʰaːẽːgeː', 'will eat (pl)', 'verb', '', 1794],
  ['payega', 'paayega|payegaa', 'पाएगा', 'paːeːgaː', 'will be able (m)', 'verb', '', 1795],
  ['sakega', 'sakegaa', 'सकेगा', 'səkeːgaː', 'will be able (m)', 'verb', '', 1796],
  ['banayega', 'banaayega', 'बनाएगा', 'bənaːeːgaː', 'will make (m)', 'verb', '', 1797],
  ['batayega', 'bataayega', 'बताएगा', 'bət̪aːeːgaː', 'will tell (m)', 'verb', '', 1798],
  ['jeetega', 'jitega|jeetegaa', 'जीतेगा', 'dʒiːt̪eːgaː', 'will win (m)', 'verb', '', 1799],
  ['harega', 'haarega|haregaa', 'हारेगा', 'ɦaːreːgaː', 'will lose (m)', 'verb', '', 1800],
  ['marega', 'maregaa', 'मरेगा', 'məreːgaː', 'will die (m)', 'verb', '', 1801],
  ['uthega', 'uthegaa', 'उठेगा', 'ʊʈʰeːgaː', 'will rise (m)', 'verb', '', 1802],
  ['baithega', 'bethega|baithegaa', 'बैठेगा', 'bɛːʈʰeːgaː', 'will sit (m)', 'verb', '', 1803],
  ['rukega', 'rukegaa', 'रुकेगा', 'rʊkeːgaː', 'will stop (m)', 'verb', '', 1804],
  ['niklega', 'niklegaa|nikalega', 'निकलेगा', 'nɪkleːgaː', 'will come out (m)', 'verb', '', 1805],
  ['pahuchega', 'pahunchega', 'पहुँचेगा', 'pəɦʊ̃tʃeːgaː', 'will arrive (m)', 'verb', '', 1806],
  ['badlega', 'badlegaa|badalega', 'बदलेगा', 'bəd̪leːgaː', 'will change (m)', 'verb', '', 1807],
  ['dikhega', 'dikhegaa', 'दिखेगा', 'd̪ɪkʰeːgaː', 'will show/appear (m)', 'verb', '', 1808],
  ['khulega', 'khulegaa', 'खुलेगा', 'kʰʊleːgaː', 'will open (m)', 'verb', '', 1809],
  ['girega', 'giregaa', 'गिरेगा', 'gɪreːgaː', 'will fall (m)', 'verb', '', 1810],

  // ---- Future first person: -unga / -ungi ---------------------------------
  ['bhejunga', 'bhejoonga|bhejunga', 'भेजूँगा', 'bʰeːdʒũːgaː', 'will send (m, 1sg)', 'verb', '', 1815],
  ['dekhunga', 'dekhoonga|dekhunga', 'देखूँगा', 'd̪eːkʰũːgaː', 'will see (m, 1sg)', 'verb', '', 1816],
  ['dekhungi', 'dekhoongi', 'देखूँगी', 'd̪eːkʰũːgiː', 'will see (f, 1sg)', 'verb', '', 1817],
  ['sununga', 'sunoonga', 'सुनूँगा', 'sʊnũːgaː', 'will hear (m, 1sg)', 'verb', '', 1818],
  ['sunungi', 'sunoongi', 'सुनूँगी', 'sʊnũːgiː', 'will hear (f, 1sg)', 'verb', '', 1819],
  ['bolunga', 'boloonga', 'बोलूँगा', 'boːlũːgaː', 'will speak (m, 1sg)', 'verb', '', 1820],
  ['dunga', 'doonga|dungaa', 'दूँगा', 'd̪ũːgaː', 'will give (m, 1sg)', 'verb', '', 1821],
  ['lunga', 'loonga|lungaa', 'लूँगा', 'lũːgaː', 'will take (m, 1sg)', 'verb', '', 1822],
  ['karungi', 'karoongi|krungi', 'करूँगी', 'kərũːgiː', 'will do (f, 1sg)', 'verb', '', 1823],
  ['jaungi', 'jaoongi|jaungii', 'जाऊँगी', 'dʒaːũːgiː', 'will go (f, 1sg)', 'verb', '', 1824],
  ['aaunga', 'aoonga|aunga', 'आऊँगा', 'aːũːgaː', 'will come (m, 1sg)', 'verb', '', 1825],
  ['aaungi', 'aoongi|aungi', 'आऊँगी', 'aːũːgiː', 'will come (f, 1sg)', 'verb', '', 1826],
  ['khaunga', 'khaoonga', 'खाऊँगा', 'kʰaːũːgaː', 'will eat (m, 1sg)', 'verb', '', 1827],
  ['piyunga', 'peeyunga|piunga', 'पीऊँगा', 'piːũːgaː', 'will drink (m, 1sg)', 'verb', '', 1828],
  ['likhunga', 'likhoonga', 'लिखूँगा', 'lɪkʰũːgaː', 'will write (m, 1sg)', 'verb', '', 1829],
  ['milunga', 'miloonga', 'मिलूँगा', 'mɪlũːgaː', 'will meet (m, 1sg)', 'verb', '', 1830],
  ['rahunga', 'rahoonga|rhunga', 'रहूँगा', 'rəɦũːgaː', 'will stay (m, 1sg)', 'verb', '', 1831],
  ['sochunga', 'sochoonga', 'सोचूँगा', 'soːtʃũːgaː', 'will think (m, 1sg)', 'verb', '', 1832],
  ['samjhunga', 'samjhoonga', 'समझूँगा', 'səmdʒʰũːgaː', 'will understand (m, 1sg)', 'verb', '', 1833],
  ['banaunga', 'banaoonga', 'बनाऊँगा', 'bənaːũːgaː', 'will make (m, 1sg)', 'verb', '', 1834],
  ['bataunga', 'bataoonga', 'बताऊँगा', 'bət̪aːũːgaː', 'will tell (m, 1sg)', 'verb', '', 1835],
  ['laaunga', 'laoonga|launga', 'लाऊँगा', 'laːũːgaː', 'will bring (m, 1sg)', 'verb', '', 1836],
  ['chalunga', 'chaloonga', 'चलूँगा', 'tʃəlũːgaː', 'will move (m, 1sg)', 'verb', '', 1837],
  ['marunga', 'maroonga', 'मरूँगा', 'mərũːgaː', 'will die (m, 1sg)', 'verb', '', 1838],
  ['jeetunga', 'jitunga|jeetoonga', 'जीतूँगा', 'dʒiːt̪ũːgaː', 'will win (m, 1sg)', 'verb', '', 1839],

  // ---- Imperative and subjunctive: bare stem, -o, -un --------------------
  ['bhej', 'bhejh', 'भेज', 'bʰeːdʒ', 'send (stem)', 'verb', '', 1845],
  ['likh', 'likhh', 'लिख', 'lɪkʰ', 'write (stem)', 'verb', '', 1846],
  ['rakh', 'rakhh', 'रख', 'rəkʰ', 'keep (stem)', 'verb', '', 1847],
  ['mil', 'mill', 'मिल', 'mɪl', 'meet (stem)', 'verb', '', 1848],
  ['ruk', 'rukk', 'रुक', 'rʊk', 'stop (stem)', 'verb', '', 1849],
  ['chhod', 'chod|chhor', 'छोड़', 'tʃʰoːɽ', 'leave (stem)', 'verb', '', 1850],
  ['tod', 'tor|todd', 'तोड़', 't̪oːɽ', 'break (stem)', 'verb', '', 1851],
  ['uth', 'uthh', 'उठ', 'ʊʈʰ', 'get up (stem)', 'verb', '', 1852],
  ['baith', 'beth|baithh', 'बैठ', 'bɛːʈʰ', 'sit (stem)', 'verb', '', 1853],
  ['aa', 'aaa', 'आ', 'aː', 'come (stem)', 'verb', '', 1854],
  ['ja', 'jaa', 'जा', 'dʒaː', 'go (stem)', 'verb', '', 1855],
  ['kha', 'khaa', 'खा', 'kʰaː', 'eat (stem)', 'verb', '', 1856],
  ['pee', 'pi|pii', 'पी', 'piː', 'drink (stem)', 'verb', '', 1857],
  ['de', 'dey', 'दे', 'd̪eː', 'give (stem)', 'verb', '', 1858],
  ['le', 'ley', 'ले', 'leː', 'take (stem)', 'verb', '', 1859],
  ['bhool', 'bhul|bhooll', 'भूल', 'bʰuːl', 'forget (stem)', 'verb', '', 1860],
  ['pakad', 'pakar|pakadd', 'पकड़', 'pəkəɽ', 'catch (stem)', 'verb', '', 1861],
  ['nikal', 'nikall', 'निकल', 'nɪkəl', 'get out (stem)', 'verb', 'slang', 1862],
  ['ban', 'bann', 'बन', 'bən', 'become (stem)', 'verb', '', 1863],
  ['maan', 'man|maann', 'मान', 'maːn', 'accept (stem)', 'verb', '', 1864],
  ['sambhal', 'sambhall', 'संभल', 'səmbʰəl', 'steady yourself (stem)', 'verb', '', 1865],
  ['bata', 'bataa|bta', 'बता', 'bət̪aː', 'tell (imperative)', 'verb', '', 1866],
  ['dikha', 'dikhaa', 'दिखा', 'd̪ɪkʰaː', 'show (imperative)', 'verb', '', 1867],
  ['bhejo', 'bhejoo', 'भेजो', 'bʰeːdʒoː', 'send (imperative)', 'verb', '', 1868],
  ['likho', 'likhoo', 'लिखो', 'lɪkʰoː', 'write (imperative)', 'verb', '', 1869],
  ['socho', 'sochoo', 'सोचो', 'soːtʃoː', 'think (imperative)', 'verb', '', 1870],
  ['samjho', 'samjhoo|samjo', 'समझो', 'səmdʒʰoː', 'understand (imperative)', 'verb', '', 1871],
  ['rakho', 'rakhoo', 'रखो', 'rəkʰoː', 'keep (imperative)', 'verb', '', 1872],
  ['jao', 'jaao|jaoo', 'जाओ', 'dʒaːoː', 'go (imperative)', 'verb', '', 1873],
  ['aao', 'aoo|aaoo', 'आओ', 'aːoː', 'come (imperative)', 'verb', '', 1874],
  ['khao', 'khaao', 'खाओ', 'kʰaːoː', 'eat (imperative)', 'verb', '', 1875],
  ['piyo', 'piyoo|pio', 'पियो', 'pɪjoː', 'drink (imperative)', 'verb', '', 1876],
  ['lo', 'loo', 'लो', 'loː', 'take (imperative)', 'verb', '', 1877],
  ['bolo', 'boloo', 'बोलो', 'boːloː', 'speak (imperative)', 'verb', '', 1878],
  ['milo', 'miloo', 'मिलो', 'mɪloː', 'meet (imperative)', 'verb', '', 1879],
  ['ruko', 'rukoo', 'रुको', 'rʊkoː', 'stop (imperative)', 'verb', '', 1880],
  ['batao', 'bataao|btao', 'बताओ', 'bət̪aːoː', 'tell me (imperative)', 'verb', '', 1881],
  ['dikhao', 'dikhaao', 'दिखाओ', 'd̪ɪkʰaːoː', 'show (imperative)', 'verb', '', 1882],
  ['chhodo', 'chodo|chhoro', 'छोड़ो', 'tʃʰoːɽoː', 'leave it (imperative)', 'verb', 'slang', 1883],
  ['utho', 'uthoo', 'उठो', 'ʊʈʰoː', 'get up (imperative)', 'verb', '', 1884],
  ['baitho', 'betho|baithoo', 'बैठो', 'bɛːʈʰoː', 'sit (imperative)', 'verb', '', 1885],
  ['sambhalo', 'sambhaloo', 'संभलो', 'səmbʰəloː', 'be careful (imperative)', 'verb', '', 1886],
  ['bhoolo', 'bhulo|bhooloo', 'भूलो', 'bʰuːloː', 'forget (imperative)', 'verb', '', 1887],
  ['banao', 'banaao|bnao', 'बनाओ', 'bənaːoː', 'make (imperative)', 'verb', '', 1888],
  ['bulao', 'bulaao', 'बुलाओ', 'bʊlaːoː', 'call (imperative)', 'verb', '', 1889],
  ['sunao', 'sunaao', 'सुनाओ', 'sʊnaːoː', 'tell/recite (imperative)', 'verb', '', 1890],
  ['gao', 'gaao|gaoo', 'गाओ', 'gaːoː', 'sing (imperative)', 'verb', 'filmi', 1891],
  ['nacho', 'naacho|nachoo', 'नाचो', 'naːtʃoː', 'dance (imperative)', 'verb', '', 1892],
  ['jeeto', 'jito|jeetoo', 'जीतो', 'dʒiːt̪oː', 'win (imperative)', 'verb', '', 1893],
  ['bhago', 'bhaago|bhagoo', 'भागो', 'bʰaːgoː', 'run (imperative)', 'verb', 'slang', 1894],
  ['hato', 'hatoo|hutto', 'हटो', 'ɦəʈoː', 'move aside (imperative)', 'verb', 'slang', 1895],
  ['bhejun', 'bhejoon|bheju', 'भेजूँ', 'bʰeːdʒũː', 'should I send', 'verb', '', 1896],
  ['dekhun', 'dekhoon|dekhu', 'देखूँ', 'd̪eːkʰũː', 'should I see', 'verb', '', 1897],
  ['sunun', 'sunoon|sunu', 'सुनूँ', 'sʊnũː', 'should I listen', 'verb', '', 1898],
  ['bolun', 'boloon|bolu', 'बोलूँ', 'boːlũː', 'should I speak', 'verb', '', 1899],
  ['dun', 'doon|du', 'दूँ', 'd̪ũː', 'should I give', 'verb', '', 1900],
  ['lun', 'loon|lu', 'लूँ', 'lũː', 'should I take', 'verb', '', 1901],
  ['jaun', 'jaoon|jau', 'जाऊँ', 'dʒaːũː', 'should I go', 'verb', '', 1902],
  ['aaun', 'aoon|aau', 'आऊँ', 'aːũː', 'should I come', 'verb', '', 1903],
  ['khaun', 'khaoon|khau', 'खाऊँ', 'kʰaːũː', 'should I eat', 'verb', '', 1904],
  ['likhun', 'likhoon|likhu', 'लिखूँ', 'lɪkʰũː', 'should I write', 'verb', '', 1905],
  ['samjhun', 'samjhoon|samjhu', 'समझूँ', 'səmdʒʰũː', 'should I understand', 'verb', '', 1906],
  ['sochun', 'sochoon|sochu', 'सोचूँ', 'soːtʃũː', 'should I think', 'verb', '', 1907],
  ['milun', 'miloon|milu', 'मिलूँ', 'mɪlũː', 'should I meet', 'verb', '', 1908],
  ['rahun', 'rahoon|rahu', 'रहूँ', 'rəɦũː', 'should I stay', 'verb', '', 1909],
  ['bataun', 'bataoon|batau', 'बताऊँ', 'bət̪aːũː', 'should I tell', 'verb', '', 1910],
  ['banaun', 'banaoon|banau', 'बनाऊँ', 'bənaːũː', 'should I make', 'verb', '', 1911],
  ['chalun', 'chaloon|chalu', 'चलूँ', 'tʃəlũː', 'should I move', 'verb', '', 1912],

  // ---- Conjunctive participle: -kar / -ke --------------------------------
  ['karke', 'karkey|krke', 'करके', 'kərkeː', 'having done', 'verb', '', 1920],
  ['jakar', 'jaakar|jakr', 'जाकर', 'dʒaːkər', 'having gone', 'verb', '', 1921],
  ['jake', 'jaake|jakey', 'जाके', 'dʒaːkeː', 'having gone', 'verb', '', 1922],
  ['aakar', 'akar|aakr', 'आकर', 'aːkər', 'having come', 'verb', '', 1923],
  ['hokar', 'hokr|hoker', 'होकर', 'ɦoːkər', 'having become', 'verb', '', 1924],
  ['dekhkar', 'dekhkr|dekhker', 'देखकर', 'd̪eːkʰkər', 'having seen', 'verb', '', 1925],
  ['dekhke', 'dekhkey', 'देखके', 'd̪eːkʰkeː', 'having seen', 'verb', '', 1926],
  ['sunkar', 'sunkr|sunker', 'सुनकर', 'sʊnkər', 'having heard', 'verb', '', 1927],
  ['sunke', 'sunkey', 'सुनके', 'sʊnkeː', 'having heard', 'verb', '', 1928],
  ['sochkar', 'sochkr', 'सोचकर', 'soːtʃkər', 'having thought', 'verb', '', 1929],
  ['samajhkar', 'samajhkr|samajkar', 'समझकर', 'səmədʒʰkər', 'having understood', 'verb', '', 1930],
  ['lekar', 'lekr|leker', 'लेकर', 'leːkər', 'having taken', 'verb', '', 1931],
  ['dekar', 'dekr|deker', 'देकर', 'd̪eːkər', 'having given', 'verb', '', 1932],
  ['milkar', 'milkr|milker', 'मिलकर', 'mɪlkər', 'together/having met', 'verb', '', 1933],
  ['bolkar', 'bolkr', 'बोलकर', 'boːlkər', 'having spoken', 'verb', '', 1934],
  ['bolke', 'bolkey', 'बोलके', 'boːlkeː', 'having spoken', 'verb', '', 1935],
  ['likhkar', 'likhkr', 'लिखकर', 'lɪkʰkər', 'having written', 'verb', '', 1936],
  ['khakar', 'khaakar|khakr', 'खाकर', 'kʰaːkər', 'having eaten', 'verb', '', 1937],
  ['uthkar', 'uthkr', 'उठकर', 'ʊʈʰkər', 'having got up', 'verb', '', 1938],
  ['baithkar', 'bethkar|baithkr', 'बैठकर', 'bɛːʈʰkər', 'having sat', 'verb', '', 1939],
  ['rukkar', 'rukkr', 'रुककर', 'rʊkkər', 'having stopped', 'verb', '', 1940],
  ['bhejkar', 'bhejkr', 'भेजकर', 'bʰeːdʒkər', 'having sent', 'verb', '', 1941],
  ['chalkar', 'chalkr', 'चलकर', 'tʃəlkər', 'having walked', 'verb', '', 1942],

  // ---- Compound-verb second halves, participles, oblique infinitives -----
  ['chuka', 'chukaa', 'चुका', 'tʃʊkaː', 'already done (m)', 'verb', '', 1950],
  ['chuki', 'chukii', 'चुकी', 'tʃʊkiː', 'already done (f)', 'verb', '', 1951],
  ['chuke', 'chukey', 'चुके', 'tʃʊkeː', 'already done (pl)', 'verb', '', 1952],
  ['paya', 'payaa|paaya', 'पाया', 'paːjaː', 'was able (m)', 'verb', '', 1953],
  ['payi', 'pai|paayi', 'पाई', 'paːiː', 'was able (f)', 'verb', '', 1954],
  ['paye', 'pae|paaye', 'पाए', 'paːeː', 'were able (pl)', 'verb', '', 1955],
  ['saka', 'sakaa', 'सका', 'səkaː', 'could (m)', 'verb', '', 1956],
  ['saki', 'sakii', 'सकी', 'səkiː', 'could (f)', 'verb', '', 1957],
  ['sake', 'sakey', 'सके', 'səkeː', 'could (pl)', 'verb', '', 1958],
  ['sakta', 'saktaa', 'सकता', 'səkt̪aː', 'can (m)', 'verb', '', 1959],
  ['sakti', 'saktii', 'सकती', 'səkt̪iː', 'can (f)', 'verb', '', 1960],
  ['sakte', 'saktey', 'सकते', 'səkt̪eː', 'can (pl)', 'verb', '', 1961],
  ['laga', 'lagaa', 'लगा', 'ləgaː', 'began/seemed (m)', 'verb', '', 1962],
  ['lagi', 'lagii', 'लगी', 'ləgiː', 'began/seemed (f)', 'verb', '', 1963],
  ['lage', 'lagey', 'लगे', 'ləgeː', 'began/seemed (pl)', 'verb', '', 1964],
  ['baitha', 'betha|baithaa', 'बैठा', 'bɛːʈʰaː', 'sat (m)', 'verb', '', 1965],
  ['baithi', 'bethi|baithii', 'बैठी', 'bɛːʈʰiː', 'sat (f)', 'verb', '', 1966],
  ['pada', 'padaa|para', 'पड़ा', 'pəɽaː', 'lay / had to (m)', 'verb', '', 1967],
  ['padi', 'padii|pari', 'पड़ी', 'pəɽiː', 'lay / had to (f)', 'verb', '', 1968],
  ['khada', 'khadaa|khara', 'खड़ा', 'kʰəɽaː', 'standing (m)', 'verb', '', 1969],
  ['khadi', 'khadii|khari', 'खड़ी', 'kʰəɽiː', 'standing (f)', 'verb', '', 1970],
  ['huye', 'hue|huey', 'हुए', 'ɦʊeː', 'happened (pl)', 'verb', '', 1971],
  ['jane', 'jaane|jaaney', 'जाने', 'dʒaːneː', 'going (oblique inf)', 'verb', '', 1972],
  ['hone', 'honey', 'होने', 'ɦoːneː', 'being (oblique inf)', 'verb', '', 1973],
  ['karne', 'karney|krne', 'करने', 'kərneː', 'doing (oblique inf)', 'verb', '', 1974],
  ['dene', 'deney', 'देने', 'd̪eːneː', 'giving (oblique inf)', 'verb', '', 1975],
  ['lene', 'leney', 'लेने', 'leːneː', 'taking (oblique inf)', 'verb', '', 1976],
  ['milne', 'milney', 'मिलने', 'mɪlneː', 'meeting (oblique inf)', 'verb', '', 1977],
  ['dekhne', 'dekhney', 'देखने', 'd̪eːkʰneː', 'seeing (oblique inf)', 'verb', '', 1978],
  ['sunne', 'sunney', 'सुनने', 'sʊnneː', 'hearing (oblique inf)', 'verb', '', 1979],
  ['bhejne', 'bhejney', 'भेजने', 'bʰeːdʒneː', 'sending (oblique inf)', 'verb', '', 1980],
];
