// lib/lexicon/ncr-slang.ts
//
// The bank that makes a suggestion sound like it came from this writer rather
// than from a dictionary. hi-core.ts holds the vocabulary every Hindi speaker
// shares; this file holds the vocabulary of one commute, one office, and one
// city — Noida to Gurugram, a data platform, and the Hinglish spoken on the
// way. A rhyme for `daftar` or `okhla` is worth more here than a rhyme for
// `pyaar`, because nobody else's lexicon would have offered it.
//
// Two arrays, because the two halves need different things from us. Tokens
// with Indian phonology are invisible to CMUdict, so every one carries
// hand-authored IPA (HiRow). English tokens already have their phonemes in
// CMUdict — all they lack is a frequency rank and the tags the Desi/tech
// toggle filters on, so they are EnRow and nothing more.
//
// Transcription conventions are hi-core's, held constant:
//   - Hindi /h/ is the voiced glottal ɦ; Urdu x ɣ q where genuinely Perso-Arabic.
//   - Dental t̪ d̪ for Hindi t/d; retroflex ʈ ɖ ɽ only where genuinely retroflex.
//   - Vowel length is contrastive and always marked: ə vs aː, ɪ vs iː, ʊ vs uː.
//   - Nasalization is a tilde on the vowel; a genuine consonantal n/m stays.
//   - Word-final inherent schwa is never written.
//
// Every row here carries at least one tag — an untagged row belongs in
// hi-core, not in a personal bank.

import type { HiRow } from './hi-lexeme';
import type { EnRow } from './tagged';

/** Indian-phonology tokens: place names, Hinglish slang, Hindi work vocabulary. */
export const NCR_HI_ROWS: HiRow[] = [
  // ---- NCR geography ------------------------------------------------------
  ['noida', 'noyda|noeda', 'नोएडा', 'noːeːɖaː', 'Noida', 'noun', 'ncr', 2900],
  ['gurugram', 'gurgram|gurugraam', 'गुरुग्राम', 'gʊrʊgraːm', 'Gurugram', 'noun', 'ncr|corporate', 2901],
  ['gurgaon', 'gudgaon|gurgao|gurgav', 'गुड़गाँव', 'gʊɽgãːʋ', 'Gurgaon (older name)', 'noun', 'ncr|corporate', 2902],
  ['delhi', 'dehli|dilhi', 'दिल्ली', 'd̪ɪlliː', 'Delhi', 'noun', 'ncr', 2903],
  ['dilli', 'dilly|dili', 'दिल्ली', 'd̪ɪlliː', 'Delhi (as spoken)', 'noun', 'ncr|slang', 2904],
  ['faridabad', 'faridabaad|fareedabad', 'फ़रीदाबाद', 'fəriːd̪aːbaːd̪', 'Faridabad', 'noun', 'ncr', 2905],
  ['ghaziabad', 'gaziabad|ghaziabaad', 'ग़ाज़ियाबाद', 'ɣaːzɪjaːbaːd̪', 'Ghaziabad', 'noun', 'ncr', 2906],
  ['sonipat', 'sonepat|sonipath', 'सोनीपत', 'soːniːpət̪', 'Sonipat', 'noun', 'ncr', 2907],
  ['dwarka', 'dwaraka|dwarkaa', 'द्वारका', 'd̪ʋaːrkaː', 'Dwarka, west Delhi', 'noun', 'ncr', 2908],
  ['saket', 'saaket', 'साकेत', 'saːkeːt̪', 'Saket, south Delhi', 'noun', 'ncr', 2909],
  ['rohini', 'rohinii|rohni', 'रोहिणी', 'roːɦɪɳiː', 'Rohini, north-west Delhi', 'noun', 'ncr', 2910],
  ['karolbagh', 'karolbaag|karol', 'करोल बाग़', 'kəroːlbaːɣ', 'Karol Bagh market', 'noun', 'ncr', 2911],
  ['chandnichowk', 'chandnichok|chandani', 'चाँदनी चौक', 'tʃãːd̪niːtʃɔːk', 'Chandni Chowk, old Delhi', 'noun', 'ncr', 2912],
  ['lajpat', 'lajpath|laajpat', 'लाजपत', 'laːdʒpət̪', 'Lajpat (Nagar)', 'noun', 'ncr', 2913],
  ['nehru', 'nehroo|neharu', 'नेहरू', 'neːɦruː', 'Nehru (Place)', 'noun', 'ncr|corporate', 2914],
  ['okhla', 'okla|okhlaa', 'ओखला', 'oːkʰlaː', 'Okhla industrial belt', 'noun', 'ncr', 2915],
  ['mayur', 'mayoor', 'मयूर', 'məjuːr', 'Mayur (Vihar)', 'noun', 'ncr', 2916],
  ['vihar', 'vihaar|bihar', 'विहार', 'ʋɪɦaːr', 'Vihar (colony suffix)', 'noun', 'ncr', 2917],
  ['kalkaji', 'kalkajee|kalkaaji', 'कालकाजी', 'kaːlkaːdʒiː', 'Kalkaji, south Delhi', 'noun', 'ncr', 2918],
  ['govindpuri', 'govindpurii|gobindpuri', 'गोविंदपुरी', 'goːʋɪnd̪pʊriː', 'Govindpuri', 'noun', 'ncr', 2919],
  ['badarpur', 'badarpoor|badharpur', 'बदरपुर', 'bəd̪ərpʊr', 'Badarpur border', 'noun', 'ncr', 2920],
  ['tughlakabad', 'tuglakabad|tughlaqabad', 'तुग़लक़ाबाद', 't̪ʊɣləqaːbaːd̪', 'Tughlakabad', 'noun', 'ncr', 2921],
  ['sarita', 'saritaa', 'सरिता', 'sərɪt̪aː', 'Sarita (Vihar)', 'noun', 'ncr', 2922],
  ['munirka', 'munirkaa|munerka', 'मुनिरका', 'mʊnɪrkaː', 'Munirka', 'noun', 'ncr', 2923],
  ['katwaria', 'katwariya|katwaaria', 'कटवारिया', 'kəʈʋaːrɪjaː', 'Katwaria (Sarai)', 'noun', 'ncr', 2924],
  ['hauz', 'haus|hauzz', 'हौज़', 'ɦɔːz', 'Hauz (Khas)', 'noun', 'ncr', 2925],
  ['khas', 'khaas|khass', 'ख़ास', 'xaːs', 'special / Khas', 'adj', 'ncr', 2926],
  ['malviya', 'malaviya|malviyaa', 'मालवीय', 'maːlʋɪjaː', 'Malviya (Nagar)', 'noun', 'ncr', 2927],
  ['mehrauli', 'meharauli|mehraulii', 'महरौली', 'məɦrɔːliː', 'Mehrauli', 'noun', 'ncr', 2928],
  ['chhatarpur', 'chatarpur|chhattarpur', 'छतरपुर', 'tʃʰət̪ərpʊr', 'Chhatarpur', 'noun', 'ncr', 2929],
  ['sultanpur', 'sultaanpur', 'सुल्तानपुर', 'sʊlt̪aːnpʊr', 'Sultanpur', 'noun', 'ncr', 2930],
  ['sohna', 'sohnaa|sohana', 'सोहना', 'soːɦnaː', 'Sohna, south Gurugram', 'noun', 'ncr', 2931],
  ['manesar', 'maanesar|manesaar', 'मानेसर', 'maːneːsər', 'Manesar industrial town', 'noun', 'ncr|corporate', 2932],
  ['palam', 'palaam|pallam', 'पालम', 'paːləm', 'Palam, near the airport', 'noun', 'ncr', 2933],
  ['najafgarh', 'najaafgarh|nazafgarh', 'नजफ़गढ़', 'nədʒəfgəɖʰ', 'Najafgarh', 'noun', 'ncr', 2934],
  ['narela', 'narelaa', 'नरेला', 'nəreːlaː', 'Narela', 'noun', 'ncr', 2935],
  ['bawana', 'bavana|bawanaa', 'बवाना', 'bəʋaːnaː', 'Bawana industrial area', 'noun', 'ncr', 2936],
  ['seelampur', 'silampur|seelampoor', 'सीलमपुर', 'siːləmpʊr', 'Seelampur', 'noun', 'ncr', 2937],
  ['shahdara', 'shahdaraa|shadara', 'शाहदरा', 'ʃaːɦd̪əraː', 'Shahdara, east Delhi', 'noun', 'ncr', 2938],
  ['yamuna', 'jamna|yamunaa', 'यमुना', 'jəmʊnaː', 'Yamuna river', 'noun', 'ncr', 2939],
  ['hindon', 'hindan|hindonn', 'हिंडन', 'ɦɪnɖən', 'Hindon river / airbase', 'noun', 'ncr', 2940],
  ['aravali', 'aravalli|arawali', 'अरावली', 'əraːʋəliː', 'Aravali hills', 'noun', 'ncr', 2941],
  ['sector', 'sektor|sectorr', 'सेक्टर', 'seːkʈər', 'sector (address unit)', 'noun', 'ncr', 2942],
  ['dnd', 'dndflyway', 'डीएनडी', 'ɖiːeːnɖiː', 'DND expressway', 'noun', 'ncr', 2943],
  ['jamuna', 'jamunaa|jumna', 'जमुना', 'dʒəmʊnaː', 'Jamuna (colloquial Yamuna)', 'noun', 'ncr|slang', 2944],
  ['kashmere', 'kashmeri|kashmiri', 'कश्मीरी', 'kəʃmiːriː', 'Kashmere Gate transit hub', 'noun', 'ncr', 2945],
  ['azadpur', 'aazadpur|ajadpur', 'आज़ादपुर', 'aːzaːd̪pʊr', 'Azadpur mandi', 'noun', 'ncr', 2946],
  ['tilak', 'tilakk', 'तिलक', 't̪ɪlək', 'Tilak (Nagar)', 'noun', 'ncr', 2947],
  ['patel', 'patell|pateil', 'पटेल', 'pəʈeːl', 'Patel (Nagar)', 'noun', 'ncr', 2948],
  ['janakpuri', 'janakpurii|janpuri', 'जनकपुरी', 'dʒənəkpʊriː', 'Janakpuri', 'noun', 'ncr', 2949],
  ['uttam', 'utam|uttamm', 'उत्तम', 'ʊt̪t̪əm', 'Uttam (Nagar)', 'noun', 'ncr', 2950],
  ['tikri', 'tikrii|tikari', 'टीकरी', 'ʈiːkriː', 'Tikri border', 'noun', 'ncr', 2951],
  ['bijwasan', 'bijwaasan|bijvasan', 'बिजवासन', 'bɪdʒʋaːsən', 'Bijwasan', 'noun', 'ncr', 2952],
  ['chirag', 'chiraag|chirager', 'चिराग़', 'tʃɪraːɣ', 'lamp / Chirag (Delhi)', 'noun', 'ncr', 2953],

  // ---- Metro and the commute ----------------------------------------------
  ['metro', 'metroo|maitro', 'मेट्रो', 'meːʈroː', 'the Metro', 'noun', 'ncr', 2960],
  ['rapid', 'rapidd|raipid', 'रैपिड', 'rɛːpɪɖ', 'RapidX / rapid transit', 'noun', 'ncr', 2961],
  ['blueline', 'bluline|bluelaine', 'ब्लू लाइन', 'bluːlaːɪn', 'Blue Line', 'noun', 'ncr', 2962],
  ['aqualine', 'akwaline|aqualaine', 'एक्वा लाइन', 'ɛːkʋaːlaːɪn', 'Aqua Line, Noida', 'noun', 'ncr', 2963],
  ['yellowline', 'yelloline|yellowlaine', 'येलो लाइन', 'jeːloːlaːɪn', 'Yellow Line', 'noun', 'ncr', 2964],
  ['magenta', 'majenta|magentaa', 'मजेंटा', 'mədʒeːnʈaː', 'Magenta Line', 'noun', 'ncr', 2965],
  ['violet', 'vaylet|voilet', 'वायलेट', 'ʋaːjleːʈ', 'Violet Line', 'noun', 'ncr', 2966],
  ['station', 'steshan|istation', 'स्टेशन', 'sʈeːʃən', 'station', 'noun', 'ncr', 2967],
  ['botanical', 'botanicle|botenical', 'बॉटनिकल', 'boːʈənɪkəl', 'Botanical Garden interchange', 'noun', 'ncr', 2968],
  ['rajivchowk', 'rajivchok|rajeevchowk', 'राजीव चौक', 'raːdʒiːʋtʃɔːk', 'Rajiv Chowk interchange', 'noun', 'ncr', 2969],
  ['hudacity', 'hudasity|hooda', 'हुडा सिटी', 'ɦʊɖaːsɪʈiː', 'HUDA City Centre', 'noun', 'ncr', 2970],
  ['rickshaw', 'riksha|rikshaw', 'रिक्शा', 'rɪkʃaː', 'rickshaw', 'noun', 'ncr', 2971],
  ['auto', 'autoo|otto', 'ऑटो', 'ɔːʈoː', 'auto-rickshaw', 'noun', 'ncr', 2972],
  ['cab', 'kaab|caab', 'कैब', 'kɛːb', 'cab', 'noun', 'ncr|corporate', 2973],
  ['bhaada', 'bhada|bhaadaa', 'भाड़ा', 'bʰaːɽaː', 'fare', 'noun', 'ncr', 2974],
  ['kirai', 'kiraya|kiraaya', 'किराया', 'kɪraːjaː', 'rent/fare', 'noun', 'ncr', 2975],
  ['jam', 'jaam|jamm', 'जाम', 'dʒaːm', 'traffic jam', 'noun', 'ncr|slang', 2976],
  ['traffic', 'trafik|traffick', 'ट्रैफ़िक', 'ʈrɛːfɪk', 'traffic', 'noun', 'ncr', 2977],
  ['signal', 'signall|singnal', 'सिग्नल', 'sɪgnəl', 'traffic signal', 'noun', 'ncr', 2978],
  ['flyover', 'flyovar|phlyover', 'फ़्लाईओवर', 'flaːiːoːʋər', 'flyover', 'noun', 'ncr', 2979],
  ['underpass', 'andarpass|underpas', 'अंडरपास', 'ənɖərpaːs', 'underpass', 'noun', 'ncr', 2980],
  ['toll', 'tol|tollh', 'टोल', 'ʈoːl', 'toll plaza', 'noun', 'ncr', 2981],
  ['challan', 'chalaan|challaan', 'चालान', 'tʃaːlaːn', 'traffic fine', 'noun', 'ncr', 2982],
  ['chalan', 'chalann', 'चलन', 'tʃələn', 'trend/currency in use', 'noun', 'ncr|slang', 2983],
  ['pollution', 'polution|palution', 'पॉल्यूशन', 'poːljuːʃən', 'pollution', 'noun', 'ncr', 2984],
  ['smog', 'smogg|smoag', 'स्मॉग', 'smɔːg', 'smog', 'noun', 'ncr', 2985],
  ['dhaba', 'dhabha|dhabaa', 'ढाबा', 'ɖʰaːbaː', 'roadside eatery', 'noun', 'ncr|slang', 2986],
  ['chai', 'chay|chaai', 'चाय', 'tʃaːj', 'tea', 'noun', 'ncr|slang', 2987],
  ['tapri', 'tapari|taprii', 'टपरी', 'ʈəpriː', 'tea stall', 'noun', 'ncr|slang', 2988],
  ['thela', 'thelaa|tela', 'ठेला', 'ʈʰeːlaː', 'handcart', 'noun', 'ncr|slang', 2989],
  ['redlight', 'redlite|redlaight', 'रेड लाइट', 'reːɖlaːɪʈ', 'red light', 'noun', 'ncr', 2990],

  // ---- Work and grind, Hindi side -----------------------------------------
  ['naukri', 'nokri|naukrii', 'नौकरी', 'nɔːkriː', 'job', 'noun', 'corporate', 3000],
  ['daftar', 'daftarr|daftur', 'दफ़्तर', 'd̪əft̪ər', 'office', 'noun', 'corporate', 3001],
  ['malik', 'maalik|maalick', 'मालिक', 'maːlɪk', 'owner/boss', 'noun', 'corporate', 3002],
  ['saheb', 'sahab|saahab', 'साहेब', 'saːɦeːb', 'sir', 'noun', 'corporate', 3003],
  ['babu', 'baboo|baabu', 'बाबू', 'baːbuː', 'clerk/officer', 'noun', 'corporate|slang', 3004],
  ['chhutti', 'chutti|chhuttii', 'छुट्टी', 'tʃʰʊʈʈiː', 'leave/holiday', 'noun', 'corporate', 3005],
  ['tankhwah', 'tankhwaah|tankhaah', 'तनख़्वाह', 't̪ənxʋaːɦ', 'salary', 'noun', 'corporate', 3006],
  ['tankha', 'tankhaa|tankhah', 'तनख़ा', 't̪ənxaː', 'pay', 'noun', 'corporate', 3007],
  ['mehnat', 'mehanat|mehnatt', 'मेहनत', 'meːɦnət̪', 'hard work', 'noun', 'corporate', 3008],
  ['majdoori', 'mazdoori|majduri', 'मजदूरी', 'mədʒd̪uːriː', 'wage labour', 'noun', 'corporate', 3009],
  ['mazdoor', 'majdoor|mazdur', 'मज़दूर', 'məzd̪uːr', 'labourer', 'noun', 'corporate|ncr', 3010],
  ['dihaadi', 'dihadi|dehadi', 'दिहाड़ी', 'd̪ɪɦaːɽiː', 'daily wage', 'noun', 'corporate|ncr', 3011],
  ['thekedaar', 'thekedar|thekaydar', 'ठेकेदार', 'ʈʰeːkeːd̪aːr', 'contractor', 'noun', 'corporate', 3012],
  ['sifarish', 'sifaarish|sifarishh', 'सिफ़ारिश', 'sɪfaːrɪʃ', 'recommendation/pull', 'noun', 'corporate|slang', 3013],
  ['jugaad', 'jugad|jugaadd', 'जुगाड़', 'dʒʊgaːɽ', 'workaround/hack', 'noun', 'slang|corporate', 3014],
  ['chamchagiri', 'chamchagirii|chamchagari', 'चमचागीरी', 'tʃəmtʃaːgiːriː', 'sycophancy', 'noun', 'corporate|slang', 3015],
  ['tarakki', 'tarakkii|taraqqi', 'तरक़्क़ी', 't̪ərəqqiː', 'advancement', 'noun', 'corporate', 3016],
  ['pareshani', 'pareshaani|pareshanii', 'परेशानी', 'pəreːʃaːniː', 'trouble', 'noun', 'corporate', 3017],
  ['dabaav', 'dabav|dabaaw', 'दबाव', 'd̪əbaːʋ', 'pressure', 'noun', 'corporate', 3018],
  ['bojh', 'boj|bojhh', 'बोझ', 'boːdʒʰ', 'burden', 'noun', 'corporate', 3019],
  ['thakan', 'thakaan|thakann', 'थकान', 't̪ʰəkaːn', 'exhaustion', 'noun', 'corporate', 3020],
  ['sutta', 'suttaa|sutaa', 'सुट्टा', 'sʊʈʈaː', 'cigarette', 'noun', 'slang|ncr', 3021],
  ['seedhi', 'sidhi|seedhii', 'सीढ़ी', 'siːɖʰiː', 'ladder/stair', 'noun', 'corporate', 3022],
  ['kursi', 'kursii|kurshi', 'कुर्सी', 'kʊrsiː', 'chair/post', 'noun', 'corporate', 3023],
  ['mez', 'mej|mezz', 'मेज़', 'meːz', 'desk/table', 'noun', 'corporate', 3024],
  ['file', 'fail|phile', 'फ़ाइल', 'faːɪl', 'file', 'noun', 'corporate|tech', 3025],
  ['register', 'rajistar|registar', 'रजिस्टर', 'rədʒɪsʈər', 'ledger/register', 'noun', 'corporate', 3026],
  ['mohar', 'muhar|moharr', 'मोहर', 'moːɦər', 'seal/stamp', 'noun', 'corporate', 3027],
  ['farz', 'farj|farzz', 'फ़र्ज़', 'fərz', 'duty', 'noun', 'corporate', 3028],
  ['jimmedari', 'zimmedari|jimmedaari', 'ज़िम्मेदारी', 'zɪmmeːd̪aːriː', 'responsibility', 'noun', 'corporate', 3029],
  ['galti', 'galtii|ghalti', 'ग़लती', 'ɣəlt̪iː', 'mistake', 'noun', 'corporate', 3030],
  ['sudhaar', 'sudhar|sudhaarr', 'सुधार', 'sʊd̪ʰaːr', 'fix/improvement', 'noun', 'corporate|tech', 3031],
  ['sawaal', 'sawal|sawaall', 'सवाल', 'səʋaːl', 'question', 'noun', 'corporate', 3032],
  ['kamai', 'kamaai|kamaee', 'कमाई', 'kəmaːiː', 'earnings', 'noun', 'corporate', 3033],
  ['kharcha', 'kharchaa|karcha', 'ख़र्चा', 'xərtʃaː', 'expense', 'noun', 'corporate', 3034],
  ['bachat', 'bachatt|bachath', 'बचत', 'bətʃət̪', 'savings', 'noun', 'corporate', 3035],
  ['udhaar', 'udhar|udhaarr', 'उधार', 'ʊd̪ʰaːr', 'credit/loan', 'noun', 'corporate', 3036],
  ['hisaab', 'hisab|hisaabb', 'हिसाब', 'ɦɪsaːb', 'account/reckoning', 'noun', 'corporate', 3037],
  ['kaagaz', 'kagaz|kaagazz', 'काग़ज़', 'kaːɣəz', 'paper/document', 'noun', 'corporate', 3038],
  ['darkhwast', 'darkhwaast|darqhwast', 'दरख़्वास्त', 'd̪ərxʋaːst̪', 'application/request', 'noun', 'corporate', 3039],
  ['karobaar', 'karobar|kaarobaar', 'कारोबार', 'kaːroːbaːr', 'business', 'noun', 'corporate', 3040],

  // ---- Hinglish street slang ----------------------------------------------
  ['bhaisahab', 'bhaisaab|bhaisaahab', 'भाईसाहब', 'bʰaːiːsaːɦəb', 'sir/bro (respectful)', 'interj', 'slang|ncr', 3050],
  ['bhaiya', 'bhaiyya|bhaeya', 'भैया', 'bʰɛːjaː', 'brother/bro', 'noun', 'slang|ncr', 3051],
  ['guru', 'gurru|guroo', 'गुरु', 'gʊrʊ', 'master/mate', 'noun', 'slang', 3052],
  ['ustad', 'ustaad|usstad', 'उस्ताद', 'ʊst̪aːd̪', 'master/virtuoso', 'noun', 'slang|filmi', 3053],
  ['bhidu', 'bhiddu|bhidoo', 'भिड़ू', 'bʰɪɽuː', 'buddy', 'noun', 'slang|filmi', 3054],
  ['launda', 'londa|laundaa', 'लौंडा', 'lɔːnɖaː', 'boy/lad', 'noun', 'slang', 3055],
  ['laundiya', 'londiya|laundia', 'लौंडिया', 'lɔːnɖɪjaː', 'girl/lass', 'noun', 'slang', 3056],
  ['chhora', 'chora|chhoraa', 'छोरा', 'tʃʰoːraː', 'boy (Haryanvi)', 'noun', 'slang|ncr', 3057],
  ['chhori', 'chori|chhorii', 'छोरी', 'tʃʰoːriː', 'girl (Haryanvi)', 'noun', 'slang|ncr', 3058],
  ['banda', 'bandaa|bunda', 'बंदा', 'bənd̪aː', 'guy', 'noun', 'slang', 3059],
  ['bandi', 'bandii|bundi', 'बंदी', 'bənd̪iː', 'girl', 'noun', 'slang', 3060],
  ['tapori', 'tapoori|tappori', 'टपोरी', 'ʈəpoːriː', 'street tough', 'noun', 'slang|filmi', 3061],
  ['bindaas', 'bindas|bindaass', 'बिंदास', 'bɪnd̪aːs', 'carefree', 'adj', 'slang|filmi', 3062],
  ['rapchik', 'rapchick|repchik', 'रैपचिक', 'rɛːptʃɪk', 'sharp/stylish', 'adj', 'slang', 3063],
  ['jhakaas', 'jhakas|jhakaass', 'झकास', 'dʒʰəkaːs', 'brilliant', 'adj', 'slang|filmi', 3064],
  ['tagda', 'tagdaa|tagra', 'तगड़ा', 't̪əgɽaː', 'strong/solid', 'adj', 'slang', 3065],
  ['fadu', 'phadu|faddu', 'फाड़ू', 'faːɽuː', 'killer/awesome', 'adj', 'slang', 3066],
  ['mast', 'mastt|must', 'मस्त', 'məst̪', 'great/chill', 'adj', 'slang', 3067],
  ['scene', 'seen|sceene', 'सीन', 'siːn', 'situation/plan', 'noun', 'slang', 3068],
  ['lafda', 'lafdaa|laphda', 'लफड़ा', 'ləfɽaː', 'mess/trouble', 'noun', 'slang', 3069],
  ['panga', 'pangaa|punga', 'पंगा', 'pəŋgaː', 'beef/trouble', 'noun', 'slang', 3070],
  ['jhol', 'jholl|jhole', 'झोल', 'dʒʰoːl', 'shady business', 'noun', 'slang', 3071],
  ['chakkar', 'chakar|chukkar', 'चक्कर', 'tʃəkkər', 'round/entanglement', 'noun', 'slang', 3072],
  ['setting', 'seting|saitting', 'सेटिंग', 'seːʈɪŋ', 'arrangement/fix', 'noun', 'slang|corporate', 3073],
  ['jugaadu', 'jugadu|jugaduu', 'जुगाड़ू', 'dʒʊgaːɽuː', 'resourceful hustler', 'adj', 'slang|corporate', 3074],
  ['dhandha', 'dhanda|dhandhaa', 'धंधा', 'd̪ʰənd̪ʰaː', 'business/trade', 'noun', 'slang|corporate', 3075],
  ['chillar', 'chiller|chillarr', 'चिल्लर', 'tʃɪllər', 'loose change/petty', 'noun', 'slang', 3076],
  ['khoka', 'khokha|khokaa', 'खोखा', 'kʰoːkʰaː', 'kiosk / one crore', 'noun', 'slang', 3077],
  ['peti', 'petii|paiti', 'पेटी', 'peːʈiː', 'box / one lakh', 'noun', 'slang', 3078],
  ['tempo', 'tempoo|taimpo', 'टेंपो', 'ʈeːmpoː', 'shared tempo van', 'noun', 'slang|ncr', 3079],
  ['ghanta', 'ghantaa|ghunta', 'घंटा', 'gʰəɳʈaː', 'hour / nothing doing', 'noun', 'slang', 3080],
  ['bakwaas', 'bakwas|bakvaas', 'बकवास', 'bəkʋaːs', 'nonsense', 'noun', 'slang', 3081],
  ['timepass', 'timepas|taimpass', 'टाइमपास', 'ʈaːɪmpaːs', 'killing time', 'noun', 'slang', 3082],
  ['faltu', 'faaltu|phaltu', 'फ़ालतू', 'faːlt̪uː', 'useless/spare', 'adj', 'slang', 3083],
  ['dhakka', 'dhakkaa|dhaka', 'धक्का', 'd̪ʰəkkaː', 'shove/jolt', 'noun', 'slang|ncr', 3084],
  ['dhamaal', 'dhamal|dhamaall', 'धमाल', 'd̪ʰəmaːl', 'riot/uproar', 'noun', 'slang|filmi', 3085],
  ['hulchul', 'halchal|hulchull', 'हलचल', 'ɦəltʃəl', 'commotion', 'noun', 'slang|filmi', 3086],
];

/** English tokens that need tagging, not transcription — CMUdict has the phonemes. */
export const NCR_EN_ROWS: EnRow[] = [
  // ---- Data platform ------------------------------------------------------
  ['migration', 'tech', 3500],
  ['pipeline', 'tech', 3501],
  ['cluster', 'tech', 3502],
  ['kafka', 'tech', 3503, 'distributed event-streaming log'],
  ['airflow', 'tech', 3504, 'workflow scheduler for data pipelines'],
  ['spark', 'tech', 3505, 'distributed compute engine'],
  ['hadoop', 'tech', 3506, 'the older distributed storage and compute stack'],
  ['snowflake', 'tech', 3507, 'cloud data warehouse'],
  ['warehouse', 'tech', 3508],
  ['schema', 'tech', 3509],
  ['query', 'tech', 3510],
  ['index', 'tech', 3511],
  ['partition', 'tech', 3512],
  ['replication', 'tech', 3513],
  ['sharding', 'tech', 3514, 'splitting one dataset across many machines'],
  ['cache', 'tech', 3515],
  ['storage', 'tech', 3516],
  ['compute', 'tech', 3517],
  ['memory', 'tech', 3518],

  // ---- Pipelines and scheduling -------------------------------------------
  ['ingestion', 'tech', 3520],
  ['backfill', 'tech', 3521, 'rerunning a pipeline over past dates'],
  ['batch', 'tech', 3522],
  ['stream', 'tech', 3523],
  ['cron', 'tech', 3524, 'time-based job scheduler'],
  ['scheduler', 'tech', 3525],
  ['dag', 'tech', 3526, 'directed acyclic graph; one Airflow workflow'],
  ['orchestration', 'tech', 3527],
  ['checkpoint', 'tech', 3528],
  ['latency', 'tech', 3529],
  ['throughput', 'tech', 3530],
  ['timeout', 'tech', 3531],
  ['retry', 'tech', 3532],
  ['bottleneck', 'tech', 3533],
  ['benchmark', 'tech', 3534],
  ['optimize', 'tech', 3535],

  // ---- Reliability and the pager ------------------------------------------
  ['alert', 'tech', 3540],
  ['pager', 'tech', 3541, 'the on-call rotation, by metonymy'],
  ['incident', 'tech', 3542],
  ['outage', 'tech', 3543],
  ['postmortem', 'tech', 3544, 'the write-up after an incident'],
  ['runbook', 'tech', 3545, 'step-by-step procedure for a known failure'],
  ['dashboard', 'tech', 3546],
  ['metric', 'tech', 3547],
  ['logging', 'tech', 3548],
  ['monitoring', 'tech', 3549],
  ['downtime', 'tech', 3550],
  ['uptime', 'tech', 3551],
  ['rollback', 'tech', 3552, 'reverting a deploy to the previous version'],

  // ---- Ship it ------------------------------------------------------------
  ['deploy', 'tech', 3555],
  ['deployed', 'tech', 3556],
  ['deployment', 'tech', 3557],
  ['staging', 'tech', 3558, 'the pre-production environment'],
  ['production', 'tech', 3559],
  ['release', 'tech', 3560],
  ['version', 'tech', 3561],
  ['rollout', 'tech', 3562],
  ['patch', 'tech', 3563],
  ['hotfix', 'tech', 3564, 'an urgent fix shipped outside the release train'],
  ['feature', 'tech', 3565],
  ['flag', 'tech', 3566],
  ['experiment', 'tech', 3567],

  // ---- Tooling and version control ----------------------------------------
  ['terraform', 'tech', 3570, 'infrastructure-as-code tool'],
  ['docker', 'tech', 3571, 'container runtime'],
  ['kubernetes', 'tech', 3572, 'container orchestrator'],
  ['container', 'tech', 3573],
  ['commit', 'tech', 3574],
  ['branch', 'tech', 3575],
  ['merge', 'tech', 3576],
  ['rebase', 'tech', 3577, 'replaying commits onto a new base'],
  ['review', 'tech', 3578],
  ['refactor', 'tech', 3579],
  ['legacy', 'tech', 3580],
  ['technical', 'tech', 3581],
  ['debt', 'tech', 3582],
  ['server', 'tech', 3583],
  ['laptop', 'tech', 3584],
  ['vpn', 'tech', 3585, 'the tunnel into the office network'],
  ['credentials', 'tech', 3586],
  ['access', 'tech', 3587],
  ['permission', 'tech', 3588],
  ['firewall', 'tech', 3589],

  // ---- The ticket queue ---------------------------------------------------
  ['standup', 'corporate', 3600, 'the daily status meeting'],
  ['sprint', 'corporate', 3601],
  ['backlog', 'corporate', 3602],
  ['retro', 'corporate', 3603, 'retrospective at the end of a sprint'],
  ['ticket', 'corporate', 3604],
  ['jira', 'corporate', 3605, 'the issue tracker'],
  ['slack', 'corporate', 3606],
  ['email', 'corporate', 3607],
  ['calendar', 'corporate', 3608],
  ['meeting', 'corporate', 3609],
  ['blocker', 'corporate', 3610],
  ['dependency', 'corporate', 3611],
  ['priority', 'corporate', 3612],
  ['deadline', 'corporate', 3613],
  ['extension', 'corporate', 3614],
  ['escalation', 'corporate', 3615],
  ['stakeholder', 'corporate', 3616],
  ['deliverable', 'corporate', 3617],
  ['roadmap', 'corporate', 3618],
  ['quarter', 'corporate', 3619],
  ['target', 'corporate', 3620],

  // ---- Career, HR, and the appraisal cycle --------------------------------
  ['appraisal', 'corporate', 3630, 'the annual performance review'],
  ['promotion', 'corporate', 3631],
  ['increment', 'corporate', 3632, 'the annual raise, as HR names it'],
  ['hike', 'corporate|ncr', 3633, 'salary raise, in Indian office usage'],
  ['notice', 'corporate', 3634],
  ['period', 'corporate', 3635],
  ['resignation', 'corporate', 3636],
  ['attrition', 'corporate', 3637, 'the rate people quit'],
  ['onboarding', 'corporate', 3638],
  ['offboarding', 'corporate', 3639],
  ['handover', 'corporate', 3640],
  ['headcount', 'corporate', 3641, 'budgeted number of people on a team'],
  ['bandwidth', 'corporate', 3642, 'spare time, in manager-speak'],
  ['capacity', 'corporate', 3643],

  // ---- Money and the vendor ----------------------------------------------
  ['revenue', 'corporate', 3650],
  ['budget', 'corporate', 3651],
  ['billing', 'corporate', 3652],
  ['invoice', 'corporate', 3653],
  ['vendor', 'corporate', 3654],
  ['client', 'corporate', 3655],
  ['delivery', 'corporate', 3656],

  // ---- The grind ----------------------------------------------------------
  ['overtime', 'corporate|slang', 3660],
  ['weekend', 'corporate|slang', 3661],
  ['burnout', 'corporate|slang', 3662],
  ['grind', 'slang', 3663],
  ['hustle', 'slang', 3664],
];
