// lib/lexicon/phrase-bank.ts
//
// Short n-grams for server-side mosaic and holorime search. Each entry is a
// 2–4 word phrase chosen for rhyme-friendly cadence and register overlap with
// the NCR/Hinglish lyric context.

export interface PhraseEntry {
  text: string;
  lang: 'en' | 'hi' | 'mixed';
  wordCount: number;
  tags: string[];
}

export const PHRASE_BANK: PhraseEntry[] = [
  // ---- English 2-word -----------------------------------------------------
  { text: 'late night', lang: 'en', wordCount: 2, tags: [] },
  { text: 'cold sweat', lang: 'en', wordCount: 2, tags: [] },
  { text: 'dark room', lang: 'en', wordCount: 2, tags: [] },
  { text: 'blue moon', lang: 'en', wordCount: 2, tags: [] },
  { text: 'hard knock', lang: 'en', wordCount: 2, tags: ['slang'] },
  { text: 'fast lane', lang: 'en', wordCount: 2, tags: [] },
  { text: 'slow burn', lang: 'en', wordCount: 2, tags: [] },
  { text: 'deep breath', lang: 'en', wordCount: 2, tags: [] },
  { text: 'long road', lang: 'en', wordCount: 2, tags: [] },
  { text: 'short fuse', lang: 'en', wordCount: 2, tags: [] },
  { text: 'big dream', lang: 'en', wordCount: 2, tags: [] },
  { text: 'small talk', lang: 'en', wordCount: 2, tags: ['corporate'] },
  { text: 'real talk', lang: 'en', wordCount: 2, tags: ['slang'] },
  { text: 'side hustle', lang: 'en', wordCount: 2, tags: ['slang'] },
  { text: 'main stage', lang: 'en', wordCount: 2, tags: [] },
  { text: 'back seat', lang: 'en', wordCount: 2, tags: [] },
  { text: 'front row', lang: 'en', wordCount: 2, tags: [] },
  { text: 'top floor', lang: 'en', wordCount: 2, tags: ['corporate'] },
  { text: 'ground zero', lang: 'en', wordCount: 2, tags: [] },
  { text: 'free fall', lang: 'en', wordCount: 2, tags: [] },
  { text: 'low key', lang: 'en', wordCount: 2, tags: ['slang'] },
  { text: 'high tide', lang: 'en', wordCount: 2, tags: [] },
  { text: 'soft glow', lang: 'en', wordCount: 2, tags: [] },
  { text: 'sharp edge', lang: 'en', wordCount: 2, tags: [] },
  { text: 'blind spot', lang: 'en', wordCount: 2, tags: [] },
  { text: 'sweet spot', lang: 'en', wordCount: 2, tags: [] },
  { text: 'hot take', lang: 'en', wordCount: 2, tags: ['slang'] },
  { text: 'cold front', lang: 'en', wordCount: 2, tags: [] },
  { text: 'warm heart', lang: 'en', wordCount: 2, tags: [] },
  { text: 'dry spell', lang: 'en', wordCount: 2, tags: [] },
  { text: 'wet paint', lang: 'en', wordCount: 2, tags: [] },
  { text: 'fresh start', lang: 'en', wordCount: 2, tags: [] },
  { text: 'clean slate', lang: 'en', wordCount: 2, tags: [] },
  { text: 'rough patch', lang: 'en', wordCount: 2, tags: [] },
  { text: 'smooth talk', lang: 'en', wordCount: 2, tags: [] },
  { text: 'tight grip', lang: 'en', wordCount: 2, tags: [] },
  { text: 'loose change', lang: 'en', wordCount: 2, tags: [] },
  { text: 'heavy rain', lang: 'en', wordCount: 2, tags: [] },
  { text: 'light rain', lang: 'en', wordCount: 2, tags: [] },
  { text: 'thick skin', lang: 'en', wordCount: 2, tags: [] },
  { text: 'thin line', lang: 'en', wordCount: 2, tags: [] },
  { text: 'wide open', lang: 'en', wordCount: 2, tags: [] },
  { text: 'narrow path', lang: 'en', wordCount: 2, tags: [] },
  { text: 'steady hand', lang: 'en', wordCount: 2, tags: [] },
  { text: 'shaky ground', lang: 'en', wordCount: 2, tags: [] },
  { text: 'broken glass', lang: 'en', wordCount: 2, tags: [] },
  { text: 'golden hour', lang: 'en', wordCount: 2, tags: [] },
  { text: 'silver lining', lang: 'en', wordCount: 2, tags: [] },
  { text: 'black market', lang: 'en', wordCount: 2, tags: [] },
  { text: 'white noise', lang: 'en', wordCount: 2, tags: [] },
  { text: 'red tape', lang: 'en', wordCount: 2, tags: ['corporate'] },
  { text: 'green light', lang: 'en', wordCount: 2, tags: [] },
  { text: 'gray area', lang: 'en', wordCount: 2, tags: [] },
  { text: 'night shift', lang: 'en', wordCount: 2, tags: ['corporate'] },
  { text: 'day job', lang: 'en', wordCount: 2, tags: [] },
  { text: 'pay cut', lang: 'en', wordCount: 2, tags: ['corporate'] },
  { text: 'cash flow', lang: 'en', wordCount: 2, tags: ['corporate'] },
  { text: 'stock price', lang: 'en', wordCount: 2, tags: ['corporate'] },
  { text: 'team lead', lang: 'en', wordCount: 2, tags: ['tech', 'corporate'] },
  { text: 'code review', lang: 'en', wordCount: 2, tags: ['tech'] },
  { text: 'bug fix', lang: 'en', wordCount: 2, tags: ['tech'] },
  { text: 'data lake', lang: 'en', wordCount: 2, tags: ['tech'] },
  { text: 'cloud stack', lang: 'en', wordCount: 2, tags: ['tech'] },
  { text: 'root cause', lang: 'en', wordCount: 2, tags: ['tech', 'corporate'] },
  { text: 'edge case', lang: 'en', wordCount: 2, tags: ['tech'] },
  { text: 'pull request', lang: 'en', wordCount: 2, tags: ['tech'] },
  { text: 'sprint plan', lang: 'en', wordCount: 2, tags: ['tech', 'corporate'] },
  { text: 'standup call', lang: 'en', wordCount: 2, tags: ['tech', 'corporate'] },
  { text: 'road map', lang: 'en', wordCount: 2, tags: ['tech', 'corporate'] },
  { text: 'pitch deck', lang: 'en', wordCount: 2, tags: ['corporate'] },
  { text: 'board room', lang: 'en', wordCount: 2, tags: ['corporate'] },
  { text: 'head count', lang: 'en', wordCount: 2, tags: ['corporate'] },
  { text: 'exit plan', lang: 'en', wordCount: 2, tags: ['corporate'] },
  { text: 'metro ride', lang: 'en', wordCount: 2, tags: ['ncr'] },
  { text: 'traffic jam', lang: 'en', wordCount: 2, tags: ['ncr'] },
  { text: 'office cab', lang: 'en', wordCount: 2, tags: ['ncr', 'corporate'] },
  { text: 'food court', lang: 'en', wordCount: 2, tags: ['ncr'] },
  { text: 'mall crowd', lang: 'en', wordCount: 2, tags: ['ncr'] },
  { text: 'street food', lang: 'en', wordCount: 2, tags: ['ncr'] },
  { text: 'roof top', lang: 'en', wordCount: 2, tags: ['ncr'] },
  { text: 'film reel', lang: 'en', wordCount: 2, tags: ['filmi'] },
  { text: 'love song', lang: 'en', wordCount: 2, tags: ['filmi'] },
  { text: 'slow motion', lang: 'en', wordCount: 2, tags: ['filmi'] },
  { text: 'plot twist', lang: 'en', wordCount: 2, tags: ['filmi'] },
  { text: 'star cast', lang: 'en', wordCount: 2, tags: ['filmi'] },
  { text: 'hit song', lang: 'en', wordCount: 2, tags: ['filmi'] },
  { text: 'mix tape', lang: 'en', wordCount: 2, tags: ['slang'] },
  { text: 'boom bap', lang: 'en', wordCount: 2, tags: ['slang'] },
  { text: 'trap beat', lang: 'en', wordCount: 2, tags: ['slang'] },
  { text: 'word play', lang: 'en', wordCount: 2, tags: [] },
  { text: 'flow state', lang: 'en', wordCount: 2, tags: ['slang'] },
  { text: 'crowd noise', lang: 'en', wordCount: 2, tags: [] },
  { text: 'open mic', lang: 'en', wordCount: 2, tags: ['slang'] },
  { text: 'sound check', lang: 'en', wordCount: 2, tags: [] },

  // ---- English 3-word -----------------------------------------------------
  { text: 'in the moment', lang: 'en', wordCount: 3, tags: [] },
  { text: 'on my mind', lang: 'en', wordCount: 3, tags: [] },
  { text: 'out of time', lang: 'en', wordCount: 3, tags: [] },
  { text: 'under the radar', lang: 'en', wordCount: 3, tags: [] },
  { text: 'over the top', lang: 'en', wordCount: 3, tags: [] },
  { text: 'through the night', lang: 'en', wordCount: 3, tags: [] },
  { text: 'across the line', lang: 'en', wordCount: 3, tags: [] },
  { text: 'against the wall', lang: 'en', wordCount: 3, tags: [] },
  { text: 'behind the scenes', lang: 'en', wordCount: 3, tags: ['filmi'] },
  { text: 'beyond the limit', lang: 'en', wordCount: 3, tags: [] },
  { text: 'into the void', lang: 'en', wordCount: 3, tags: [] },
  { text: 'off the grid', lang: 'en', wordCount: 3, tags: ['slang'] },
  { text: 'on the clock', lang: 'en', wordCount: 3, tags: ['corporate'] },
  { text: 'out of pocket', lang: 'en', wordCount: 3, tags: ['slang'] },
  { text: 'under the hood', lang: 'en', wordCount: 3, tags: ['tech'] },
  { text: 'down to earth', lang: 'en', wordCount: 3, tags: [] },
  { text: 'up in smoke', lang: 'en', wordCount: 3, tags: [] },
  { text: 'back on track', lang: 'en', wordCount: 3, tags: [] },
  { text: 'lost in thought', lang: 'en', wordCount: 3, tags: [] },
  { text: 'stuck in traffic', lang: 'en', wordCount: 3, tags: ['ncr'] },
  { text: 'late for work', lang: 'en', wordCount: 3, tags: ['corporate'] },
  { text: 'ready to roll', lang: 'en', wordCount: 3, tags: ['slang'] },
  { text: 'hard to say', lang: 'en', wordCount: 3, tags: [] },
  { text: 'easy to miss', lang: 'en', wordCount: 3, tags: [] },
  { text: 'safe to assume', lang: 'en', wordCount: 3, tags: [] },
  { text: 'time to go', lang: 'en', wordCount: 3, tags: [] },
  { text: 'place to be', lang: 'en', wordCount: 3, tags: [] },
  { text: 'way too far', lang: 'en', wordCount: 3, tags: [] },
  { text: 'one more time', lang: 'en', wordCount: 3, tags: [] },
  { text: 'all night long', lang: 'en', wordCount: 3, tags: [] },
  { text: 'day by day', lang: 'en', wordCount: 3, tags: [] },
  { text: 'step by step', lang: 'en', wordCount: 3, tags: [] },
  { text: 'face to face', lang: 'en', wordCount: 3, tags: [] },
  { text: 'hand in hand', lang: 'en', wordCount: 3, tags: [] },
  { text: 'heart to heart', lang: 'en', wordCount: 3, tags: [] },
  { text: 'mind over matter', lang: 'en', wordCount: 3, tags: [] },
  { text: 'less is more', lang: 'en', wordCount: 3, tags: [] },
  { text: 'more or less', lang: 'en', wordCount: 3, tags: [] },
  { text: 'now or never', lang: 'en', wordCount: 3, tags: [] },
  { text: 'hit or miss', lang: 'en', wordCount: 3, tags: [] },
  { text: 'make or break', lang: 'en', wordCount: 3, tags: [] },
  { text: 'bar for bar', lang: 'en', wordCount: 3, tags: ['slang'] },
  { text: 'push to prod', lang: 'en', wordCount: 3, tags: ['tech'] },
  { text: 'ship the fix', lang: 'en', wordCount: 3, tags: ['tech'] },
  { text: 'run the query', lang: 'en', wordCount: 3, tags: ['tech'] },
  { text: 'merge the branch', lang: 'en', wordCount: 3, tags: ['tech'] },
  { text: 'close the ticket', lang: 'en', wordCount: 3, tags: ['tech', 'corporate'] },
  { text: 'join the call', lang: 'en', wordCount: 3, tags: ['corporate'] },
  { text: 'send the deck', lang: 'en', wordCount: 3, tags: ['corporate'] },
  { text: 'sign the deal', lang: 'en', wordCount: 3, tags: ['corporate'] },
  { text: 'miss the metro', lang: 'en', wordCount: 3, tags: ['ncr'] },
  { text: 'cut the scene', lang: 'en', wordCount: 3, tags: ['filmi'] },
  { text: 'play the hero', lang: 'en', wordCount: 3, tags: ['filmi'] },
  { text: 'drop the beat', lang: 'en', wordCount: 3, tags: ['slang'] },
  { text: 'spit the verse', lang: 'en', wordCount: 3, tags: ['slang'] },
  { text: 'ride the wave', lang: 'en', wordCount: 3, tags: [] },
  { text: 'chase the dream', lang: 'en', wordCount: 3, tags: [] },
  { text: 'break the cycle', lang: 'en', wordCount: 3, tags: [] },
  { text: 'find the rhythm', lang: 'en', wordCount: 3, tags: [] },
  { text: 'feel the pulse', lang: 'en', wordCount: 3, tags: [] },

  // ---- English 4-word -----------------------------------------------------
  { text: 'out of the blue', lang: 'en', wordCount: 4, tags: [] },
  { text: 'in over my head', lang: 'en', wordCount: 4, tags: [] },
  { text: 'on the other side', lang: 'en', wordCount: 4, tags: [] },
  { text: 'out of my control', lang: 'en', wordCount: 4, tags: [] },
  { text: 'through thick and thin', lang: 'en', wordCount: 4, tags: [] },
  { text: 'from start to finish', lang: 'en', wordCount: 4, tags: [] },
  { text: 'for better or worse', lang: 'en', wordCount: 4, tags: [] },
  { text: 'by any means necessary', lang: 'en', wordCount: 4, tags: [] },
  { text: 'on the same page', lang: 'en', wordCount: 4, tags: ['corporate'] },
  { text: 'off the beaten path', lang: 'en', wordCount: 4, tags: [] },
  { text: 'up against the wall', lang: 'en', wordCount: 4, tags: [] },
  { text: 'down for the count', lang: 'en', wordCount: 4, tags: [] },
  { text: 'back against the wall', lang: 'en', wordCount: 4, tags: [] },
  { text: 'lost in the moment', lang: 'en', wordCount: 4, tags: [] },
  { text: 'stuck between two worlds', lang: 'en', wordCount: 4, tags: [] },
  { text: 'ready for the spotlight', lang: 'en', wordCount: 4, tags: ['filmi'] },
  { text: 'waiting for the signal', lang: 'en', wordCount: 4, tags: ['tech'] },
  { text: 'running out of time', lang: 'en', wordCount: 4, tags: [] },
  { text: 'looking for a sign', lang: 'en', wordCount: 4, tags: [] },
  { text: 'trying to stay afloat', lang: 'en', wordCount: 4, tags: [] },
  { text: 'learning on the job', lang: 'en', wordCount: 4, tags: ['corporate'] },
  { text: 'burning the midnight oil', lang: 'en', wordCount: 4, tags: ['corporate'] },
  { text: 'cutting through the noise', lang: 'en', wordCount: 4, tags: [] },
  { text: 'finding my own voice', lang: 'en', wordCount: 4, tags: [] },
  { text: 'holding onto the past', lang: 'en', wordCount: 4, tags: [] },
  { text: 'moving at my pace', lang: 'en', wordCount: 4, tags: [] },
  { text: 'push code to prod', lang: 'en', wordCount: 4, tags: ['tech'] },
  { text: 'join the standup call', lang: 'en', wordCount: 4, tags: ['tech', 'corporate'] },
  { text: 'at the crossroads now', lang: 'en', wordCount: 4, tags: [] },
  { text: 'in a different light', lang: 'en', wordCount: 4, tags: [] },
  { text: 'on a lonely road', lang: 'en', wordCount: 4, tags: [] },
  { text: 'at the starting line', lang: 'en', wordCount: 4, tags: [] },
  { text: 'in the public eye', lang: 'en', wordCount: 4, tags: [] },
  { text: 'under neon city lights', lang: 'en', wordCount: 4, tags: ['ncr'] },
  { text: 'over hills and valleys', lang: 'en', wordCount: 4, tags: [] },
  { text: 'from dusk until dawn', lang: 'en', wordCount: 4, tags: [] },

  // ---- Hindi ----------------------------------------------------------------
  { text: 'raat ka safar', lang: 'hi', wordCount: 3, tags: ['filmi'] },
  { text: 'dil ki baat', lang: 'hi', wordCount: 3, tags: ['filmi'] },
  { text: 'sapna dekhna', lang: 'hi', wordCount: 2, tags: [] },
  { text: 'raasta milna', lang: 'hi', wordCount: 2, tags: [] },
  { text: 'waqt guzarna', lang: 'hi', wordCount: 2, tags: [] },
  { text: 'dil dhadakna', lang: 'hi', wordCount: 2, tags: [] },
  { text: 'aankh milna', lang: 'hi', wordCount: 2, tags: [] },
  { text: 'baat karna', lang: 'hi', wordCount: 2, tags: [] },
  { text: 'ghar jaana', lang: 'hi', wordCount: 2, tags: [] },
  { text: 'kaam karna', lang: 'hi', wordCount: 2, tags: [] },
  { text: 'raat guzarna', lang: 'hi', wordCount: 2, tags: [] },
  { text: 'subah hona', lang: 'hi', wordCount: 2, tags: [] },
  { text: 'shaam dhalna', lang: 'hi', wordCount: 2, tags: ['filmi'] },
  { text: 'barish hona', lang: 'hi', wordCount: 2, tags: [] },
  { text: 'hawa chalna', lang: 'hi', wordCount: 2, tags: [] },
  { text: 'raasta katna', lang: 'hi', wordCount: 2, tags: ['ncr'] },
  { text: 'office jaana', lang: 'hi', wordCount: 2, tags: ['corporate'] },
  { text: 'meeting attend', lang: 'hi', wordCount: 2, tags: ['corporate'] },
  { text: 'salary aana', lang: 'hi', wordCount: 2, tags: ['corporate'] },
  { text: 'promotion milna', lang: 'hi', wordCount: 2, tags: ['corporate'] },
  { text: 'boss se baat', lang: 'hi', wordCount: 3, tags: ['corporate'] },
  { text: 'team ke saath', lang: 'hi', wordCount: 3, tags: ['corporate'] },
  { text: 'project submit', lang: 'hi', wordCount: 2, tags: ['tech', 'corporate'] },
  { text: 'deadline miss', lang: 'hi', wordCount: 2, tags: ['corporate'] },
  { text: 'film dekhna', lang: 'hi', wordCount: 2, tags: ['filmi'] },
  { text: 'gaana sunna', lang: 'hi', wordCount: 2, tags: ['filmi'] },
  { text: 'hero ban jaana', lang: 'hi', wordCount: 3, tags: ['filmi'] },
  { text: 'dil tut jaana', lang: 'hi', wordCount: 3, tags: ['filmi'] },
  { text: 'pyaar karna', lang: 'hi', wordCount: 2, tags: ['filmi'] },
  { text: 'metro pakadna', lang: 'hi', wordCount: 2, tags: ['ncr'] },

  // ---- Mixed Hinglish -------------------------------------------------------
  { text: 'metro mein late', lang: 'mixed', wordCount: 3, tags: ['ncr'] },
  { text: 'office ka stress', lang: 'mixed', wordCount: 3, tags: ['ncr', 'corporate'] },
  { text: 'weekend ka plan', lang: 'mixed', wordCount: 3, tags: ['ncr'] },
  { text: 'traffic ka scene', lang: 'mixed', wordCount: 3, tags: ['ncr'] },
  { text: 'dhaba pe chai', lang: 'mixed', wordCount: 3, tags: ['ncr'] },
  { text: 'gully ka vibe', lang: 'mixed', wordCount: 3, tags: ['ncr', 'slang'] },
  { text: 'sector ka address', lang: 'mixed', wordCount: 3, tags: ['ncr'] },
  { text: 'cab ka wait', lang: 'mixed', wordCount: 3, tags: ['ncr'] },
  { text: 'deadline ka pressure', lang: 'mixed', wordCount: 3, tags: ['corporate'] },
  { text: 'sprint ka review', lang: 'mixed', wordCount: 3, tags: ['tech', 'corporate'] },
  { text: 'bug ka fix', lang: 'mixed', wordCount: 3, tags: ['tech'] },
  { text: 'code ka review', lang: 'mixed', wordCount: 3, tags: ['tech'] },
  { text: 'prod pe deploy', lang: 'mixed', wordCount: 3, tags: ['tech'] },
  { text: 'standup pe late', lang: 'mixed', wordCount: 3, tags: ['tech', 'corporate'] },
  { text: 'film ka climax', lang: 'mixed', wordCount: 3, tags: ['filmi'] },
  { text: 'song ka hook', lang: 'mixed', wordCount: 3, tags: ['filmi', 'slang'] },
  { text: 'beat pe flow', lang: 'mixed', wordCount: 3, tags: ['slang'] },
  { text: 'bar pe bar', lang: 'mixed', wordCount: 3, tags: ['slang'] },
  { text: 'vibe check karo', lang: 'mixed', wordCount: 3, tags: ['slang'] },
  { text: 'scene set hai', lang: 'mixed', wordCount: 3, tags: ['slang'] },
];
