// lib/types/rhyme.ts
import type { Lang, Phoneme, Stress } from './phonetics';

export type RhymeType =
  | 'perfect'          // identical rhyme tail, different onset: 'grind' / 'mind'
  | 'identical'        // same phonemes AND same word or homophone: 'right' / 'write'
  | 'slant'            // same nucleus, coda within tolerance: 'shape' / 'fake'
  | 'para'             // identical coda skeleton, different nucleus: 'grind' / 'grand'
  | 'consonance'       // consonant skeleton matches, vowels ignored
  | 'assonance-chain'  // nucleus sequence matches across 2+ syllables, coda ignored
  | 'internal'         // a match located before line-final position
  | 'multisyllabic'    // rhyme tail spans 2+ syllables at high match
  | 'mosaic'           // a multi-word phrase rhyming a single word: 'bottle of' / 'hospital'
  | 'holorime'         // an entire line homophonic with another line
  | 'forced';          // below slant tolerance but reachable; flagged as a stretch

export interface RhymeCandidate {
  text: string;
  lang: Lang;
  type: RhymeType;
  score: number;                // 0-1
  phonemes: Phoneme[];
  syllableCount: number;
  /** English gloss, mandatory for Hindi suggestions so the panel is readable at a glance. */
  gloss?: string;
  isCrossLanguage: boolean;
  tags: string[];               // 'ncr', 'tech', 'filmi', 'slang', 'corporate'
}

/**
 * One searchable word in the rhyme index. Deliberately flat and string-heavy:
 * this shape is JSON, shipped to the worker, and parsed into `Phoneme[]` lazily
 * only for the handful of lexemes a query actually scores.
 */
export interface Lexeme {
  text: string;
  lang: Lang;
  /** Unified-inventory IPA for the whole word. */
  ipa: string;
  /** Nucleus sequence joined by '_'. The assonance and slant-rhyme lookup key. */
  assonanceKey: string;
  /** From the last primary-stressed nucleus to the end. The perfect-rhyme lookup key. */
  rhymeTail: string;
  syllableCount: number;
  /** Per-syllable stress, so `stressAlignment` needs no re-syllabification. */
  stress: Stress[];
  gloss?: string;
  tags: string[];
  /** Frequency rank; lower is more common. Drives index trimming and result ordering. */
  rank: number;
}

/** Generated by lib/engine/index-builder.ts, consumed in the worker. */
export interface RhymeIndex {
  lexemes: Lexeme[];                        // flat; id === array position
  byNucleusSeq: Record<string, number[]>;   // assonanceKey -> lexeme ids
  byRhymeTail: Record<string, number[]>;    // exact tail -> lexeme ids
  byTag: Record<string, number[]>;
  version: number;
}
